講座削除機能（講師側）条件分岐（杉原）
yukihiroLaravel/juko_laravel pull request #103
Opened 2023-06-09 14:33 UTC by kenta327

## 概要
・ 講座削除機能（講師側）受講中の生徒がいた場合は削除しない　条件分岐
## 動作確認手順
・attendancesテーブルにcourse_id = 1のデータとcoursesテーブルのid=1のデータを作成しておく。
・postマン DELTEメソッドでhttp://localhost:8080/api/v1/instructor/course/1　send　ボタン押下する
・coursesテーブルのid = 1 のデータは削除されていない事を確認
・postマン DELTEメソッドでhttp://localhost:8080/api/v1/instructor/course/2　send　ボタン押下する

・
## 確認してほしいこと
・

2023-06-09 14:38 UTC, yukihiroLaravel requested changes

2023-06-09 14:38 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/CourseController.php
> +        ->exists();
インデントつける

2023-06-09 14:38 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/CourseController.php
> +        }
```
$result = false;
if(!$attendance){
            $course->delete();
            $result = true;
}
return response()->json([
            "result" => $result
]);
```

2023-06-10 11:01 UTC, kenta327 commented on app/Http/Controllers/Api/Instructor/CourseController.php
> +        ->exists();
インデント修正しました。

2023-06-10 11:02 UTC, kenta327 commented on app/Http/Controllers/Api/Instructor/CourseController.php
> +        }
修正しました。

2023-06-10 13:20 UTC, Hikaru-Giannis reviewed
course_id = 1のdeleted_atをadminerで日時更新した場合は、どうなりますか？

2023-06-10 13:20 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/CourseController.php
> +            ->exists();
Laravelは論理削除の機能を持っているので、`whereNull('deleted_at')`は不要にして書くことができます。
しかし、現時点ではどこかにその論理削除の設定が不足しているので、それらの機能を有効するためにはどうすればよいか一度調べてみてください！

わからなければ、ご質問等していただければと思います！

2023-06-11 13:48 UTC, kenta327 commented on app/Http/Controllers/Api/Instructor/CourseController.php
> +            ->exists();
> course_id = 1のdeleted_atをadminerで日時更新した場合は、どうなりますか？

deleted_atを日時更新した場合は削除されているユーザーとみなされているのでコースは削除されます。

2023-06-11 15:48 UTC, kenta327 commented on app/Http/Controllers/Api/Instructor/CourseController.php
> +            ->exists();
> Laravelは論理削除の機能を持っているので、`whereNull('deleted_at')`は不要にして書くことができます。 しかし、現時点ではどこかにその論理削除の設定が不足しているので、それらの機能を有効するためにはどうすればよいか一度調べてみてください！
> 
> わからなければ、ご質問等していただければと思います！

ご指摘、いただきありがとうございます。
モデルにsoftdeleteを定義した場合、確かに論理削除されているデータは除外して取得されている事が確認できました。
よってwhereNull('deleted_at')の記述は削除しました。
よろしくお願いします。

2023-06-12 13:26 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/CourseController.php
> +        }
動作自体は問題ないです！
しかし、コードの可読性という観点でもう少し良い書き方ができそうです。
例えば、早期リターンという方法を利用したり(一度調べてみてください！)、変数の扱い、if分の検証の扱いとかですかね。(人による好みも含んでしまうので正解はないです。)
あとは、こちらが意図的に削除できないエラーを返す場合は、メッセージをつけて理由を教えてあげましょう！

上の指摘を反映したサンプルコードを提示するので、参考にしてみてください。(自分の好みも含んでいます)
ただ真似るだけでなく、意味を理解しながら実装すると良いと思います！

````php
    /**
     * 講座削除API
     *
     * @param CourseDeleteRequest $request
     * @return JsonResponse
     */
    public function delete(CourseDeleteRequest $request)
    {
        $course = Course::findOrFail($request->course_id);
        if (Attendance::where('course_id', $request->course_id)->exists()) {
            return response()->json([
                "result" => false,
                "message" => "This course has already been taken by students."
            ]);
        }
        $course->delete();
        return response()->json([
            "result" => true,
        ]);
    }
````

2023-06-14 13:00 UTC, kenta327 commented on app/Http/Controllers/Api/Instructor/CourseController.php
> +        }
ご指摘いただいた通り私の書いたコードだと可読性の面で
分かりにくい記述になっておりましたので
kouさんから提示されたサンプルコードと見比べてみたところ
あきらかに読みやすく判りやすいので全て書かれているコードを理解した上で踏襲させていただきました。

2023-06-14 13:56 UTC, Hikaru-Giannis approved these changes

2023-06-14 14:13 UTC, merged