レッスン更新APIのプルリクエスト
yukihiroLaravel/juko_laravel pull request #121
Opened 2023-06-27 13:34 UTC by Hikaru-Giannis

2023-06-28 01:33 UTC, yukihiroLaravel requested changes

2023-06-28 01:33 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                'status' => 'private',
１点だけ気になったのですが、

   'status' =>  Lesson::STATUS_PRIVATE,

ではなく、

   'status' => 'private',

で大丈夫なのでしょうか？

2023-06-28 09:04 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                'status' => 'private',
よくないですね...
修正を依頼します！

2023-06-28 12:50 UTC, ka2ki1 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                'status' => 'private',
対応しました

2023-07-01 05:53 UTC, yukihiroLaravel approved these changes
OKです。まーじしました！

2023-07-01 05:53 UTC, merged