Feature/goto/jka123/create controller route
yukihiroLaravel/juko_laravel pull request #29
Opened 2023-04-11 13:21 UTC by GotoAkane

＃＃　やったこと　
- 編集画面の作成　-
＃＃　確認方法
- ポストマンにて-
-http://localhost:8080/api/v1/course/1/edit
course_id、title、imageが表示されることを確認
以上よろしくお願いいたします。

2023-04-16 03:33 UTC, Hikaru-Giannis commented on app/Http/Requests/Instructor/CoursesIndexRequest.php
> +    /**
このプロジェクトではある程度リクエストファイルの命名形式を統一しているので、
`CourseEditRequest`に変更するようにお願いします！

2023-04-16 14:10 UTC, GotoAkane commented
## 質問があります。
コード確認よろしくお願いいたします。

2023-04-18 12:59 UTC, GotoAkane commented
プルリク作成しました。
確認よろしくお願いいたします。

2023-04-19 07:58 UTC, yukihiroLaravel requested changes
指摘の点を修正お願いします！

2023-04-19 07:58 UTC, yukihiroLaravel commented on app/Http/Resources/Instructor/CourseEditResponse.php
> +    });
インデントがおかしいので、修正しましょう！
下記のような感じです！

```
return $this->resource->map(function($course) {
        return [
            'course_id' => $course->id,
            'title' => $course->title,
            'image' => $course->image,
        ];
});
```

2023-04-19 07:58 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/CourseController.php
> +
ここは、下の方と同じように
`*`
があった方がいいと思います！

2023-04-19 12:21 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/CourseController.php
> +
この書き方は問題があるので、修正する必要があります。
次のようコードを参考に記述することができます。
現状は連想配列が渡されるため、コレクション形式でレスポンスを取得しております。

````
    public function edit(CourseEditRequest $request)
    {
       $course = Course::findOrFail($request->course_id);
       return new CourseEditResponse($course);
    }
````

2023-04-19 12:21 UTC, Hikaru-Giannis commented on app/Http/Resources/Instructor/CourseEditResponse.php
> +        ];
コントローラーを指摘通りに修正すると、下記で記述が済むようになります！

````
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'course_id' => $this->resource->id,
            'title' => $this->resource->title,
            'image' => $this->resource->image,
        ];
    }
````

2023-04-20 16:35 UTC, GotoAkane commented
プルリクの修正しましたので、確認よろしくお願いいたします。

2023-04-21 14:12 UTC, Hikaru-Giannis reviewed
問題ないと思います！お疲れ様でした。

2023-04-22 07:13 UTC, merged