DB操作するメインロジック実装
yukihiroLaravel/juko_laravel pull request #346
Opened 2023-11-28 10:56 UTC by doncouchi

## 概要
- 「この受講生を講座から退会」させるボタン押下時のAPI作成、受講生削除機能をコントローラーに追加しました。

## 確認したこと
- postmanにてartendance_id 1で"result": trueが出ることを確認。
- データベース上でartendance_id 1が削除されることを確認。

## 確認してほしいこと
- 実在していない受講生を削除などする場合エラーになるのですが、エラーになる場合の表示画面は作成したほうがいいでしょうか？
- インデントなどコードが間違ってないか

2023-11-28 14:54 UTC, yukihiroLaravel requested changes
質問についてコメントしましたのでご確認ください！

2023-11-28 14:54 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            $attendance = Attendance::find($attendanceId);
ご質問の存在しないものを消そうとするとエラーになる
という話ですが、

findの代わりに
findOrFail という関数を使うと対応できると思います！

存在しないIDを入れてテストしてみてください！

2023-11-28 16:36 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
ER図を確認いただきたいのですが、受講状態の他にレッスン個別の状態を管理している`lesson_attendances`テーブルが存在します。

この受講状態を削除する時点で削除しないと、講座は退会しているのにレッスンは受講中という不整合が起きますのでそちらの対応もお願いしたいです！

2023-12-08 14:30 UTC, yukihiroLaravel requested changes
コメントしましたので、ご確認ください！

2023-12-08 14:30 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                }
このif文は他の部分を参考にされて書かれた感じでしょうか？
丸々不要かと思いました💦

2023-12-09 11:53 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            $attendance->delete();
こちら動作としては、問題ないです！
次はもう1歩応用した方法で実装してみましょうか！
というのは、Attendanceモデルが削除されるイベントを検出して、それをトリガーに`LessonAttendance`を削除するといった方法です！

次の記事やCourse、Chapterでは既にこの方法で実装されているので参考にすると良いと思います！
https://zenn.dev/usmoo/articles/f3b101eb51ae3a

2023-12-09 11:53 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            \Log::error($e);
バックスラッシュは既にクラスがインポートされているので不要です！

2023-12-10 14:23 UTC, yukihiroLaravel reviewed
１点Kouさんにお伺いしたいので記述したのと、
他に指摘あればお願いします！

2023-12-10 14:23 UTC, yukihiroLaravel commented on app/Model/Attendance.php
> +            $attendance->lessonAttendances()->delete();
@Hikaru-Giannis 
この書き方でもOKかと思いますが、
Course.phpの内容を踏襲するなら、
```
foreach ($attendance->lessonAttendances as $child) {
    // 削除内容
}
```
みたいに統一したほうがいいかと思いましたが
いかがでしょうか？

2023-12-11 01:18 UTC, Hikaru-Giannis commented on app/Model/Attendance.php
> +            $attendance->lessonAttendances()->delete();
@yukihiroLaravel 

個人的にはこの記述では問題ないと思います！
理由としては`foreach`と比較してこちらの記述の方が可読性、保守都的な観点からメリットが大きいため、あえて崩す必要はないと判断しました。

2023-12-11 01:18 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
こちらは実際に動作確認されていましたでしょうか？
私の方では、次のエラーで動作確認ができませんでした。

````log
Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [App\Model\Attendance].
````

`attendance_id`はURLから取得するため、リクエストの`attendance_id`の取得の方法を確認してみると良いかもしれないです😊

2023-12-11 01:18 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
こちらは、attendanceテーブルとlesson_attendancesテーブルの複数テーブルからレコードを削除するため、トランザクションを考慮する必要があります！
他のコントローラーにトランザクションの実装が記述されているので、参考にしてみてください。

トランザクションとはだと次の記事とか参考になるかもしれないです！
https://swri.jp/glossary/%E3%83%88%E3%83%A9%E3%83%B3%E3%82%B6%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3

2023-12-11 01:20 UTC, Hikaru-Giannis reviewed
`database/migrations/2022_10_29_022717_create_lesson_attendances_table.php`に'lesson_id'と`attendance_id`が定義されているのですが、外部キー制約がなかったため、定義をお願いしてもよろしいでしょうか？

お手数をおかけしますが、よろしくお願いします🙇‍♂️

2023-12-11 03:04 UTC, yukihiroLaravel requested changes

2023-12-11 03:04 UTC, yukihiroLaravel commented on app/Model/Attendance.php
> +            $attendance->lessonAttendances()->delete();
@Hikaru-Giannis 
かしこまりました！
@doncouchi 
では今の書き方でいきましょう！

2023-12-16 02:30 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
現状の実装はどの講師でもリクエストした受講データを削除することができてしまいます！
そのため、認証している講師のidと削除対象の受講データの講座の講師が一致しない場合は、エラーを返すようにお願いします🙇‍♂️

2023-12-18 13:38 UTC, yukihiroLaravel requested changes
こんな感じで実装

2023-12-18 13:38 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            if ($attendance->lessonAttendances->lesson->id !== $attendanceId) {
Auth::guard('instructor')->user()->id;

2023-12-19 00:20 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            if (Auth::guard('instructor')->user()->id !== $attendance->instructor_id) {
ER図を拝見してほしいのですが、`attendances`テーブルには、`instructor_id`カラムがないですのでこれだと機能してない状態でした！
ヒントとして、`attendances`には`course_id`がありますので、その講座の講師idを参照すればうまくいくかもしれないです...！

2023-12-20 00:14 UTC, Hikaru-Giannis approved these changes

2023-12-20 00:55 UTC, yukihiroLaravel approved these changes
OKです！
マージしました！

以前MTGでお伝えしたことができていなかったので
お伝えした内容をしっかり理解して進めていきましょう✨

2023-12-20 00:56 UTC, merged