#568 自分と配下のinstructorの講座情報のみにアクセスできるロジックの作成(kumiko)
yukihiroLaravel/juko_laravel pull request #359
Opened 2023-12-05 13:37 UTC by kuminmi

## issue
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-568

## 概要
- 自分と配下のinstructorの講座情報のみにアクセスできるロジックの作成

## 動作確認手順
- GETリクエストにて
　/api/v1/manager/course/{course_id}/edit
　にアクセスすると、
　自分（ログイン中の講師[兼マネージャー]）の持っている講座と配下の講師が持っている講座の情報を取得できる。
- 配下にない講師の講座のidを入れるとエラーが返ってくる。

## 考慮して欲しいこと
- コードについて完全に理解はしていませんが他のメソッドに使われている内容を真似して書きました。

## 確認して欲しいこと
- エラー文を返すやり方がわかりませんでした。合っているか、またはより明瞭な書き方があればご教授いただきたいです。

2023-12-05 14:36 UTC, yukihiroLaravel requested changes
確認しましたが、
かなり核心に近づいてきた感じがします！☺️

ただいくつかコメントしましたのでご確認ください！

2023-12-05 14:36 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/CourseController.php
> +                'message' => "Not allowed to edit this course.",
エラーメッセージは、他のところに習って

"Forbidden, not allowed to edit this course."

の方がいいかと思いました！

2023-12-05 14:36 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/CourseController.php
> +        // エラー応答
この文字がインデントずれていますので修正願います。

2023-12-05 14:36 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/CourseController.php
> +        } else{
結果は同じなのですが
下記のようなelseを使わない書き方の方がスッキリするので
こちらに書き換えましょう！

```
if (!in_array($course->instructor_id, $instructorIds, true)) {
     // エラー対応
}
return response()->json($course);
```

2023-12-05 14:36 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/CourseController.php
> +                ->get();
下の

return response()->json($courses);

のところは$coursesが複数形ではなく
単数形$courseになると思うので
ここの４行丸々削除でいい気がします。

2023-12-05 14:36 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/CourseController.php
> +            return response()->json($courses);
正しいのは１つの
$course
だけの情報を返すレスポンスのはずなので
複数形なのはおかしいと思います。
単数形$courseが正しいですかね

2023-12-06 04:50 UTC, yukihiroLaravel requested changes
理解が進みよかったです☺️
もう一歩だけ修正願います！

2023-12-06 04:50 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/CourseController.php
> +            if (!in_array($course->instructor_id, $instructorIds, true)) {
下記エラー対応のコメントアウトではなく

```
if(~){
}
```

の方のインデントがズレていました（今回の修正でズレた？）
ので１つインデントを左に移動願います

2023-12-06 04:50 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/CourseController.php
> +                'message' => "Forbidden,not allowed to edit this course.",
細かいですが、 not の前に一つスペースがあった方がいいかと思いました！
"Forbidden, not allowed to edit this course."

2023-12-06 12:06 UTC, kou-tech approved these changes

2023-12-06 12:59 UTC, yukihiroLaravel approved these changes
マージしました！
おつかれさまでした！！

2023-12-06 12:59 UTC, merged