#595 自分と配下のinstructorの作成したチャプターを更新できるロジック作成（ごめ）
yukihiroLaravel/juko_laravel pull request #366
Opened 2023-12-09 14:31 UTC by gomez8927

## issue
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-595

## 概要
- 自分と配下のinstructorの作成したチャプターを更新できるロジック作成

## 動作確認手順
- GETリクエストにて
　/api/v1/manager/course/{course_id}/chapter/{chapter_id}
　にアクセスすると、
　自分（ログイン中の講師[兼マネージャー]）の持っているチャプターと配下の講師が持っているチャプターの情報を取得できる。
- 配下にない講師の講座のidを入れるとエラーが返ってくる。

## 考慮して欲しいこと
- 特にありません
## 確認して欲しいこと
- 特にありません

2023-12-10 00:14 UTC, yukihiroLaravel requested changes
レビューしましたので、ご確認ください😃

2023-12-10 00:14 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        if ($chapterInstructorId === $instructorId || in_array($chapterInstructorId, $instructorIds, true)) {
$chapterInstructorId === $instructorId
これは不要かと思います！

$chapterInstructorId の中身は真上で定義しているとおり chapterのIDなので
チャプターID と　インストラクターID は別物になると思いますので
この一文はおかしい気がしますね💦

2023-12-10 00:14 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +                'data'    => $chapter, // 更新されたチャプター情報を返す
レスポンスで
メッセージは含めない仕様になっていたかと思うので、こちらの
message　と　data の返却は不要ですね！

2023-12-10 00:14 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            // エラー応答（権限がない場合）
下記のkumikoさんのように

https://github.com/yukihiroLaravel/juko_laravel/pull/359/files

条件文の中身も今と逆で!をつけて結果を反転させることで
成功→失敗の順でなく
失敗→成功の順に変えて
```
if (!in_array($chapterInstructorId, $instructorIds, true)) {
   // 失敗結果を返す
    return response()->json([
                'result'  => false,
                'message' => "Forbidden, not allowed to edit this chapter.",
     ], 403);
}
return response()->json([
          'result'  => true,
]);

```
結果は変わらないのですが
elseをわない書き方（早期リターンなどと言います）の方が
シンプルで見やすいので、このような書き方に変えてみましょう

2023-12-10 00:14 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            // エラー応答（権限がない場合）
また、失敗の条件でなかった場合に
更新を実行するという一番大事な処理が抜けていると思いますので
お伝えの通り、

app/Http/Controllers/Api/Instructor/ChapterController.php
のupdateメソッドを参考に
更新の処理を記述しましょう！

2023-12-10 06:49 UTC, gomez8927 commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +                'data'    => $chapter, // 更新されたチャプター情報を返す
訂正しました

2023-12-10 06:57 UTC, gomez8927 commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        if ($chapterInstructorId === $instructorId || in_array($chapterInstructorId, $instructorIds, true)) {
訂正しました

2023-12-10 07:08 UTC, gomez8927 commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            // エラー応答（権限がない場合）
elseをつわないシンプルな書き方に修正しました
更新を実行するコードを追加しました

2023-12-10 14:14 UTC, yukihiroLaravel requested changes
１点指摘しました！

2023-12-10 14:14 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        Log::info('Request Data:', $request->all());
このログは不要ですので削除ください！

2023-12-10 14:25 UTC, gomez8927 commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        Log::info('Request Data:', $request->all());
訂正しました

2023-12-11 01:23 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        $chapterInstructorId = $chapter->id;
こちらは`chapter`テーブルの主キーのidを参照しており、コメントの講師IDを取得というのは間違いではないでしょうか？

2023-12-11 03:03 UTC, yukihiroLaravel requested changes

2023-12-11 03:03 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        $chapterInstructorId = $chapter->id;
@gomez8927 
こちら昨日指摘したと思いますが、pushがまだでしたかね・・・？

2023-12-11 18:49 UTC, gomez8927 commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        $chapterInstructorId = $chapter->id;
訂正しました

2023-12-16 02:39 UTC, Hikaru-Giannis approved these changes

2023-12-16 03:30 UTC, yukihiroLaravel approved these changes
OKです！
マージしました☺️
おつかれさまでした！

少しずつ理解深めていきましょう❗️

2023-12-16 03:30 UTC, merged