#JKA606 ロジックの作成(kumiko)
yukihiroLaravel/juko_laravel pull request #374
Opened 2023-12-12 13:39 UTC by kuminmi

## issue
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-604
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-606
## 概要
- 新権限マネージャー設立による配下のinstructorの作成したチャプター削除できるAPI作成における、
- 子課題②ロジックの作成
## 動作確認手順
- postmanにて
deleteリクエストで/api/v1/manager/course/{course_id}/chapter/{chapter_id}にアクセスすると
```
{
  "result": true
}
```
　が返ってくることを確認。
- ログインしているマネージャー自身と配下のインストラクターが持つコースのチャプターでない場合は
```
{
    "result": false,
    "message": "Forbidden, not allowed to delete this chapter."
}
```
　が返ってくることを確認。
- Adminerにて
対象のコースのチャプターの[deleted_at]カラムに反映されていることを確認。
またその際、コースは残り、チャプターのみが消えていることも確認。
## 考慮して欲しいこと
- 特にありません
## 確認して欲しいこと
- より良い書き方があればご教授願います。

2023-12-12 14:21 UTC, yukihiroLaravel requested changes
コメントご確認ください。

2023-12-12 14:21 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        //自分と配下のインストラクターが持っている講座を取得
文言

2023-12-12 14:21 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +
その講座($request->course_id)の中に
本当にそのチャプターID($request->chapter_id)が存在するかどうか？
を確認する条件分岐が必要！

2023-12-12 14:21 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +
整合性確認が必要

2023-12-15 01:08 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +use Illuminate\Support\Facades\Auth;
参照していないクラスは、インポート(=use)しないようにお願いします！

2023-12-16 02:54 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +
27行目で講座情報取得していますが、28行目のチャプターの講座情報の講師id(=`instructor_id`)で比較すると余計なDBアクセスが減ると思うのですがいかがでしょうか？

2023-12-16 13:51 UTC, Hikaru-Giannis approved these changes

2023-12-16 13:58 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
お疲れ様でした！

2023-12-16 13:58 UTC, merged