#609 講師のチャプター関連APIで、講座作成した講師のみしかチャプターのステータス更新・削除できないように制限する(ごめ)
yukihiroLaravel/juko_laravel pull request #392
Opened 2023-12-23 15:13 UTC by gomez8927

## issue
https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-609

## 概要
- 講師のチャプター関連APIで、講座作成した講師のみしかチャプターのステータス更新・削除できないように制限する
## 動作確認手順
- RLのchapter_idが、講座作成した講師のチャプターであれば以下のレスポンスが返ってくること。
```
{
    "result": true,
    "data": {
        "chapter_id": 1,
        "title": "チャプタータイトル"
    }
}
```
## 考慮して欲しいこと
- 今回参考にした「Swagge」はhttp://localhost:8080//api/v1/instructor/course/{course_id}/chapter/{chapter_id}
　
## 確認して欲しいこと
- 今回は「URLのchapter_idが本当にURLの講座(couse)の所属のチャプターなのかの照合」はしておりませんが、する必要はありますでしょうか？
- またupdateStatusとdeleteでは若干コードが違いますが、揃えるべきか、このままの方が適切か教えてください
```
Chapter::findOrFail($request->chapter_id)
            ->update([
                'status' => $request->status
        ]);

        return response()->json([
            'result' => true,
        ]);
```
```
$chapter = Chapter::findOrFail($request->chapter_id);
        $chapter->delete();
        return response()->json([
            "result" => true
        ]);
```

2023-12-24 08:14 UTC, yukihiroLaravel requested changes
いくつかコメントしました！

- 今回は「URLのchapter_idが本当にURLの講座(couse)の所属のチャプターなのかの照合」はしておりませんが、する必要はありますでしょうか？
→こちら古澤さんにはお伝えしていて、ごめさんにはお伝えしておらずすみません！
　照合必要ですのでご対応お願いします！

- またupdateStatusとdeleteでは若干コードが違いますが、揃えるべきか、このままの方が適切か教えてください
　→ すみません、これはどこの部分でしょうか？
　　書いていただいている部分のコードは特に修正が必要そうに見えませんが、、、。

2023-12-24 08:14 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                "message" => "Not authorized."
すみません！
参考にされた部分が上記になっていたと思いますが
メッセージは下記の方がふさわしいかと思いました！

Invalid instructor_id

2023-12-24 08:14 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                "message" => "Not authorized."
すみません！
参考にされた部分が上記になっていたと思いますが
メッセージは下記の方がふさわしいかと思いました！

Invalid instructor_id

2023-12-24 13:27 UTC, gomez8927 commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                "message" => "Not authorized."
変更しました

2023-12-24 13:27 UTC, gomez8927 commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                "message" => "Not authorized."
変更しました

2023-12-25 12:13 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                "message" => 'invalid instructor_id.'
resultの値が論理型ではなく、文字列型になっているので修正をお願いします。

2023-12-25 12:13 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                "message" => 'invalid instructor_id.'
resultの値が論理型ではなく、文字列型になっているので修正をお願いします。

2023-12-25 12:13 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                "message" => 'invalid instructor_id.'
チャプター情報取得する際の講座情報を利用すれば、不要なデータベースのI/Oを減らせると思うのですがいかがでしょうか？

2023-12-25 12:13 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                "message" => 'invalid instructor_id.'
チャプター情報取得する際の講座情報を利用すれば、不要なデータベースのI/Oを減らせると思うのですがいかがでしょうか？

2023-12-27 13:52 UTC, gomez8927 commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                "message" => 'invalid instructor_id.'
訂正しました

2023-12-27 13:52 UTC, gomez8927 commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                "message" => 'invalid instructor_id.'
訂正しました

2023-12-28 13:22 UTC, Hikaru-Giannis approved these changes

2023-12-28 14:53 UTC, yukihiroLaravel approved these changes
問題ないのでマージしました！
おつかれさまでした！☺️

2023-12-28 14:53 UTC, merged