#jka-620 ロジックの作成(kumikio)
yukihiroLaravel/juko_laravel pull request #393
Opened 2023-12-24 14:54 UTC by kuminmi

## タスク
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-610
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-620
## 概要
- 新権限マネージャー設立による配下のinstructorの作成した講座にチャプターを新規登録できるAPI作成
における、ロジックの作成
## 動作確認手順
- ログイン中のマネージャーが自分と配下のインストラクターが持つ講座のチャプターを新規登録する
- POSTリクエストにて
/api/v1/manager/course/{course_id}/chapter/
- body
{
  "title": "Hello Worldを出力する"
}
- レスポンス
{
  "result": true
}
を確認。
## 考慮して欲しいこと
- 特にありません
## 確認して欲しいこと
- $orderの部分、考えてみました。書き方はこれでいいのかご確認よろしくお願いします。

2023-12-25 03:57 UTC, yukihiroLaravel requested changes
概ねOKかと思いますが
１点コメントしました！

2023-12-25 03:57 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        $chapters = $course->chapters->all();
こちらの$chapters という変数は使っていないので
丸々３０行目は不要じゃないでしょうか？

2023-12-25 05:27 UTC, kuminmi commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        $chapters = $course->chapters->all();
ご指摘ありがとうございます。修正いたしました！

2023-12-25 12:17 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        $order = $course->chapters()->count();
この記述ではデータベースのレコード数を取得しているのは意図的ですか...？
やり方として、次の2つがあると思われたのですが、どちらを意図しているのか確認したかったです！

1. 講座情報を取得するときに関連するチャプター情報も取得し、その数を合計
2. DBで講座IDを条件にレコード数を合計

2023-12-25 12:17 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        $chapter = Chapter::create([
$chapterの変数は他でも利用していないので、今回変数への格納は不要かと思います！

2023-12-26 14:11 UTC, kuminmi commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        $chapter = Chapter::create([
承知しました。

2023-12-26 14:11 UTC, kuminmi commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        $order = $course->chapters()->count();
2.のつもりでしたが、
理由としては、orderの最大の数を取得して１を足した数が新規作成したチャプターのorderの数字になると考えたからです。
しかし、このままだとチャプターが削除された場合や、orderが2から始まっている場合などはダメだということに気がつきましたので
他の方法を考えてみようと思います。
kouさんが気が付かれたのはその点だったのでしょうか？

2023-12-27 12:13 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        $order = $course->chapters()->count();
いえ、ただの意図的であるかの確認です！

> チャプターが削除された場合や、orderが2から始まっている場合などはダメだ

そもそも不整合を起こさないようにするのが適切ですので、現状で問題ないですよ！

2023-12-27 12:13 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        $order = $course->chapters()->count();
なるべく変数のスコープは小さくしたいので、createメソッド前で行いましょう！
また、原則変数は更新しない方が良いです！
- バグの発生リスクの向上
- プログラムの複雑性

```php
        $order = $course->chapters()->count();
        $newOrder = $order + 1;
        Chapter::create([
            'course_id' => $course_id,
            'title' => $request->input('title'),
            'order' => $order,
            'status' => Chapter::STATUS_PRIVATE,
         ]);

        return response()->json([
            'result' => true,
        ]);
```

2023-12-27 23:11 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            'order' => $order,
ここも$newOrderですね！

2023-12-28 00:52 UTC, kuminmi commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            'order' => $order,
ですよね、すみません。
修正いたします。

2023-12-28 13:19 UTC, Hikaru-Giannis approved these changes

2023-12-28 14:54 UTC, yukihiroLaravel approved these changes
問題ないのでマージしました！
おつかれさまでした！☺️

2023-12-28 14:54 UTC, merged