#640 講師のチャプター新規登録APIで、講座を本当にその講師が作ったものかを照合する(ごめ)
yukihiroLaravel/juko_laravel pull request #402
Opened 2024-01-04 04:22 UTC by gomez8927

## issue
https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-640

## 概要
- 講師のチャプター新規登録APIで、講座を本当にその講師が作ったものかを照合する
## 動作確認手順
- RLのcourse_idが、講座作成した講師のであれば以下のレスポンスが返ってくること。
```
{
        return [
            'course_id' => $this->course_id,
            'chapter' => [
                'chapter_id' => $this->id,
                'title' => $this->title,
            ]
        ];
    }
```
- 違った場合
```
return response()->json([
                    'result' => false,
                    'message' => 'Invalid instructor_id for this course.',
                ], 403);
```

## 考慮して欲しいこと
- 特になし
　
## 確認して欲しいこと
- 特になし

2024-01-04 04:58 UTC, yukihiroLaravel requested changes
１点レビューしましたのでご確認ください！

2024-01-04 04:58 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +            $user = Instructor::find($request->user()->id);
$request->user()->id
ではなく、
Auth::user~
の方を使いましょう！

2024-01-04 06:47 UTC, gomez8927 commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +            $user = Instructor::find($request->user()->id);
訂正しました

2024-01-04 14:13 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +            $order = $course->chapters->count();
ここで講座に関連するチャプターをDBから取得して、そのカウントを計上するなら次のどちらかがいいと思います。
1. 講座情報を取得する時にチャプター情報も取得する。
2. DBのチャプターテーブルに対して、講座idを条件にカウントを取得する。

2024-01-04 21:54 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +            $course = $course->fresh('chapters');
この記述は後に$courseを参照している形跡がないので、不要ではないですかね...？

2024-01-04 22:30 UTC, Hikaru-Giannis approved these changes

2024-01-05 00:26 UTC, yukihiroLaravel requested changes
コメントしました！

2024-01-05 00:26 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +            $user = Auth::user();
Auth::guard('instructor')->user();

この書き方にしましょう！

2024-01-05 00:45 UTC, yukihiroLaravel approved these changes
マージしました！

2024-01-05 00:45 UTC, merged