新権限マネージャー設立による配下のinstructorの作成したチャプター公開状態変更API作成
yukihiroLaravel/juko_laravel pull request #407
Opened 2024-01-07 08:36 UTC by gomez8927

2024-01-07 08:38 UTC, yukihiroLaravel requested changes

2024-01-07 08:38 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +use Illuminate\Http\Request;
お手数ですが、こちらは不要になったかと思いますので削除願います！

2024-01-07 23:57 UTC, Hikaru-Giannis approved these changes

2024-01-08 00:37 UTC, yukihiroLaravel approved these changes
マージしました！おつかれさまでした！

2024-01-08 00:37 UTC, merged