#jka-647 try~catchを追加(kumiko)
yukihiroLaravel/juko_laravel pull request #408
Opened 2024-01-07 14:07 UTC by kuminmi

## タスク
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-610
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-647
## 概要
- 新権限マネージャー設立による配下のinstructorの作成した講座にチャプターを新規登録できるAPI作成のtry~catchを追加
## 動作確認手順
- ログイン中のマネージャーが自分と配下のインストラクターが持つ講座のチャプターを新規登録する
- POSTリクエストにて  
/api/v1/manager/course/{course_id}/chapter/
- body  
```
{  
   "title": "Hello Worldを出力する"  
}
```
- レスポンス  
```
{  
   "result": true  
}
```
を確認。
## 考慮して欲しいこと
- コンフリクトが起こった際にshowメソッドを触ったためインデントの調整を行っています。
## 確認して欲しいこと
- 特にありません

2024-01-08 00:38 UTC, yukihiroLaravel requested changes
コメントしました！

2024-01-08 00:38 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +             ], 403);
インデントがスペース４つ分になっていない気がします！
１つスペース削除が必要ですかね。

2024-01-08 00:38 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +             return response()->json([
インデントがスペース４つ分になっていない気がします！
１つスペース削除が必要ですかね。

2024-01-08 08:08 UTC, Hikaru-Giannis requested changes

2024-01-08 08:08 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        } catch (Exception $e) {
`Exception`がインポートされている形跡がないので、インポートするようにお願いします。

2024-01-08 08:08 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
phpdocの@returnの記述もお願いします！

```php
@return \Illuminate\Http\JsonResponse
```

2024-01-08 13:27 UTC, kuminmi commented on app/Http/Controllers/Api/Manager/ChapterController.php
承知しました！

2024-01-08 13:27 UTC, kuminmi commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        } catch (Exception $e) {
修正しました！

2024-01-08 13:27 UTC, kuminmi commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +             return response()->json([
修正しました！

2024-01-08 13:27 UTC, kuminmi commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +             ], 403);
修正しました！

2024-01-09 03:45 UTC, Hikaru-Giannis approved these changes

2024-01-09 04:55 UTC, yukihiroLaravel approved these changes
マージしました！

2024-01-09 04:55 UTC, merged