JKA-648_(dera)_ルート変更・コントローラ改修_(JKA-624)講師情報更新APIの改修
yukihiroLaravel/juko_laravel pull request #410
Opened 2024-01-09 12:13 UTC by Jino225242

## issue
 タスク　[JKA-648:ルート変更・コントローラ改修_(JKA-624)講師情報更新APIの改修](https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-648)

## 概要
1.ルート変更
　URLを /api/v1/instructor/{instructor_id} → /api/v1/instructor/update に変更
2. コントローラ改修①
　instructor_idはリクエストからではなく、認証者のidを参照
3. コントローラ改修②
　バリデーションのメールアドレスにおいて、前後同じのままであればTrue、そうでなければDBでのユニークチェック
4. コントローラ改修③
　プロフィール画像のリクエストがない場合は、以前の状態を保持

## 動作確認手順
/api/v1/instructor/update　において、

1. nick_name：*****(任意テキスト), last_name：*****(任意テキスト),first_name：*****(任意テキスト), email：*****(任意メールアドレス),profile_image：*****(任意ファイル)をリクエストボディとして実行することで、
```
{
    "result": true,
    "data": {
        "nick_name": "*****(任意テキスト)",
        "last_name": "*****(任意テキスト)",
        "first_name": "*****(任意テキスト)",
        "email": "*****(任意メールアドレス)",
        "profile_image": "instructor/*****(任意ファイル).jpg",
        "type": "manager" もしくは "instructor"
    }
}
```
が出力されることを確認

2.nick_name：*****(任意テキスト), last_name：*****(任意テキスト),first_name：*****(任意テキスト), email：*****(任意メールアドレス),profile_image：null(リクエスト無し)をリクエストボディとして実行することで、 
```
{
    "result": true,
    "data": {
        "nick_name": "*****(任意テキスト)",
        "last_name": "*****(任意テキスト)",
        "first_name": "*****(任意テキスト)",
        "email": "*****(任意メールアドレス)",
        "profile_image": "instructor/*****(任意ファイル).jpg",     ←以前の状態を保持
        "type": "manager" もしくは "instructor"
    }
}
```
が出力されることを確認

3.nick_name：*****(任意テキスト), last_name：*****(任意テキスト),first_name：*****(任意テキスト), email：*****(他instructorと同メールアドレス),profile_image：*****(任意ファイル)をリクエストボディとして実行することで、 
```
 {
    "message": "The given data was invalid.",
    "errors": {
        "email": [
            "The email has already been taken."
        ]
    }
}
```
が出力されることを確認

## 考慮して欲しいこと
「3. コントローラ改修②（メールアドレスのバリデーション）」において、
JIRAのタスク内容説明において、” 生徒更新APIで類似実装あり ” といただいておりましたが、
`app/Http/Requests/Student/StudentPatchRequest.php` にて、
メールアドレスのバリデーションルールとして使用している`app/Rules/UniqueEmailRule.php` が
Studentモデルに特化した内容となっておりましたので、
ファイル名を`StudentUniqueEmailRule.php`へ変更しておりましたので、ご了承くださいますようお願いいたします。
（`app/Rules/UniqueEmailRule.php` を一般化するよりもこちらの方が波及する影響が少ないと考えました。）

2024-01-09 14:10 UTC, Hikaru-Giannis requested changes

2024-01-09 14:10 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/InstructorController.php
次の記述は同じid同士を比較しているので、不要だと思われるのですがいかがでしょうか？

```php
            if (Auth::guard('instructor')->user()->id !== $instructor->id) {
                return response()->json([
                    'result' => 'false',
                    "message" => "Not authorized."
                ], 403);
            }
```

2024-01-09 14:10 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/InstructorController.php
次の記述をdisk指定で`public`にし、それに伴う修正をお願いします！

```php
                $imagePath = Storage::putFileAs('public/instructor', $file, $filename);
                $imagePath = Instructor::convertImagePath($imagePath);
```

2024-01-09 14:10 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/InstructorController.php
> +            $imagePath = $instructor->profile_image;    // 更新前の画像パスを使用
コメントを残すのであれば、次のように統一しておきましょうか！

```php
// 更新前の画像パスを使用
$imagePath = $instructor->profile_image;
```

2024-01-09 14:10 UTC, Hikaru-Giannis commented on app/Http/Requests/Instructor/InstructorPatchRequest.php
論理削除されている場合、この時点でエラーとするようにお願いします🙇‍♂️
```php
            'instructor_id' => ['required', 'integer', 'exists:instructors,id'],
```

2024-01-09 14:10 UTC, Hikaru-Giannis commented on app/Rules/InstructorUniqueEmailRule.php
> +    }
適切なバリデーションメッセージを返すようにお願いします。
`app/Rules/StudentUniqueEmailRule.php`を真似ると統一できるので、よろしくお願いします！

2024-01-09 14:11 UTC, Hikaru-Giannis commented
> （app/Rules/UniqueEmailRule.php を一般化するよりもこちらの方が波及する影響が少ないと考えました。）

私も同感ですので、良いと思います！

2024-01-09 17:11 UTC, Jino225242 commented on app/Http/Controllers/Api/Instructor/InstructorController.php
```
            if (Auth::guard('instructor')->user()->id !== $instructor->id) {
                return response()->json([
                    'result' => 'false',
                    "message" => "Not authorized."
                ], 403);
            }
```
の削除忘れ失礼いたしました！
削除いたします🙇‍♂️

2024-01-09 17:47 UTC, Jino225242 commented on app/Http/Controllers/Api/Instructor/InstructorController.php
disk指定については、子課題②として実施しようと考えておりましたが、ご指摘いただきましたので本プルリクエストにて進めさせていただきます。
`$imagePath = Storage::disk('public')->putFileAs('instructor', $file, $filename);`
にてよろしいでしょうか。

2024-01-09 17:47 UTC, Jino225242 commented on app/Http/Controllers/Api/Instructor/InstructorController.php
> +            $imagePath = $instructor->profile_image;    // 更新前の画像パスを使用
失礼いたしました🙇‍♂️修正いたします。

2024-01-09 17:47 UTC, Jino225242 commented on app/Rules/InstructorUniqueEmailRule.php
> +    }
デフォルト(`return 'The validation error message.';`)のままとなっており、失礼いたしました。

以下にてよろしいでしょうか。
`return 'The :attribute has already been taken.';`

2024-01-09 17:47 UTC, Jino225242 commented on app/Http/Requests/Instructor/InstructorPatchRequest.php
以下にてよろしいでしょうか。
`'instructor_id' => ['required', 'integer', 'exists:instructors,id,deleted_at,NULL'],`

2024-01-10 11:13 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/InstructorController.php
> 子課題②として実施しようと考えておりました

失礼しました🙇‍♂️

> $imagePath = Storage::disk('public')->putFileAs('instructor', $file, $filename);
にてよろしいでしょうか。

その認識で問題ないです！

2024-01-10 11:15 UTC, Hikaru-Giannis commented on app/Http/Requests/Instructor/InstructorPatchRequest.php
その認識で問題ないともいます！

2024-01-10 11:15 UTC, Hikaru-Giannis commented on app/Rules/InstructorUniqueEmailRule.php
> +    }
その認識で問題ないと思います！

2024-01-10 11:35 UTC, Hikaru-Giannis requested changes
`app/Model/Instructor.php`の`convertImagePath`は、システム上で参照しなくなったと思いますので、削除お願いします！

2024-01-10 13:28 UTC, Hikaru-Giannis approved these changes

2024-01-10 13:28 UTC, merged