JKA-624_(dera)_講師情報更新APIの改修
yukihiroLaravel/juko_laravel pull request #412
Opened 2024-01-10 13:50 UTC by Jino225242

## issue
 タスク　[(JKA-624)講師情報更新APIの改修](https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-624)

## 概要
topicブランチからdevelopブランチへのプルリクとなります。

1.ルート変更
　URLを /api/v1/instructor/{instructor_id} → /api/v1/instructor/update に変更
2. コントローラ改修①
　instructor_idはリクエストからではなく、認証者のidを参照
3. コントローラ改修②
　バリデーションのメールアドレスにおいて、前後同じのままであればTrue、そうでなければDBでのユニークチェック
4. コントローラ改修③
　プロフィール画像のリクエストがない場合は、以前の状態を保持

## 動作確認手順
/api/v1/instructor/update　において、

1. nick_name：*****(任意テキスト), last_name：*****(任意テキスト),first_name：*****(任意テキスト), email：*****(任意メールアドレス),profile_image：*****(任意ファイル)をリクエストボディとして実行することで、
```
{
    "result": true,
    "data": {
        "nick_name": "*****(任意テキスト)",
        "last_name": "*****(任意テキスト)",
        "first_name": "*****(任意テキスト)",
        "email": "*****(任意メールアドレス)",
        "profile_image": "instructor/*****(任意ファイル).jpg",
        "type": "manager" もしくは "instructor"
    }
}
```
が出力されることを確認

2.nick_name：*****(任意テキスト), last_name：*****(任意テキスト),first_name：*****(任意テキスト), email：*****(任意メールアドレス),profile_image：null(リクエスト無し)をリクエストボディとして実行することで、 
```
{
    "result": true,
    "data": {
        "nick_name": "*****(任意テキスト)",
        "last_name": "*****(任意テキスト)",
        "first_name": "*****(任意テキスト)",
        "email": "*****(任意メールアドレス)",
        "profile_image": "instructor/*****(任意ファイル).jpg",     ←以前の状態を保持
        "type": "manager" もしくは "instructor"
    }
}
```
が出力されることを確認

3.nick_name：*****(任意テキスト), last_name：*****(任意テキスト),first_name：*****(任意テキスト), email：*****(他instructorと同メールアドレス),profile_image：*****(任意ファイル)をリクエストボディとして実行することで、 
```
 {
    "message": "The given data was invalid.",
    "errors": {
        "email": [
            "The email has already been taken."
        ]
    }
}
```
が出力されることを確認

## 考慮して欲しいこと
「3. コントローラ改修②（メールアドレスのバリデーション）」において、
JIRAのタスク内容説明において、” 生徒更新APIで類似実装あり ” といただいておりましたが、
`app/Http/Requests/Student/StudentPatchRequest.php` にて、
メールアドレスのバリデーションルールとして使用している`app/Rules/UniqueEmailRule.php` が
Studentモデルに特化した内容となっておりましたので、
ファイル名を`StudentUniqueEmailRule.php`へ変更しておりましたので、ご了承くださいますようお願いいたします。
（`app/Rules/UniqueEmailRule.php` を一般化するよりもこちらの方が波及する影響が少ないと考えました。）

2024-01-11 08:48 UTC, kou-tech requested changes

2024-01-11 08:48 UTC, kou-tech commented on app/Http/Requests/Instructor/InstructorPatchRequest.php
ここで、typeの変更は想定していないので削除お願いしたいです🙇‍♀️
元々あった記述も削除して問題ないです！

2024-01-11 13:15 UTC, Jino225242 commented on app/Http/Requests/Instructor/InstructorPatchRequest.php
`'type' => ['required', 'string', 'max:30', new InstructorTypeRule()]`
となっていたため、
```
{
    "message": "The given data was invalid.",
    "errors": {
        "type": [
            "The type field is required."
        ]
    }
}
```
という出力となるため、
`'type' => Auth::user()->type,`
と追記させていただきましたが、
`'type' => ['required', 'string', 'max:30', new InstructorTypeRule()]`
の部分自体を削除して問題ないという認識にてよろしいでしょうか。

2024-01-11 13:39 UTC, Hikaru-Giannis commented on app/Http/Requests/Instructor/InstructorPatchRequest.php
その認識で問題ないです！

2024-01-12 00:06 UTC, Hikaru-Giannis approved these changes

2024-01-12 00:06 UTC, merged