#651  新権限マネージャー設立による配下のinstructorの作成した講座・チャプターに紐づくレッスンの並び順を変更できるAPI作成(ごめ)
yukihiroLaravel/juko_laravel pull request #417
Opened 2024-01-11 15:34 UTC by gomez8927

## タスク
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-651
## 概要
- 新権限マネージャー設立による配下のinstructorの作成した講座・チャプターに紐づくレッスンの並び順を変更できるAPI作成
## 動作確認手順
- POSTリクエスト
api/v1/manager/course/1/chapter/1/lesson/sort
- body
```
{
  "lessons": [
    {
      "lesson_id": 1,
      "order": 1
    }
  ]
}
```
- レスポンス
```
{
  "result": true
}
```
## 考慮して欲しいこと
- 特にありません
## 確認して欲しいこと
- 特にありません

2024-01-11 16:07 UTC, yukihiroLaravel requested changes
コメントしましたのでご確認願います！

2024-01-11 16:07 UTC, yukihiroLaravel commented on app/Http/Requests/Manager/LessonSortRequest.php
> +            'chapter_id' => ['required', 'integer'],
他のフォームリクエストにある
exist や deleted_at の制約も必要かと思いました！

2024-01-11 16:07 UTC, yukihiroLaravel commented on app/Http/Requests/Manager/LessonSortRequest.php
> +            'lessons.*.lesson_id' => ['required', 'integer'],
ここにも、exist や deleted_at の制約が必要？

2024-01-11 16:07 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/LessonController.php
> +                    ], 403);
@Hikaru-Giannis 
ここで下のようにExceptionを投げて、
rollbackを通すべきでしょうか？

2024-01-12 00:01 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/LessonController.php
> +                    ], 403);
@yukihiroLaravel 
個人的には、例外へ投げる必要がないと思います。この時点までにDBのレコード操作が行われないのと、基本的に、認可 → 実行という手順で実装すると思いますので。

2024-01-12 06:31 UTC, yukihiroLaravel requested changes

2024-01-12 06:31 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/LessonController.php
> +                    ], 403);
@Hikaru-Giannis 
なるほどです。

ただ、起こりうるのか微妙ですが
レッスン１は認可処理上問題なく並び順をupdateした後に
レッスン２は認可処理上問題があった場合、
foreachを使っているので、レッスン１については並び順を変更する
レコード操作が実施済みとなってしまうと思うので
他の部分と同様にExceptionを投げた方がいいかと思ったのですが
いかがでしょうか？

2024-01-12 13:14 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/LessonController.php
> +                    ], 403);
@yukihiroLaravel 
 出先でコード見てたので、全体まで把握していなかったです🙇‍♂️
おっしゃる通りですね。

個人的なレビューだと、同一ループで認可と更新は責務として、分離したいので、次のようにしたいですが、判断はお任せします！

````php
            $courseId = $request->input('course_id');
            $chapterId = $request->input('chapter_id');
            $inputLessons = $request->input('lessons');

            // レッスンを一括取得
            $lessons = Lesson::with('chapter.course')->whereIn('id', array_column($inputLessons, 'lesson_id'))->get();

            // 認可
            $lessons->each(function ($lesson) use ($user, $courseId,$chapterId) {
                if ($user->id !== $lesson->chapter->course->instructor_id) {
                    return response()->json([
                        'result' => false,
                        'message' => 'Invalid instructor_id.',
                    ], 403);
                }

                if ((int) $courseId !== $lesson->chapter->course->id) {
                    return response()->json([
                        'result' => false,
                        'message' => 'Invalid course.',
                    ], 403);
                }

                if ((int) $chapterId !== $lesson->chapter->id) {
                    return response()->json([
                        'result' => false,
                        'message' => 'Invalid chapter.',
                    ], 403);
                }
            });

            // レッスンのorderカラムを更新
            $lessons->each(function ($lesson) use ($inputLessons) {
                $inputLesson = new Collection($inputLessons);
                $lesson->update([
                    'order' => $inputLesson['order']
                ]);
            });
````

2024-01-14 16:58 UTC, gomez8927 commented on app/Http/Requests/Manager/LessonSortRequest.php
> +            'chapter_id' => ['required', 'integer'],
訂正しました

2024-01-14 16:58 UTC, gomez8927 commented on app/Http/Requests/Manager/LessonSortRequest.php
> +            'lessons.*.lesson_id' => ['required', 'integer'],
訂正しました

2024-01-14 16:59 UTC, gomez8927 commented on app/Http/Controllers/Api/Manager/LessonController.php
> +                    ], 403);
訂正しました

2024-01-15 12:10 UTC, Hikaru-Giannis requested changes

2024-01-15 12:10 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/LessonController.php
> +use Illuminate\Http\Request;
こちらは参照していないので、削除お願いします！

2024-01-15 12:10 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        } catch (\Exception $e) {
Exceptionは、useでインポートしているのでエスケープ処理をする必要はないです。

2024-01-15 14:13 UTC, gomez8927 commented on app/Http/Controllers/Api/Manager/LessonController.php
> +use Illuminate\Http\Request;
訂正しました

2024-01-15 14:13 UTC, gomez8927 commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        } catch (\Exception $e) {
訂正しました

2024-01-15 21:12 UTC, Hikaru-Giannis approved these changes

2024-01-16 02:47 UTC, yukihiroLaravel approved these changes
ありがとうございます！
マージしました！

2024-01-16 02:47 UTC, merged