Feature/kumiko/jka 660/form request
yukihiroLaravel/juko_laravel pull request #419
Opened 2024-01-14 14:53 UTC by kuminmi

## タスク
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-657
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-660
## 概要
- 新権限マネージャー設立による配下のinstructorの作成した講座・チャプターに紐づくレッスンを更新するAPI作成
における、フォームリクエストの作成
## 動作確認手順
- postmanにて
- PUTリクエスト
/api/v1/manager/course/1/chapter/1/lesson/1
```
{
  "title": "レッスンタイトル",
  "url": "https://www.youtube.com/watch?v=xxxxxxxxxxx",
  "remarks": "備考"
}
```
- レスポンス
```
{
  "result": true
}
```
が返ってくることを確認。
- course_idが一致しない場合のエラー確認。
- chapter_idが一致しない場合のエラー確認。
## 考慮して欲しいこと
- 特にありません
## 確認して欲しいこと
- 特にありません

2024-01-15 02:44 UTC, yukihiroLaravel requested changes
少しコメントしました！

2024-01-15 02:44 UTC, yukihiroLaravel commented on app/Http/Requests/Manager/LessonUpdateRequest.php
> +            'course_id' => ['required', 'integer'],
いつもの、exist, deleted_at null のバリデーション を入れましょう！

2024-01-15 04:09 UTC, kuminmi commented on app/Http/Requests/Manager/LessonUpdateRequest.php
> +            'course_id' => ['required', 'integer'],
そうでした。忘れてました。修正します！

2024-01-15 12:16 UTC, Hikaru-Giannis commented on app/Http/Requests/Manager/LessonUpdateRequest.php
> +            'title' => ['required','string'],
`title`の最大文字数のバリデーションをお願いします。
dbのカラムのサイズが最大と解釈して問題ないです！

2024-01-15 14:29 UTC, kuminmi commented on app/Http/Requests/Manager/LessonUpdateRequest.php
> +            'title' => ['required','string'],
修正しました！

2024-01-15 21:13 UTC, Hikaru-Giannis approved these changes

2024-01-16 02:46 UTC, yukihiroLaravel approved these changes
ありがとうございます！
マージしました！

2024-01-16 02:46 UTC, merged