jka-630 新権限マネージャー設立による配下のinstructorの作成したチャプター並び順変更API作成(ふるさわ)
yukihiroLaravel/juko_laravel pull request #432
Opened 2024-01-21 14:48 UTC by furusawa501

## 概要
-  新権限マネージャー設立による配下のinstructorの作成したチャプター並び順変更API作成(ふるさわ)

## 動作確認手順
- POSTリクエスト
/api/v1/manager/course/1/chapter/sort
- body
```
{
  "chapters": [
    {
      "chapter_id": 1,
      "order": 2
    },
    {
      "chapter_id": 2,
      "order": 1
    }
  ]
}
```
- レスポンス
```
{
    "result": true
}
```
## 考慮して欲しいこと
- 配下ではないインストラクターのチャプターをソートした場合のエラー確認は
chaptersテーブルにテスト用のレコードを追加する必要があります。

## 確認して欲しいこと
- api.phpのルーティング追加がローカルリポジトリにマージされていなかった（？）ため
今回のプルリクエストに変更が含まれていますが、原因がわかりません。

2024-01-24 12:57 UTC, yukihiroLaravel requested changes
１点コメントしました！

2024-01-24 12:57 UTC, yukihiroLaravel commented on app/Http/Requests/Manager/ChapterSortRequest.php
> +            'chapters.*.chapter_id' => ['required', 'integer'],
こちらも
'exists:chapters,id,deleted_at,NULL'
この記述があるといいと思いました！

2024-01-24 21:08 UTC, Hikaru-Giannis approved these changes

2024-01-27 08:48 UTC, yukihiroLaravel approved these changes

2024-01-27 08:48 UTC, merged