新権限マネージャー設立による配下のinstructorに紐づくお知らせ情報一覧を表示するAPI作成
yukihiroLaravel/juko_laravel pull request #444
Opened 2024-01-31 08:23 UTC by junro1307

## issue
タスク
①子課題　空の配列を返すルーターとコントローラの作成

## 概要
- 空の配列を返すルーターとコントローラの作成

## 確認してほしい所
間違っていたり、コード書き方にご指摘ありましたら、お願いいたします。
## 考慮してほしい所
なし

2024-02-01 07:40 UTC, yukihiroLaravel requested changes
コメントしましたのでご確認ください！

2024-02-01 07:40 UTC, yukihiroLaravel commented on routes/api.php
> +                 // マネージャーお知らせ一覧
他のところにならって
`マネージャー-お知らせ一覧`
とハイフンをつけましょう！

2024-02-01 07:40 UTC, yukihiroLaravel commented on routes/api.php
> +                Route::prefix('Notification')->group(function () {
Notification
URLは基本小文字なので、頭文字は小文字ですね！
notification

2024-02-01 10:23 UTC, Hikaru-Giannis commented on routes/api.php
> +                    Route::get('/', 'Api\Manager\NotificationController@store');
意図したURLとレスポンスが返ってくる動作確認はされていましたでしょうか？

2024-02-05 20:09 UTC, yukihiroLaravel requested changes
コメントしましたのでご確認ください！

2024-02-05 20:09 UTC, yukihiroLaravel commented on routes/api.php
> +                    Route::post('/', 'Api\Manager\AttendanceController@');
@の後が消えてしまっているので戻しましょう💦

2024-02-06 05:30 UTC, merged