ロジック作成とレスポンス整形のリソースファイル作成 or 変更
yukihiroLaravel/juko_laravel pull request #452
Opened 2024-02-11 15:27 UTC by junro1307

## 新権限マネージャー設立による配下のinstructorに紐づくお知らせ情報一覧を表示するAPI作成

子課題②ロジック作成
子課題④レスポンス整形のリソースファイル作成 or 変更

## 動作確認

Postmanで（http://localhost:8080/api/v1/manager/notification/index)でsend

実行結果
{
    "data": {
        "notifications": [
            {
                "id": 1,
                "course_id": 1,
                "course_title": "PHP入門講座",
                "title": "レッスン「変数とは？」閲覧について",
                "type": "always",
                "start_date": "2023-08-01 00:00:00"
            },
            {
                "id": 3,
                "course_id": 1,
                "course_title": "PHP入門講座",
                "title": "レッスン「変数とは？」閲覧について",
                "type": "once",
                "start_date": "2023-08-01 00:00:00"
            }
        ],
        "pagination": {
            "page": 1,
            "total": 2
        }
    }
}

## 確認してほしい所

ほぼコピペで記述したコードですが、注意点やご指摘があればよろしくお願いします。

2024-02-12 00:55 UTC, yukihiroLaravel requested changes
コメントしましたので
ご確認お願いします！

2024-02-12 00:55 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +use App\Http\Requests\Instructor\NotificationIndexRequest;
こちらは次のタスクで変える予定だと思いますので
一旦このままでOKです！

2024-02-12 00:55 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +                                        ->where('instructor_id', Auth::guard('instructor')->user()->id)
動画で解説しているように、
ここでマネージャー本人だけでなく配下のinstructorのinstructor_id全部に合致する
Notificationを抽出する対応が必要です！

たとえば、こんな感じです！

```
->whereIn('instructor_id', $instructorIds)
```

このように描いた上で、
最初Jiraで解説した動画を見ていただき、
マネージャー本人のお知らせだけでなく、配下のinstructorのお知らせ一覧が取得できるか
きちんと動作確認を行いましょう！

動作確認が1番重要です！

2024-02-16 21:41 UTC, Hikaru-Giannis approved these changes

2024-02-17 00:05 UTC, yukihiroLaravel approved these changes

2024-02-17 00:05 UTC, merged