フォームリクエスト作成、変更（川端）
yukihiroLaravel/juko_laravel pull request #470
Opened 2024-02-22 08:27 UTC by junro1307

## 新権限マネージャー設立による配下のinstructorに紐づくお知らせ情報一覧を表示するAPI作成
## 子課題③
フォームリクエスト作成、変更
## 動作確認
Postman（http://localhost:8080/api/v1/manager/notification/index?page=A&per_page=A)
ParamsでKey入力でエラーが出る値を入力sendしてエラーメッセージを確認
{
    "message": "The given data was invalid.",
    "errors": {
        "per_page": [
            "The per page must be an integer."
        ],
        "page": [
            "The page must be an integer."
        ]
    }
}
## 確認してほしい所
特にないです。
## 考慮してほしい所
特にないです。

2024-02-22 12:56 UTC, yukihiroLaravel approved these changes
問題ないかと思います！

2024-02-22 14:22 UTC, Hikaru-Giannis requested changes

2024-02-22 14:22 UTC, Hikaru-Giannis commented on app/Http/Requests/Manager/NotificationIndexRequest.php
これだけだと、リクエストファイルを作成しただけでコントローラーでは参照できていないと思われたのですがいかがでしょうか？

2024-02-22 14:39 UTC, yukihiroLaravel requested changes
修正願います。

2024-02-22 14:39 UTC, yukihiroLaravel commented on app/Http/Requests/Manager/NotificationIndexRequest.php
> +namespace App\Http\Requests;
namespace App\Http\Requests\Manager;

2024-02-22 14:39 UTC, yukihiroLaravel commented on app/Http/Requests/Manager/NotificationIndexRequest.php
すみません、僕の方でも確認漏れてました🙇‍♂️

2024-02-23 02:17 UTC, yukihiroLaravel approved these changes
問題ないかと思います！

2024-02-23 04:16 UTC, Hikaru-Giannis approved these changes

2024-02-23 15:21 UTC, merged