受講生一覧取得API（講師側に受講生名・日時検索を追加する）（はいしま）
yukihiroLaravel/juko_laravel pull request #471
Opened 2024-02-22 10:36 UTC by hatschi2023

## Issue
子課題　JKA-721

受講生一覧取得API（講師側・マネージャー側の２つ）に受講生名・日時検索を追加する
https://gut-familie.atlassian.net/browse/JKA-716

## 概要
受講生一覧取得API（講師側に受講生名・日時検索を追加する）

## 動作確認手順
instructor(id=1)でログインし、講座の受講生一覧を取得
GET:
http://localhost:8080/api/v1/instructor/course/1/student/index

- acount ：（※いづれか１件づつ確認）
生徒ニックネーム1 
生徒テスト
test_student_1@example.com

- start_date ：
2024-02-01
- end_date：
2024-02-15

## 考慮して欲しいこと（質問）

- 受講生名、日付検索のために新たに検索条件　$acount、$start_date、 $end_date を作成しました。
対応するフォームリクエストの値の取得は、Viewではname属性で取得していたと思いますが、API開発ではどのように取得すればよいでしょうか。

2024-02-22 10:39 UTC, hatschi2023 commented on app/Http/Requests/Instructor/StudentIndexRequest.php
> +            'end_date' => ['date_format:Y-m-d'],
![image](https://github.com/yukihiroLaravel/juko_laravel/assets/145645279/555ac672-4bc0-43a0-a6c5-1c22c63115b9)

2024-02-22 12:20 UTC, hatschi2023 commented on database/seeds/StudentSeeder.php
> +                'profile_image' => '/student/image3.jpg',
![image](https://github.com/yukihiroLaravel/juko_laravel/assets/145645279/364e7045-5457-40f9-a6f5-a9b9ad51ef2a)
動作確認で200 OK で成功するのですが、検索の絞り込みが確認できません。
そういえば最初に、GETでPostmanの動作確認するときはBodyは必要ないと教わった気がします。（間違ってましたらごめんなさい）
Bodyのform-dataで絞り込み条件を入力して送信しましたが、この方法で動作確認は可能でしょうか。

2024-02-23 04:14 UTC, Hikaru-Giannis commented
> Viewではname属性で取得していたと思いますが、API開発ではどのように取得すればよいでしょうか。

長らくViewでの開発をしていなかったのですが、name属性に該当するのがPostmanによるKeyに該当するような認識です。`$_GET`とかはグローバル変数なので、そのまま扱うのはとても危険なので、フレームワークでその周辺をある程度安全にしてくれている感じですね。

APIだから違いがあるというよりは、Content-typeによる違いかなと感じました。
https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Content-Type

2024-02-23 04:14 UTC, Hikaru-Giannis requested changes

2024-02-23 04:14 UTC, Hikaru-Giannis commented on database/seeds/StudentSeeder.php
> +                'profile_image' => '/student/image3.jpg',
これはGetリクエストなので、Paramsで確認が正しい方法です！
<img width="910" alt="スクリーンショット 2024-02-23 13 03 21" src="https://github.com/yukihiroLaravel/juko_laravel/assets/64859506/b9be7bd6-49fc-471a-b961-6d5ec9bd34b6">

2024-02-23 04:14 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/StudentController.php
はいしまさんの前の方の実装なのですが、attendancesテーブルも必要なカラムだけ取得するようにお願いします！

2024-02-23 04:14 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +        $end_date = $request->input('end_date');
キャメルケースでお願いします！

2024-02-23 04:14 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +            })
`start_date`と`end_date`は、ダブルクォーテーションで囲う必要性ありましたでしょうか？

2024-02-25 12:58 UTC, hatschi2023 commented on database/seeds/StudentSeeder.php
> +                'profile_image' => '/student/image3.jpg',
Paramsで確認できました！
![image](https://github.com/yukihiroLaravel/juko_laravel/assets/145645279/48e955d0-8bc2-44b6-991d-ec3f784723d5)

2024-02-25 13:09 UTC, hatschi2023 commented on app/Http/Controllers/Api/Instructor/StudentController.php
>              ->when($sortBy === 'attendanced_at', function ($query) use ($order) {
質問です。
$sortBy === 'attendanced_at' この部分の 'attendanced_at' がまだいまいち理解できていません。
何度かご説明いただいているコンテンツタイプのキーワードにあたりますか？
ここはユーザー画面で登録日をソート指定した場合の処理だと思いますが、キーワードの'attendanced_at'と登録日が紐づくのはどうしてなのでしょうか。
登録日のカラムにキーワードが指定されているからなのだと推測しますが、どこに記載されているのでしょうか。

また、select句でattendances.created_at as attendanced_at としましたが、キーワードと被っていても問題ないでしょうか？

2024-02-25 13:18 UTC, hatschi2023 commented on app/Http/Controllers/Api/Instructor/StudentController.php
修正しました！

2024-02-26 05:36 UTC, Hikaru-Giannis requested changes

2024-02-26 05:36 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/StudentController.php
>              ->when($sortBy === 'attendanced_at', function ($query) use ($order) {
いえ、これは今の実装では確かに必要ないですね...。

以前はEloquentで実装していたり、取得するカラム名を選定していたりしてなかった名残ですね。
そのため、whenは使用せず修正をお願いできますか？

2024-02-26 05:36 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +                $inputText = str_replace(['　',' '], '', $inputText);
ここ正規表現で修正はできそうでしょうか...？

2024-02-26 08:37 UTC, hatschi2023 commented on app/Http/Controllers/Api/Instructor/StudentController.php
>              ->when($sortBy === 'attendanced_at', function ($query) use ($order) {
` ->when($sortBy === 'attendanced_at', function ($query) use ($order) {
                $query->orderBy('attendances.created_at', $order);
            }, function ($query) use ($sortBy, $order) {
                $query->orderBy('students.' . $sortBy, $order);
            })`
            
この部分はまるっと不要ということですか。
それとも、=== 'attendanced_at'の条件での記載部分は不要ということでしょうか。

ここでどういう処理が必要なのか理解できていないのですが、
ソートはフロント側で処理されていて、データの抽出では不要という理解でよいのでしょうか。

2024-02-26 12:22 UTC, hatschi2023 commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +                $inputText = str_replace(['　',' '], '', $inputText);
修正してみました！

2024-02-26 13:00 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/StudentController.php
>              ->when($sortBy === 'attendanced_at', function ($query) use ($order) {
`when`は第一引数の真偽値がtrueなら、第二引数の関数を実行、第一引数の真偽値がfalseなら第三引数の関数を実行します。ということは、このコードからorderByの処理を特定のソートキーの場合で分岐して実行するように現状はなっています。理由としては、`attendances`テーブルの項目か、`students`テーブルの項目でソートするかの違いでした。
ただ、現状はクエリビルダでクエリを実行しているため、whenは不要になる認識でした！

> 「whenは使用せず修正」ということは、ここのコードは全て不要でしょうか。

ソート機能は必須ですので、全てではないです。結果として、sortByに該当する項目とorderで意図したソートでデータを取得できているかを動作確認していただきたいです！

- sortByに該当する項目は次のファイルの実装を確認してみてください！
  - app/Rules/IndexSortByRule.php
- orderは、ascかdescかで昇順、降順を指定することができるようになっています。
- `last_login_at`などは、Seederだと同じ日時で確認が難しければadminerなどでデータを編集して確認してみてください！

2024-02-27 09:20 UTC, hatschi2023 commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +        $results = $results->paginate($perPage, ['*'], 'page', $page);
ご指摘いただいていたソート機能の書換えについて、ひとまずif 文に書き換えてみました。
クエリビルダだとwhenを使わずに書いた方がよいのはなぜでしょうか。
よく分からない原因は、おそらく以下の点で私の理解不足があると思うのですが。。

‐　eloquentとクエリビルダ―の違いをよく把握できていない（→調べ中です）
‐　フロント側でのソートの動きが分かっていない
　→Figmaで確認したところ、各項目の▽を選択したときにソート（indexメソッドが実行）されるのでしょうか？
　
参考サイトなどヒントいただければ助かります！

2024-02-27 12:18 UTC, Hikaru-Giannis requested changes

2024-02-27 12:18 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +        $results = $results->paginate($perPage, ['*'], 'page', $page);
> クエリビルダだとwhenを使わずに書いた方がよいのはなぜでしょうか。

使わずにというよりは、使う必要がない気がします。次の記述で意図した動作になりませんか？
```php
            ->orderBy($sortBy, $order)
            ->paginate($perPage, ['*'], 'page', $page);
```

> eloquentとクエリビルダ―の違いをよく把握できていない

オブジェクト指向などが理解できていないと厳しいかもしれませんが、Eloquentを使用すると、データベースのレコードをオブジェクトとして扱うことができるのですが、複雑なDBのSQLを構築するには不向きだったりするので、もう少しDBのSQLを直感的に実行することができるのが、クエリビルダです。今回は、検索機能、ソート機能、ページネート機能があるため、Eloquentではなくクエリビルダが適切という感じですね。

> 各項目の▽を選択したときにソート（indexメソッドが実行）されるのでしょうか？

その認識であっています！

2024-02-28 03:01 UTC, hatschi2023 commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +
Postman動作確認で、カラムを指定した場合、ソートの並び替えができず原因が分かりません。

`$sortBy = $request->input('sort_by', 'nick_name');`　
でカラム名を指定している場合も、デフォルトのnick_nameが返ってきています。

`dd($request->all())`すると、正しく取得できているのですが、
キーワードがsort_by がそsortBy ?になっています。こちらはこれで問題ないでしょうか。

確認ポイントを、何かヒントいただけると助かります！
![image](https://github.com/yukihiroLaravel/juko_laravel/assets/145645279/b410e307-ab7e-4d0d-b0e0-817eca4f0c27)

2024-02-28 07:55 UTC, hatschi2023 commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +
↑こちら解決できました。
Postmanのキーの記載を間違えていたのが原因でした。
その後ソートも問題なく並び替えできているのを動作確認しました！

2024-02-28 11:13 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/StudentController.php
>          $order = $request->input('order', 'asc');
デバッグ処理は削除をお願いします！

2024-02-28 11:15 UTC, Hikaru-Giannis approved these changes

2024-02-28 12:51 UTC, Hikaru-Giannis approved these changes

2024-02-28 12:51 UTC, merged