自分と配下の講師の講師情報の取得(編集)フォームリクエスト作成(かずふみ)
yukihiroLaravel/juko_laravel pull request #479
Opened 2024-02-29 03:26 UTC by kazufumikatsuyama

##  概要
- 新権限マネージャー設立による配下のinstructorの講師情報取得(編集)API作成  
   子課題  
   フォームリクエストの作成
## 動作確認手順
- Postmanで[http://localhost:8080/api/v1/manager/instructor/{instructor_id}](http://localhost:8080/api/v1/manager/instructor/%7Binstructor_id%7D)  
   instructor_idの数字を変えて、レスポンスが返ってくるか確認
- 自分と配下の講師の情報は取れるけど、違うマネージャーの情報を  
   取得出来ないことを確認
## 考慮して欲しいこと
- 特にありません
## 確認して欲しいこと
- 特にありません

2024-02-29 07:58 UTC, yukihiroLaravel requested changes

2024-02-29 07:58 UTC, yukihiroLaravel commented on app/Http/Requests/Manager/InstructorEditRequest.php
> +            'instructor_id' => ['required', 'integer'],
https://github.com/yukihiroLaravel/juko_laravel/blob/develop/app/Http/Requests/Instructor/LessonUpdateRequest.php
こちらのファイルのように
`'instructor_id' => ['required', 'integer', 'exists:instructors,id,deleted_at,NULL'],`
このようにして、
存在しないinstructorがURLで指定されたときに弾くようにしましょう！

実装できたら存在しないIDでテストもお願いします！

2024-02-29 13:46 UTC, kou-tech requested changes

2024-02-29 13:46 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/InstructorController.php
> +use Illuminate\Http\Request;
こちらのインポートは不要ではないですか？

2024-02-29 13:46 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/InstructorController.php
> +        $requestInstructor = $request->instructor_id;
変数名が誤解を生みそうと感じました。
idというプロパティに対して、他の変数名は後尾にIdとついているのでこちらもつけると良いと思ったのですがいかがでしょうか？

2024-03-01 13:20 UTC, Hikaru-Giannis approved these changes

2024-03-01 14:30 UTC, yukihiroLaravel approved these changes
マージしました！
おつかれさまでした！

2024-03-01 14:30 UTC, merged