Instructor/Managerでチャプター更新処理が分散してしまう問題の解消（林）
yukihiroLaravel/juko_laravel pull request #490
Opened 2024-03-07 10:41 UTC by tatsuhirohayashi

## issue
Instructor/Managerでチャプター更新処理が分散してしまう問題の解消
https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-758

## 概要
Instructor/Managerでチャプター更新処理が分散してしまう問題の解消

## 動作確認手順
ポストマンで[http://localhost:8080/api/v1/manager/course/1/chapter/statusと打ち、
return true と返ってくることを確認

instructor側ではなくmanager側で重複を減らし、一貫性を高め、保守性を向上させたコードに変更しました。

## 考慮して欲しいこと
なし

2024-03-07 12:40 UTC, Hikaru-Giannis requested changes

2024-03-07 12:40 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
>          }
そもそもこの処理において、マネージャーかその配下のインストラクターの講座でない場合の認可処理が抜けていましたね。ただ、`$managedCourseIds`は、講座idのリストではなくないですか？
もう一度コードを確認してみてください！

2024-03-11 12:58 UTC, Hikaru-Giannis requested changes

2024-03-11 12:58 UTC, kou-tech commented on app/Model/Chapter.php
共通処理に切り出したことはいいですね！

しかし、関数名からこちらはチャプターを一括更新する処理を意図して共通の処理として切り出したと思います。
ただ、**チャプターを一括更新する**以外のことをしていませんか？

この関数を呼び出す側は、**チャプターを一括更新する**ことを目的としてこちらを使いたいのにその責務以外のことをされたら、使いづらい関数となってしまいます。その辺りを意識して、再度修正していただきたいです！

よろしくお願いします！

2024-03-11 12:58 UTC, kou-tech commented on app/Model/Chapter.php
関数名はキャメルケースにして、一貫性を持たせましょう！
また、一括更新であることを表現するようにしてみてください。

2024-03-11 13:03 UTC, tatsuhirohayashi commented on app/Model/Chapter.php
チャプターを一括更新する以外のことをしているとは何でしょうか？
また、
その責務以外のことをされたら、使いづらい関数になるとはどういうことでしょうか？
また、
キャメルケースとはなんでしょうか？
また、
一括更新であることを表現とはどういうことでしょうか？

よろしくお願いいたします！

2024-03-11 13:23 UTC, Hikaru-Giannis commented on app/Model/Chapter.php
@tatsuhirohayashi 
> チャプターを一括更新する以外のことをしているとは何でしょうか？

では、ご自身の書かれた`chapterUpdate`を順序立てて、説明いただけますか？その中で更新以外のことを行なっていないかを確認してみてください！

>  一括更新であることを表現とはどういうことでしょうか？

`chapterUpdate`と聞いて、他の人はチャプターを一括更新することが伝わるかを意識してみてください！

2024-03-11 13:56 UTC, tatsuhirohayashi commented on app/Model/Chapter.php
では、ご自身の書かれたchapterUpdateを順序立てて、説明いただけますか？その中で更新以外のことを行なっていないかを確認してみてください！

コースモデルからリクエストされたコースidがあるかどうか確認する。
認証された講師のIDとコースに紐づくインストラクターidと一致するかどうかチェックし、もし一致しないなら、権限がないことを示すエラーを含むレスポンスを返します。
最後に、チャプターモデルのレコードの更新で、whereで指定されたコースidに一致する条件を指定し、レコードを取得してきています。

chapterUpdateと聞いて、他の人はチャプターを一括更新することが伝わるかを意識してみてください！

chapterUpdateAllに関数名を変更しました。

2024-03-12 15:52 UTC, kou-tech requested changes

2024-03-12 15:52 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +        Chapter::chapterUpdateAll($request);
認可の部分はコードを共通化していないので、削除するのは問題が起きると思いませんか？

2024-03-12 15:52 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        Chapter::chapterUpdateAll($request);
認可の部分はコードを共通化していないので、削除するのは問題が起きると思いませんか？

2024-03-12 15:52 UTC, kou-tech commented on app/Model/Chapter.php
> +use Illuminate\Support\Facades\Auth;
参照しないので、あれば削除しましょう！

2024-03-12 15:52 UTC, kou-tech commented on app/Model/Chapter.php
> +    }
責務がわかりやすくなってきましたね！
ただこの関数の呼び出す側は、`$request`を引数に渡すと思いますが、その場合に`course_id`や`status`が含まれていないとこの関数はどのような挙動になると思いますか？
もう少し改善の余地があると思いますので、考えてみましょう！

2024-03-13 10:06 UTC, tatsuhirohayashi commented on app/Model/Chapter.php
> +use Illuminate\Support\Facades\Auth;
修正しました。

2024-03-13 10:13 UTC, tatsuhirohayashi commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +        Chapter::chapterUpdateAll($request);
認可の部分がないので、どんな講師もチャプター一括更新ができてしまうということでしょうか？

2024-03-13 10:13 UTC, tatsuhirohayashi commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        Chapter::chapterUpdateAll($request);
認可の部分がないので、どんな講師もチャプター一括更新ができてしまうということでしょうか？

2024-03-13 10:17 UTC, tatsuhirohayashi commented on app/Model/Chapter.php
> +    }
その場合にcourse_idやstatusが含まれていないとこの関数はどのような挙動になると思いますか？
とはどういった意味でしょうか？
関数には、course_idやstatusが含まれていると思いますが、

2024-03-13 10:29 UTC, tatsuhirohayashi commented on app/Model/Chapter.php
> +    }
データが含まれていないとcouse_idとstatusがnullという扱いになって、course_idがnullであるやつすべてを選択するという風になり、statusはすべてnullと更新されるということでしょうか？

2024-03-14 13:02 UTC, kou-tech commented on app/Model/Chapter.php
> +    }
`$request`という変数があると、を呼び出し側(=コントローラー)は何を引数に渡すべきなのかがわかりづらく、使いづらい関数になるとお話ししたので、このメソット内で`$request`は、使わなくなると思います！

2024-03-15 11:45 UTC, tatsuhirohayashi commented on app/Model/Chapter.php
> +    }
わかりました。

2024-03-16 11:24 UTC, Hikaru-Giannis requested changes

2024-03-16 11:24 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
次の認可処理が消えていると思うのですがなぜでしょうか？

```php
        // 講師が管理している講座でない場合、権限エラーを返す
        if (!in_array($courseId, $managedCourseIds)) {
            return response()->json([
                'result' => false,
                "message" => "Not authorized."
            ], 403);
        }
```

2024-03-16 11:24 UTC, Hikaru-Giannis commented on app/Model/Chapter.php
> +    }
変数名はキャメルケースにしましょう！

2024-03-16 11:45 UTC, tatsuhirohayashi commented on app/Model/Chapter.php
> +    }
修正しました。

2024-03-16 11:45 UTC, tatsuhirohayashi commented on app/Http/Controllers/Api/Manager/ChapterController.php
いらないと思って消しました。
もとにもどしました。

2024-03-18 10:07 UTC, Hikaru-Giannis approved these changes

2024-03-18 10:08 UTC, merged