ロジックの作成-紐づくレッスン名更新API作成(かずふみ)
yukihiroLaravel/juko_laravel pull request #491
Opened 2024-03-11 17:53 UTC by kazufumikatsuyama

##  概要
- 新権限マネージャー設立による配下のinstructorが作成したレッスン"名"更新API作成
子課題
ロジックの作成
## 動作確認手順
- Postmanでinstructor1でログインした後で
PATCHの
/api/v1/manager/course/{course_id}/chapter/{chapter_id}/lesson/{lesson_id}/title
course_id
chapter_id
lesson_idをそれぞれ入力して
指定のlesson titleが変更されているか確認
- もう一人のmanager  instructor4でログイン
更新できない事を確認
- instructor2でログイン
更新できない事を確認
## 考慮して欲しいこと
- 特にありません
## 確認して欲しいこと
- 特にありません

2024-03-12 12:30 UTC, yukihiroLaravel requested changes
いくつかコメントしましたので、ご確認ください！

2024-03-12 12:30 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        }
$instructorIdsの中身は必ず配列なので
絶対にこのifの中を通ることはないので、
ここの記述は不要かと思います！

2024-03-12 12:30 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        $user = Auth::guard('instructor')->user();
下記コメントに伴って、こちらの１行も不要かと思います！

> $instructorIdsの中身は必ず配列なので
> 絶対にこのifの中を通ることはないので、
> ここの記述は不要かと思います！

2024-03-12 15:44 UTC, kazufumikatsuyama commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        $user = Auth::guard('instructor')->user();
承知しました。

確認します。

2024-03-12 16:06 UTC, kazufumikatsuyama commented
コードを修正して
pushいたしました。

ご確認の程よろしくお願いいたします。

2024-03-13 11:14 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        }
リクエストの講座idから講座情報を取得するのではなく、レッスンから講座情報まで取得できているので、そちらと比較すべきかなと感じました！
この実装はレッスン名を更新するAPIですので、更新するレッスンの講座の講師と比較するのが妥当かなと！

2024-03-14 12:59 UTC, Hikaru-Giannis approved these changes

2024-03-14 13:11 UTC, yukihiroLaravel approved these changes
マージしました！
お疲れ様でした！

2024-03-14 13:11 UTC, merged