新権限マネージャー設立による配下のinstructorの講師情報更新API作成(はいしま)
yukihiroLaravel/juko_laravel pull request #494
Opened 2024-03-17 11:21 UTC by hatschi2023

## Issue
https://gut-familie.atlassian.net/browse/JKA-720

## 概要
新権限マネージャー設立による配下のinstructorの講師情報更新API作成

## 動作確認手順
Postmanでレスポンスを確認。
{{APP_URL}}/api/v1/manager/instructor/2

```
{
    "nick_name": "ニックネーム",
    "last_name": "名字",
    "first_name": "名前",
    "email": "test2@example.com",
    "profile_image": "instructor/default.png",
    "type": "instructor"
}
```
## 考慮して欲しいこと
タスクを分割せずに作業しましたが、こちらで問題ないでしょうか。

2024-03-17 11:46 UTC, hatschi2023 commented on app/Http/Controllers/Api/Manager/InstructorController.php
> +                'profile_image' => $imagePath,
Postmanでイメージの確認するにはどうすればよいでしょうか？
Strage/app/public/instrutor/に、サンプルdefault.pngを追加して動作確認しましたがエラーとなりました。
![image](https://github.com/yukihiroLaravel/juko_laravel/assets/145645279/8eb81f2e-24cc-457b-8c35-ee68cd42cecb)

2024-03-17 11:53 UTC, hatschi2023 commented on app/Http/Controllers/Api/Manager/InstructorController.php
> +            ]);
マネージャー権限がないと、タイプ更新はできないのだと思いますが、一番最初にインストラクターのタイプにマネージャーを登録する場合はどこでされているのでしょうか？または今回の更新処理でその対応ができるのでしょうか？

2024-03-17 12:03 UTC, hatschi2023 commented on routes/api.php
> +                });
先日post/put/patchでの更新の違いを説明していたばかりで恐縮ですが..
今回の更新はどうしてpostを使うのでしょうか。

2024-03-18 10:45 UTC, Hikaru-Giannis requested changes

2024-03-18 10:45 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/InstructorController.php
> +                'profile_image' => $imagePath,
profile_imageは、文字列ではなく画像ファイルで送る必要があります。
また、次の画像のようにform-dataで送る必要がありました！
<img width="650" alt="スクリーンショット 2024-03-18 19 41 24" src="https://github.com/yukihiroLaravel/juko_laravel/assets/64859506/86390749-81dc-48b9-b853-c8464251cd83">

2024-03-18 10:45 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/InstructorController.php
> +            ]);
現在マネージャーの新規登録機能はないですね。
よって、講師しか登録できない状況でした！

2024-03-18 10:45 UTC, Hikaru-Giannis commented on routes/api.php
> +                });
> patchではだめなのでしょうか？

Postmanの送信の方法を変えた上で、patchで試してみていただけると理解できるかと思います... !
本来はpatchにしたいです...

2024-03-19 06:48 UTC, hatschi2023 commented on app/Http/Controllers/Api/Manager/InstructorController.php
> +                'profile_image' => $imagePath,
そうでした！何度もご説明いただきありがとうございます
修正しましたら、成功しました！
![image](https://github.com/yukihiroLaravel/juko_laravel/assets/145645279/f68e267f-d03d-4ed9-ac83-2a1d6abfb291)

2024-03-19 06:50 UTC, hatschi2023 commented on app/Http/Controllers/Api/Manager/InstructorController.php
> +            ]);
まだないという発想がなかったです！なるほどですね！了解しました。

2024-03-19 07:29 UTC, hatschi2023 commented on routes/api.php
> +                });
ルーティングをpatchに変えると、以下エラーメッセージが出ました。
`"Typed property App\\Rules\\InstructorUniqueEmailRule::$email must be string, null used",`
バリデーションでEmailは必須項目としているのに、patchだとnullにしないと通らなくなるからしょうか？
patchだとなぜnullでないといけないのでしょうか？
何かヒントをいただければ助かります！

2024-03-20 12:17 UTC, Hikaru-Giannis commented on routes/api.php
> +                });
自分も取得できないで理由はわからなかったのですが、PHPがPOSTメソッド以外ではapplication/x-www-form-urlencodedやmultipart/form-dataで渡されたパラメタの処理をしてくれない仕様だかららしいです...。

[参考にした記事](https://qiita.com/crhg/items/c43e21bd5f75e64a5dde)

2024-03-20 12:17 UTC, Hikaru-Giannis approved these changes

2024-03-20 12:47 UTC, merged