ステータス更新ロジック作成(川端）
yukihiroLaravel/juko_laravel pull request #495
Opened 2024-03-18 11:38 UTC by junro1307

## 新権限マネージャー設立による配下のinstructorに紐づくレッスン"ステータス"更新API作成
## 子課題2 ロジック作成
## 動作確認
postman　（http://localhost:8080/api/v1/manager/course/1/chapter/1/lesson/1/status) send
test_instructor1から8までprivateからpublicに更新できたことを確認
test_instructor2.3ログイン後のAPIしよう禁止のエラー確認済み
## 確認してほしい所
行の１３３から１３８まで書き方で合っているか。
## 考慮して欲しい所
ご指摘お願いいたします！

2024-03-19 03:11 UTC, yukihiroLaravel requested changes
コメントしました！
ご確認ください！

2024-03-19 03:11 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        $userId = $request->user()->id;
ここは他のメソッドでも使われている
Auth::~
の書き方をしましょう

2024-03-19 03:11 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/LessonController.php
> +
この辺りに、courseとchapterの持つcourse_idが合致するかどうかの照合処理を入れましょう
（下記でchapter_idと比較しているような感じ）

2024-03-20 10:54 UTC, Hikaru-Giannis approved these changes

2024-03-22 00:24 UTC, yukihiroLaravel requested changes

2024-03-22 00:24 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        $userId = $request->user()->id;
$userIdはもう使わなくなったので不要じゃないでしょうか？
今後は、この辺りまで細かくみましょう！

2024-03-23 07:40 UTC, Hikaru-Giannis approved these changes

2024-03-23 07:51 UTC, merged