新規lesson登録時のlesson_attendance作成
yukihiroLaravel/juko_laravel pull request #507
Opened 2024-04-09 01:04 UTC by abeai0

Write
## issue
- https://gut-familie.atlassian.net/browse/JKA-773

## 概要
- 新規lesson登録時のlesson_attendance作成
## 動作確認手順
- instructorでログインして新規lessonを作成後、生徒でログインし直して受講状況が見れるか確認

## 考慮して欲しいこと
- 特にありません

## 確認してほしいこと
 "lesson_id": 12を新規作成し、postmanで http://localhost:8080/api/v1/attendance/1/course/1/chapter/1 をGETした時下記のようなデータを取得することができました。
```
{
    "data": {
        "attendance_id": 1,
        "progress": 10,
        "course": {
            "course_id": 1,
            "title": "PHP入門講座",
            "image": "course/4459908b-3cdf-4521-94fa-c2a9746d92e1.png",
            "chapter": {
                "chapter_id": 1,
                "title": "PHPとは？",
                "lessons": [
                    {
                        "lesson_id": 1,
                        "title": "echo",
                        "completed_lessons_count": 2,
                        "total_lessons_count": 4,
                        "url": "sVbEyFZKgqk",
                        "remarks": "HTMLでは決められたテキストしか表示することができませんでした。\nPHPを使うと、見る人や状況に応じて、表示するテキストを変えることができます。",
                        "lessonAttendance": {
                            "lesson_attendance_id": 1,
                            "status": "completed_attendance"
                        }
                    },
                    {
                        "lesson_id": 12,
                        "title": "レッスン作成テスト",
                        "completed_lessons_count": 0,
                        "total_lessons_count": 4,
                        "url": null,
                        "remarks": null,
                        "lessonAttendance": {
                            "lesson_attendance_id": 13,
                            "status": "before_attendance"
                        }
                    }
                ]
            }
        }
    }
}
```
- "lesson_id": 1の "completed_lessons_count": 2 がなぜ2になるのかわからなかったので教えていただけると嬉しいです。
- lessonのstatusがprivateになっているもの（ "lesson_id": 12）ここでデータを渡してしまっていいのかということが気になりました。

2024-04-10 08:51 UTC, Hikaru-Giannis requested changes

2024-04-10 08:51 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            $attendances = $lesson->chapter->course->attendances;
この書き方では、おそらく遅延ローディングの原因になってしまいますので、今回のケースだと`attendances`テーブルから、course_idを条件に取得した方が良いかと思いました！
一見、DBのI/Oが発生しているか分からないという点も含んでいます。

2024-04-10 08:51 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            }
コレクションのメソッドを駆使すると、直感的なデータ操作が行えるので、ぜひコレクションメソッドを使用してみてください！他の実装でも比較的コレクションメソッドを用いていたので、一貫性を持たせるという目的もあります。
しかし、メリット、デメリットはあるので、コレクションメソッドを使うことが正しいというわけではないことをご理解いただければと思います！

2024-04-10 08:51 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/LessonController.php
DBに対して、複数のレコードを操作を行うのでトランザクションを導入しましょう！

2024-04-11 12:13 UTC, Hikaru-Giannis requested changes

2024-04-11 12:13 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            DB::commit();
実装は問題ないです！
しかし、一度変数名に格納したり、参照渡しにする必要性はないため、次のようなコードだといかがでしょう？
どういう時に変数に格納するかという定義は難しいですが、スコープが狭い、直感的にどんなデータなのか理解ができるプロパティの値であれば変数への格納は不要かと個人的には考えます。決して、どちらが正しいという話ではないので、あべさんの判断で修正するかお任せします！

```php
            /** @var Lesson $lesson */
            $lesson = Lesson::create([
                'chapter_id' => $request->chapter_id,
                'title' => $request->title,
                'status' => Lesson::STATUS_PRIVATE,
                'order' => (int) $maxOrder + 1
            ]);

            $attendances = Attendance::where('course_id', $request->course_id)->get();
            $attendances->each(function ($attendance) use ($lesson) {
                LessonAttendance::create([
                    'attendance_id' => $attendance->id,
                    'lesson_id'     => $lesson->id,
                    'status'        => LessonAttendance::STATUS_BEFORE_ATTENDANCE
                ]);
            });

            DB::commit();
            return response()->json([
                "result" => true,
                "data" => new LessonStoreResource($lesson),
            ]);
```

2024-04-11 12:13 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            ]);
ここはサーバーエラーとしたいので、HTTPステータスを500で返すようにお願いします！

2024-04-11 23:52 UTC, abeai0 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            DB::commit();
ありがとうございます。
確かにnewLessonではなくてlessonで良さそうです！
Managerの方はnewLessonになっているのですが、それは何か意図があるのでしょうか？

2024-04-11 23:54 UTC, abeai0 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            ]);
削除してしまっていました、ありがとうございます。
Managerの方は500が入っていないのですが、このままで大丈夫でしょうか？

2024-04-12 12:38 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            DB::commit();
> Managerの方はnewLessonになっているのですが、それは何か意図があるのでしょうか？

むしろ意図していない実装になっていましたね...。実装者が別なので、見落としていました。
申し訳ございませんが、Instructorの実装をMangerに反映していただくようにお願いします🙇‍♂️

2024-04-12 12:38 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            ]);
APIごとでレスポンスが不揃いなのは良くないので、500で統一するようにお願いいたします🙇‍♂️

2024-04-12 20:27 UTC, abeai0 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            ]);
ありがとうございます、修正しました。

2024-04-12 20:27 UTC, abeai0 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            DB::commit();
ありがとうございます、修正しました。

2024-04-13 05:54 UTC, Hikaru-Giannis approved these changes

2024-04-13 05:54 UTC, merged