Feature/seiji/jka 779/empty array controller router
yukihiroLaravel/juko_laravel pull request #509
Opened 2024-04-11 03:30 UTC by Celadon67

## issue
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-779
## 概要
- 講師側 受講生詳細画面の学習状況を取得するAPIを作成　子課題
  空の配列を返すルータとコントローラの作成
## 動作確認手順
- GETリクエストで/api/v1/instructor/attendance/{attendance_id}/statusを実行
  iattendance_idを入力してからの配列が返ってくる
## 考慮してほしいこと
- 今回は特にありません。
## 確認してほしいこと
- 今回は特にありません。

2024-04-12 04:54 UTC, yukihiroLaravel requested changes
いくつか記載しましたのでご確認ください！

2024-04-12 04:54 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +    public function learningStatus(int $attendance_id): JsonResponse
関数名は他の似た部分もそうなのですがシンプルに
status
という関数名でいいかと思いました！

2024-04-12 04:54 UTC, yukihiroLaravel commented on routes/api.php
> +            });
すでにこちらは
Route::middleware('instructor')->group(function () {
で囲われている場所なので
Route::middleware('instructor')->group(function () {});
は不要なのと

このファイルの121行目あたりに
Route::prefix('attendance')->group(function () {
が存在するので、その中にこのルーティングを描くように変更しましょう。

2024-04-12 04:54 UTC, yukihiroLaravel requested changes
いくつか記載しましたのでご確認ください！

2024-04-12 06:00 UTC, yukihiroLaravel requested changes
コメント一件追加しました！

2024-04-12 06:00 UTC, yukihiroLaravel commented on routes/api.php
> +                    Route::get('{attendance_id}/status', 'Api\Instructor\AttendanceController@status');
ここは同じURLである
{attendance_id}
が両方で使われているので
prefixでまとめられると思います！

2024-04-13 21:56 UTC, yukihiroLaravel requested changes
GitHubにて回答しましたのでご確認ください！

2024-04-13 21:56 UTC, yukihiroLaravel commented on routes/api.php
> +                    Route::post('/', 'Api\Instructor\AttendanceController@store');
このpostのルーティングまで入れてしまうとURLが変わってしまうのでまずいですね💦
このルーティングは除きましょう！

2024-04-13 21:56 UTC, yukihiroLaravel commented on routes/api.php
> +
ここの空行は不要です！

2024-04-13 21:56 UTC, yukihiroLaravel commented on routes/api.php
> +                    Route::delete('/', 'Api\Instructor\AttendanceController@delete');
これはこの内容でOKです。
確かに他のルーティングに影響を与える記述ですが
結果的に元とURLは変わらないからです。

もし変えてしまったのかどうか不安であれば、
ここのルーティングもPostmanで動作確認いただければいいと思います！

2024-04-13 21:56 UTC, yukihiroLaravel commented on routes/api.php
> +                    Route::delete('/', 'Api\Instructor\AttendanceController@delete');
つまり、原則他のルーティングに影響は与えない方がいいが
結果的にURLなど動作が変わらなければ、変更をしてもOK
動作が変わってしまうのであれば変更はNG
ということです。

2024-04-14 10:33 UTC, Hikaru-Giannis approved these changes

2024-04-14 10:37 UTC, merged