JKA-779 講師側受講状況API ロジックの作成(小林)
yukihiroLaravel/juko_laravel pull request #512
Opened 2024-04-14 07:43 UTC by Celadon67

## issue
- Closes #
## 概要
-
## 動作確認手順
-
## 考慮してほしいこと
- 今回は特にありません。
## 確認してほしいこと
- 今回は特にありません。

2024-04-14 12:58 UTC, yukihiroLaravel requested changes

2024-04-14 12:58 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        $attendance = Attendance::find($attendance_id);
findOrFail()

2024-04-14 12:58 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        }
消える

2024-04-14 12:58 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        $attendance->load('chapters');
いらない？

2024-04-14 21:53 UTC, yukihiroLaravel requested changes
ありがとうございました！
いくつかコメントしました！

2024-04-14 21:53 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/CourseController.php
> +    }
この記述はすべて使われていないので不要かと思いました！

2024-04-14 21:53 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        }
try catchは今回プロジェクトにおいては
主に複数テーブルにまたがって
変更する場合などに使うので、
不要かと思います！

2024-04-14 21:53 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                ],
チャプターの情報が取得できていないと思いますが、いかがでしょうか？

2024-04-15 00:51 UTC, yukihiroLaravel requested changes
さらにコメントしました！

2024-04-15 00:51 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        }
結局これは消せるという話だったと思いますが
消したらうまくいかないでしょうか？

2024-04-15 00:51 UTC, yukihiroLaravel commented on routes/api.php
> +                });
前プルリクでで変更したはずのここが
現れてくるのはおかしい気がするので
topicでpullして
このfeatureブランチに最新のtopicをマージすべきかと思います！

2024-04-15 00:57 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        }
失礼いたしました。消したけどエラー出るから残さないといけないかと思っていたのですが、他のミスが原因で消したときにエラーが生じたため、現在は消してもエラー出ませんでした。

2024-04-15 01:12 UTC, Celadon67 commented on routes/api.php
> +                });
topicでpullしてfeatureブランチに最新のtopicをマージし、解決したかと思います!!

2024-04-15 03:27 UTC, yukihiroLaravel requested changes

2024-04-15 03:27 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +
指摘漏れておりすみませんが、
この辺りに
認証の処理（ログイン講師のIDとattencanceから抽出したinstructor_idが合致するかどうかの検証機能など）も
必要になると思いますので、入れましょう。

```
            if (Auth::guard('instructor')->user()->id !== $attendance->course->instructor_id) {
                return response()->json([
                    "result" => false,
                    "message" => "Unauthorized: The authenticated instructor does not have permission to delete this attendance record",
                ], 403);
            }
```

2024-04-15 11:44 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        $attendance = Attendance::findOrFail($attendance_id);
Eager Loadingを考慮して書き直してみましょうか！
用語が分かれなければ、まずは調べてみてください🙇‍♂️

修正前後で動作は変わりませんが、DBのI/Oの観点などで利点があります。

2024-04-16 12:23 UTC, Hikaru-Giannis approved these changes

2024-04-16 21:27 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
お疲れ様でした！

2024-04-16 21:27 UTC, merged