JKA-779 講師側受講状況API フォームリクエストの作成（小林）
yukihiroLaravel/juko_laravel pull request #516
Opened 2024-04-16 16:07 UTC by Celadon67

## issue
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-779
## 概要
- 講師側 受講生詳細画面の学習状況を取得するAPIを作成　子課題
  フォームリクエストの作成
## 動作確認手順
- http://localhost:8080/api/v1/instructor/attendance/2/status
  にアクセスすると値をとれるが、
  http://localhost:8080/api/v1/instructor/attendance/1/status
  にアクセスすると下記エラーが表示される

  {
    "message": "The given data was invalid.",
    "errors": {
        "attendance_id": [
            "The selected attendance id is invalid."
        ]
    }
}

## 考慮してほしいこと
- 今回は特にありません。
## 確認してほしいこと
- 今回は特にありません。

2024-04-17 06:18 UTC, yukihiroLaravel requested changes
かしこまりました！
１点指摘しました！

2024-04-17 06:18 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +    public function status(int $attendance_id, AttendanceStatusRequest $request): JsonResponse
今は
int $attendance_id, 
は削除しましょう

2024-04-17 12:40 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
こちら修正前のレスポンス構造が正常なので、元に戻していただきたいです！
すみませんが、よろしくお願いいたします🙇‍♂️

2024-04-17 13:47 UTC, yukihiroLaravel requested changes
１点変えられた部分についてコメントしました！

2024-04-17 13:47 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        $attendance_id = $request->input('attendance_id');
変数名がスネークケースになっていますが、
他の部分は原則キャメルケースなので
$attendanceId = $request->input('attendance_id');
にしましょう！

2024-04-19 03:19 UTC, yukihiroLaravel requested changes
いくつかコメントしました！ご確認ください！

2024-04-19 03:19 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                ];
インデントがおかしいですね。
あと、当初のレスポンスだと
30%なら
30
という数値だけを返すようになっていたはずなので
$progress = も%も不要ですね！

2024-04-19 03:19 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            "message" => "Unauthorized: The authenticated instructor does not have permission to delete this attendance record",
インデントがおかしくなっていますね

2024-04-19 03:19 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                ->first();
ここも４つスペース分インデントをつけましょう！

2024-04-19 03:19 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                }
$progressの中身を数値にしなくても
シンプルに$isCompletedなどのfalseかtrueどちらかを示す変数を定義して
完了していたらtrue、完了していなかったらfalseを入れ
それを現在存在する全てのlessonの数で割ったほうが正しい
かつ分かりやすい数値が出るかと思いました！

2024-04-19 03:19 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            ];
インデントがここもおかしいですね！

2024-04-19 03:19 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                if ($lessonAttendance && $lessonAttendance->status === LessonAttendance::STATUS_COMPLETED_ATTENDANCE) {
$lessonAttendanceの存在の有無はフォームリクエストで確認済みのため
$lessonAttendance &&
は不要ではないでしょうか？

2024-04-19 12:20 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                ];
修正しました。

2024-04-19 12:26 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                if ($lessonAttendance && $lessonAttendance->status === LessonAttendance::STATUS_COMPLETED_ATTENDANCE) {
修正いたしました。

2024-04-19 12:32 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            ];
添付写真のようにインデントは下がっているはずなのですが...
![スクリーンショット 2024-04-19 215316](https://github.com/yukihiroLaravel/juko_laravel/assets/151298156/70d64660-e713-46d8-8e05-2d85806d133e)

2024-04-19 12:32 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                ->first();
添付写真のようにインデントは下がっているはずなのですが...
![スクリーンショット 2024-04-19 212958](https://github.com/yukihiroLaravel/juko_laravel/assets/151298156/30a008f0-ce6c-4dd0-818b-a3e21e6cbf46)

2024-04-19 12:32 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            "message" => "Unauthorized: The authenticated instructor does not have permission to delete this attendance record",
添付写真のようにインデントは下がっているはずなのですが...
![スクリーンショット 2024-04-19 212746](https://github.com/yukihiroLaravel/juko_laravel/assets/151298156/5aeab800-cb19-497d-b064-3a468a97f647)

2024-04-19 12:40 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                }
修正いたしました。

2024-04-19 13:55 UTC, yukihiroLaravel requested changes
考え方は合っているのですが、
コンフリクト解消のコードが残っており動作確認できないのと

全体として小林さんが担当でないところまでインデントが多数崩れており
かなりコードが煩雑になっているので、お手数ですが修正お願いします！

2024-04-19 13:55 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        << << <<< HEAD
これだとコンフリクトでエラーになると思いますので削除しましょう

2024-04-19 13:55 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +		=======
これだとコンフリクトでエラーになると思いますので削除しましょう

2024-04-19 13:55 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                'progress' => $isCompleted ? 100 : 0,
ここで個別のレッスンの進捗率progressは使うことはなさそうに思うので不要かと思います。

2024-04-20 10:19 UTC, Hikaru-Giannis requested changes

2024-04-20 10:19 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            });
このコードは、「完了済みのデータ集計」と、「データ加工」の2つの責務に関する処理を行なってしまっているので、別々でコードを書いていただくようお願いします！

完了済みのデータ集計は、Collectionメソッドにreduceというのがあるので、それを利用するといいかもしれないです！

2024-04-21 09:49 UTC, Hikaru-Giannis requested changes

2024-04-21 09:49 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +    }
関数名にDataなどの汎用的な言葉は避けた方が良いです。
他の関数はDataではないのかというと、境界線が曖昧になり、齟齬が起きる原因になるからです！

2024-04-21 09:49 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            ->first();
これはN+1問題が起きてしまうので、それがどのような問題でどのように解消するかを調べて修正してみていただければと思います！

2024-04-21 09:49 UTC, Hikaru-Giannis commented on app/Http/Requests/Instructor/AttendanceStatusRequest.php
> +    }
この関数は定義することなく、Requestのインスタンスのプロパティとして、attendance_idを参照できるので修正をお願いします！

2024-04-22 10:31 UTC, Hikaru-Giannis requested changes

2024-04-22 10:31 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        $chapterData = $this->calculateChapterProgress($attendance);
関数名と同様にDataを変数名に名付けるのは避けましょう。

2024-04-22 10:31 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        $chapters = $attendance->course->chapters()->with(['lessons', 'lessons.lessonAttendances'])->get();
このコードの実装意図をお聞きしたいです！
というのも後述で一度も参照されていないためでした。

2024-04-22 10:31 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            ->first();
このコードでDBにアクセスしていると思いますが、ループ内でDBにアクセスするとN+1問題が起きてパフォーマンスに支障が起きてしまいます。もし、DBにアクセスせざるを得ないのであれば、その理由を教えていただけると嬉しいです！

2024-04-22 10:31 UTC, Hikaru-Giannis commented on app/Http/Requests/Instructor/AttendanceStatusRequest.php
> +    }
attendance_idをプロパティとして、参照できたのであれば削除お願いします！

2024-04-24 13:52 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +		=======
修正しました。

2024-04-24 13:52 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        << << <<< HEAD
修正しました。

2024-04-24 13:52 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                'progress' => $isCompleted ? 100 : 0,
了解いたしました。

2024-04-24 13:52 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +    }
修正いたしました。

2024-04-24 13:52 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            ->first();
修正いたしました。

2024-04-24 13:52 UTC, Celadon67 commented on app/Http/Requests/Instructor/AttendanceStatusRequest.php
> +    }
修正いたしました。

2024-04-24 13:52 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        $chapterData = $this->calculateChapterProgress($attendance);
修正いたしました

2024-04-24 13:52 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        $chapters = $attendance->course->chapters()->with(['lessons', 'lessons.lessonAttendances'])->get();
slackの文章に追記したように、ここもN+1問題が生じると思ったためです。
これについてはゆきひろさんにも確認を取り、確かに生じる可能性があるから書いても問題ないのではないかと昨日の作業会時にコメントいただき、追記させていただきました。

追記した旨はslackの文章に書かせていただきました。また、slackの文章内でも　←ここです　と表記しお伝えしました。

後述で一度も参照されていなとのことで修正しました。

また、下記の話とあわせて、N+1問題を解消するため、チャプターの進捗計算及びチャプター内完了済みレッスン数計算　の部分をまとめて修正しましたので、変更がまたがっています。

2024-04-24 13:52 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            ->first();
上記とあわせ、N+1問題が起きないよう、データベースに触る回数が少ないよう、チャプターの進捗計算、チャプター内完了済みレッスン数計算　まとめて修正いたしました。

2024-04-24 13:52 UTC, Celadon67 commented on app/Http/Requests/Instructor/AttendanceStatusRequest.php
> +    }
前回のものは修正が反映されていませんでした。今回修正・削除いたしました。

2024-04-26 09:38 UTC, Hikaru-Giannis requested changes

2024-04-26 09:38 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        })->count();
こちらは意図通りのチャプター内完了済みレッスン数を取得できてましたでしょうか？
私の環境では0になっていたので、確認でした！

2024-04-27 06:56 UTC, Hikaru-Giannis approved these changes

2024-04-27 07:20 UTC, merged