JKA-779 講師側受講状況API レスポンス整形のリソースファイル作成（小林）
yukihiroLaravel/juko_laravel pull request #517
Opened 2024-04-17 11:04 UTC by Celadon67

## issue
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-779
## 概要
- 講師側 受講生詳細画面の学習状況を取得するAPIを作成　子課題
  レスポンス整形のリソースファイル作成
## 動作確認手順
- http://localhost:8080/api/v1/instructor/attendance/2/status
  にアクセスすると値をとれるが、
  http://localhost:8080/api/v1/instructor/attendance/1/status
  にアクセスすると下記エラーが表示される

{
"message": "The given data was invalid.",
"errors": {
"attendance_id": [
"The selected attendance id is invalid."
]
}
}

## 考慮してほしいこと
- 今回は特にありません。
## 確認してほしいこと
- 今回は特にありません。

2024-04-28 00:40 UTC, yukihiroLaravel requested changes
いくつか指摘させていただきましたのでご確認ください！

2024-04-28 00:40 UTC, yukihiroLaravel commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +    if ($this->attendance !== null && is_object($this->attendance)) {
$this->attendance !== null && is_object($this->attendance
これはフォームリクエストでattendanceが存在しない場合はすでに弾いている認識ですが必要でしょうか？

あとオブジェクトでない場合も考えにくいかなと思いましたが、いかがでしょうか？

2024-04-28 00:40 UTC, yukihiroLaravel commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +    }
インデントがずれていますので修正願います！

2024-04-28 00:40 UTC, yukihiroLaravel commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +    if ($this->attendance !== null && is_object($this->attendance)) {
もし存在しないパターンがあったとしても
return []
で空の配列を返すのではなく
明確にどんなエラーが生じているのかを返した方がいいと思います！

2024-04-28 01:04 UTC, Celadon67 commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +    if ($this->attendance !== null && is_object($this->attendance)) {
- $this->attendance !== null && is_object($this->attendance　は不必要でしたので、削除いたしました。
- return []　ではなく具体的に 'Data not found　の表記にしました。

2024-04-28 01:07 UTC, Celadon67 commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +    }
```
public function toArray($request)
    {
    if ($this->attendance !== null && is_object($this->attendance)) {
```
ではなく
```
public function toArray($request)
    {
        if ($this->attendance !== null && is_object($this->attendance)) {
```
が正しい、ということで合っていますでしょうか?そのように修正し、それに合わせて他の配列も後にインデントをずらしました。

2024-04-28 11:58 UTC, Hikaru-Giannis commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +    }
リソースファイルの責務としては、主にデータの整形処理になります。
 ですので、計算処理はビジネスロジックと呼ばれるシステムのコアに近いコードなので、コントローラーに記述したままで問題ありません！

2024-04-29 11:43 UTC, Hikaru-Giannis requested changes

2024-04-29 11:43 UTC, Hikaru-Giannis commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +    }
この2つの関数がレビューしているビジネスロジックと表現しているコアのコードにが意図する箇所です！
最初のレビュー時はコントローラーに記述しても良いと表現していましたが、コントローラーで同時に整形処理も行っているので一見リソースファイルを設ける必要性が難しくなってしまいますので、これらのビジネスロジックのコードはモデルに移植するようにお願いします！ Chapterモデルに下のように定義する⇩

```php
    /**
     * チャプターの進捗計算
     *
     * @param Attendance  $attendance
     * @return array
     */
    public function calculateChapterProgress(Attendance $attendance): int
    {
        $completedLessonsCount = $this->calculateCompletedLessonCount($this, $attendance);
        $totalLessonsCount = $this->lessons->count();
        return $totalLessonsCount > 0 ? ($completedLessonsCount / $totalLessonsCount) * 100 : 0;
    }

    /**
     * チャプター内完了済みレッスン数計算
     *
     * @param Chapter $chapter
     * @param Attendance $attendance
     * @return int
     */
    private function calculateCompletedLessonCount(Chapter $chapter, Attendance $attendance): int
    {
        return $chapter->lessons->filter(function (Lesson $lesson) use ($attendance) {
            $lessonAttendance = $lesson->lessonAttendances->firstWhere('attendance_id', $attendance->id);
            return $lessonAttendance && $lessonAttendance->status === LessonAttendance::STATUS_COMPLETED_ATTENDANCE;
        })
        ->count();
    }
```

2024-04-29 11:43 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
>      }
Resourceファイル自体がJSONでレスポンスを返すようにする責務を担っているので、他の実装同様に次のコードでreturnを記述するようにお願いします！エラーが出る場合は、他の原因を探ってみてください！

```php
        return new AttendanceStatusResource($attendance);
```

2024-04-29 11:43 UTC, Hikaru-Giannis commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +    }
どうして、計算と整形処理を分離する必要があるかというと、分離しておくと再利用がしやすいというのと、チャプターの進捗計算を単体でテストすることができるようになり保守性が良くなるという利点があります！

2024-04-29 14:18 UTC, Celadon67 commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +    }
修正しました。

2024-04-29 16:14 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
>      }
修正しました。

2024-04-30 15:10 UTC, Hikaru-Giannis requested changes

2024-04-30 15:10 UTC, Hikaru-Giannis commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +        return response()->json($data);
このreturnは不要では、ありませんか？
問題がなければ削除お願いします！

2024-04-30 15:10 UTC, Hikaru-Giannis commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +    private function calculateChapterProgress($chapters)
このメソッドはチャプターに関するデータのマッピングを行っているので、`mapChapters`などが適切かと思いました！
計算の責務はモデルに移植しましたので！

2024-04-30 15:10 UTC, Hikaru-Giannis commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +    }
Resourceファイルは、インスタンス生成時に渡したデータはその特性上、`public $resource;`に格納されるので、コンストラクタは不要です！次のようなコードで、受講データを参照することができますので、修正をお願いします！

```php
// attendanceのidを参照する例
'attendance_id' => $this->resource->id,
```

2024-04-30 20:17 UTC, Celadon67 commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +        return response()->json($data);
削除しました。

2024-05-01 07:17 UTC, Celadon67 commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +    private function calculateChapterProgress($chapters)
修正しました。

2024-05-01 07:41 UTC, Celadon67 commented on app/Http/Resources/Instructor/AttendanceStatusResource.php
> +    }
修正しました。

2024-05-01 10:03 UTC, kou-tech approved these changes

2024-05-01 10:37 UTC, yukihiroLaravel approved these changes
マージしました！

2024-05-01 10:37 UTC, merged