新権限マネージャー設立による配下のinstructorの作成した講座の受講情報を削除するAPI作成（ロジック作成）
yukihiroLaravel/juko_laravel pull request #520
Opened 2024-04-20 19:56 UTC by sora1012

## issue
- 新権限マネージャー設立による配下のinstructorの作成した講座の受講情報を削除するAPI作成、ロジックの作成

## 動作確認手順
- ポストマンで、delete形式で
localhost:8080/api/v1/manager/attendance/1と入力

## ご考慮いただきたいこと
- 特にありません

## ご確認いただきたいこと
- 特にありません

2024-04-24 11:30 UTC, Hikaru-Giannis requested changes

2024-04-24 11:30 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            $attendance = Attendance::with('lessonAttendances')->findOrFail($attendanceId);
withを使っている理由があれば教えてください！

2024-04-24 11:30 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            $managedAttendances = Attendance::whereIn('id', $instructorIds)->pluck('id')->toArray();
Attendanceのidと講師のidリストは比較対象にはならないかと思います！
どの値で比較するべきかを一度吟味してみて、修正をお願いします！

2024-04-24 11:30 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +                'message' => 'Attendance record deleted successfully.'
他のAPIはメッセージを設けていないので、削除いただけますか？
親切なので問題があるわけではないです！

2024-04-24 11:30 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            ], 500);
他のAPIはメッセージを設けていないので、削除いただけますか？
親切なので問題があるわけではないです！

2024-05-08 12:57 UTC, sora1012 commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            $attendance = Attendance::with('lessonAttendances')->findOrFail($attendanceId);
調べて学んだ情報ではあるのですが、withを使うと関連付けられたデータを一度のクエリで取得することができ、効率的なデータ取得ができるからです。

2024-05-08 13:13 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            $attendance = Attendance::with('lessonAttendances')->findOrFail($attendanceId);
下記打ち合わせで共有済み。

attendanceはdeleteが実行されると、lessonAttendancesも必然に削除されるように実装されている。
しかし、その処理ではどちらにせよDBへのI/Oが走っているので、事前に取得する必要性はないため、withの記述は削除するように修正を依頼。

2024-05-11 01:53 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            $attendance->delete();
ここは敢えてインスタンスを生成する必要はないので、次のように書けませんか？

```php
            Attendance::findOrFail($attendanceId)->delete();
```

2024-05-15 13:17 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            $attendance = Attendance::findOrFail($attendanceId)->delete();
参照しないのであれば、$attendance の削除をお願いします！

2024-05-22 13:00 UTC, kou-tech approved these changes

2024-05-23 11:55 UTC, merged