Feature/jka 805/instructor course attendance status today
yukihiroLaravel/juko_laravel pull request #521
Opened 2024-04-20 20:20 UTC by abeai0

## issue
-Closes jka-805

## 概要
- 講師側 ダッシュボード 本日のレッスン・チャプター完了数 取得APIの実装

## 動作確認手順
- Postmanで講師 id：1 でログイン後GET http://localhost:8080/api/v1/instructor/course/1/attendance/status/today　をする

## 考慮して欲しいこと
- 今日完了したという条件をどのようにつけるのかわからず、困っています。
- 257行目 ifの後にdd($completedChaptersCount);をすると1が帰ってくるのですが、ここですると0になる理由がわからず、困っています。

## 確認してほしいこと

2024-04-21 11:53 UTC, Hikaru-Giannis requested changes

2024-04-21 11:53 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        }
クラス内で定義する関数はアクセス修飾子をつけて、記述しましょう！

2024-04-21 11:53 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        }
すみません、この段階では判断しかねるので、お待ちください。
強いていうのであれば、ただのレッスン合計数を取得するのであればその要素数を取得することができたりするので...。

2024-04-22 11:13 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
詳しい動作確認までできていないのですが、次のようなコードのアプローチで一度試していただけますか？
そうすると、最低限のDBのI/Oで実装可能な気がしております。

```php
        // ① withを使って、lessonAttendancesと一緒にattendancesを取得
        // withはN+1問題を解消するために使う
        $attendances = Attendance::with([
            'lessonAttendances.lesson.chapter.course'
            ])
            ->where('course_id', $request->course_id)
            ->get();

        // ② lessonAttendancesのstatusがcompleted_attendanceかつ、updated_atが今日のものの数をカウント
        // flatMapを使うと、多次元配列を1次元配列に変換してくれる
        $completedLessonsCount = $attendances->flatMap(function ($attendance) {
            ....
        })
        ->count();

        // ③ chapter_idとattendance_idを同一キーとして扱い、重複を削除してカウントしている
        $completedChaptersCount = $attendances->flatMap(function ($attendance) {
            ....
        })
        ->map(function ($lessonAttendance) {
            // chapter_idとattendance_idを同一キーとして扱う
            ....
        })
        ->unique()
        ->count();

```

2024-04-23 08:39 UTC, abeai0 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
すみません、chapter_idとattendance_idを同一キーとして扱うということがよくわかりませんでした。
もう少し掘り下げていただけると助かります。

2024-04-25 04:56 UTC, Hikaru-Giannis requested changes
全体として、変数はキャメルケースでお願いします！

2024-04-25 04:56 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                return $lessonAttendance->status == 'completed_attendance' && $lessonAttendance->updated_at->format('Y-m-d') == $today;
比較するレッスン状況の識別値は、定数がモデルに定義されているのでそちらを参照するようにお願いします。
他の実装部分でも、レッスン状況の識別値をハードコーディングしている箇所は全て定数でお願いします。

2024-04-25 04:56 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                return $lessonAttendance->status == 'completed_attendance' && $lessonAttendance->updated_at->format('Y-m-d') == $today;
作業会でも共有しましたが、日付の比較はCarbonのメソッドを使いましょう。
isToday()とか利用できないでしょうか？
https://carbon.nesbot.com/docs/

2024-04-25 10:06 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        })->unique()->count();
自分も勘違いしていましたが、`chapter_id`と`attendance_id`の組み合わせで重複されるケースはないですよね...？
unique()が不要かと思いました！

2024-04-25 10:07 UTC, Hikaru-Giannis requested changes

2024-04-25 10:07 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        // })->unique()->whereNotNull()->count();
削除して問題ないです！

2024-04-25 10:09 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        })->unique()->count();
これらのロジックは、我々以外何をしているか把握しづらいので、コメントで補足すると良いと思います。

2024-04-25 10:14 UTC, abeai0 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        })->unique()->count();
lessonAttemdamceをmapしているので、同じchapterのlessoのlessonAttendanceが重複してしまうので、uniqueは必要かと思います！

2024-04-27 06:02 UTC, Hikaru-Giannis approved these changes

2024-04-27 06:02 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        })->unique()->count();
なるほど！ありがとうございます！

2024-04-27 06:49 UTC, merged