feature/ohtomo/create_logic_for_notification_registration_jka744_2
yukihiroLaravel/juko_laravel pull request #523
Opened 2024-04-22 14:01 UTC by to-ohtomo

## issue
JKA-804

## 概要
お知らせ登録API作成 ロジックの作成
（JKA-744の子課題）

## 動作確認手順
・postmanにて、
メソッド: POST、URL: http://localhost:8080/api/v1/manager/course/1/notification
に接続し、レスポンスがtrueになることを確認しました。

・DataBaseのnotificationにデータが格納されることを確認しました。

## 考慮してほしいこと
なし

## 確認してほしいこと
なし

2024-04-23 11:51 UTC, Hikaru-Giannis requested changes

2024-04-23 11:51 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        array_push($instructorIds, $instructorId);
少し細かいですが、次のように変更をお願いできますか？

```php
$instructorIds[] = $manager->id;
```

理由としては、配列の追加処理は最新の記法では、あまりarray_pushは使われない、他の実装に合わせることであったり、$instructorIdはリクエスト値なので、それよりもモデルである$managerのidとわかる表現の方が理解しやすいためでした。

2024-04-23 11:51 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        $course = Course::FindOrFail($request->course_id);
FindOrFailを他の記法と統一して、findOrFailに修正をお願いします！

2024-04-23 13:36 UTC, to-ohtomo commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        $course = Course::FindOrFail($request->course_id);
ご指摘有難うございます。
修正させていただきます。

2024-04-23 13:36 UTC, to-ohtomo commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        array_push($instructorIds, $instructorId);
ご指摘有難うございます。
修正させていただきます。

2024-04-23 13:56 UTC, to-ohtomo commented
ご指摘の箇所を修正させていただきました。
お手数ですが、再レビューをお願い致します。

2024-04-24 11:12 UTC, Hikaru-Giannis approved these changes

2024-04-24 11:12 UTC, Hikaru-Giannis approved these changes

2024-04-24 12:28 UTC, merged