受講生側 お知らせ一覧API作成 ロジックの作成
yukihiroLaravel/juko_laravel pull request #524
Opened 2024-04-23 17:40 UTC by yuyakondo333

## 概要
 - 受講生側 お知らせ一覧API作成 ロジックの作成
## 動作確認手順
 - /login
 - //api/v1/notification/index
 - PostmanでParamに「order desc」、「sort_by start_date」
 - PostmanでParamに「order asc」、「sort_by title」
 - PostmanでParamに「order asc」、「sort_by course_title」
 - NotificationSeederでお知らせを増やしてページネーションを確認
## 考慮してほしいこと
 - ページネーションの際、お知らせの数を21以上に増やして確認してください。
## 確認してほしいこと
 - レスポンスが返ってきているか
 - タイトル、講座名、開始日時に関してsortできているか

2024-04-24 11:26 UTC, Hikaru-Giannis requested changes
タイトル、講座名、開始日時でソートはどのように動作確認していたかおしえていただけますか？
スクショなどを貼っていただくと嬉しいです！

2024-04-24 11:26 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Student/NotificationController.php
> +// use Illuminate\Support\Facades\Auth;
参照しないのであれば、削除お願いします。

2024-04-24 11:26 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        $student = Student::findOrFail($request->user()->id);
studentのidだけであれば、$request->user()->id で取得できると思うのですが、何か意図があったりしますか？

2024-04-24 11:26 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        $currentDateTime = Carbon::now();
Carbonだとミュータブルといって、変更される可能性があるインスタンス生成されてしまうため、なるべくCarbonImmutableを使うと良いと思います！

2024-04-24 11:26 UTC, Hikaru-Giannis commented on app/Http/Resources/Student/NotificationIndexResource.php
> +            ],
こちらpaginateを使うとコレクションではなく、LengthAwarePaginatorのインスタンスとなります。
なので、動作上は問題ないのですが、メソッドのドキュメントに渡す時にcollectionとして渡してあげるのが望ましいです。
`getCollection`は実はそのためのメソッドだったということですね。

なので、mapNotificationsにはgetCollectionを利用して、明示的にCollectionを渡すようにお願いします。

2024-04-24 13:02 UTC, yuyakondo333 commented on app/Http/Controllers/Api/Student/NotificationController.php
> +// use Illuminate\Support\Facades\Auth;
削除しました。

2024-04-24 13:02 UTC, yuyakondo333 commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        $student = Student::findOrFail($request->user()->id);
特に意図はないので、$request->user()->id に修正します。

2024-04-24 13:04 UTC, yuyakondo333 commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        $currentDateTime = Carbon::now();
かしこまりました！CarbonImmutableに修正します。

2024-04-24 13:30 UTC, yuyakondo333 commented on app/Http/Resources/Student/NotificationIndexResource.php
> +            ],
MTGでのご説明ありがとうございます！
$notifications->getCollection()
こちらに修正します。

2024-04-25 10:19 UTC, Hikaru-Giannis requested changes
こちらは講座名によるソートって動作確認できていましたでしょうか？

2024-04-25 10:19 UTC, Hikaru-Giannis commented on app/Http/Requests/Student/NotificationIndexRequest.php
> +            'page' => ['integer', 'min:1'],
sortByとorderもバリデーションルールに含めましょうか！
例えば、許容する文字列が限られるはずです。それ以外の文字列がリクエストされたら、エラーを返すようにしましょう。

2024-04-26 17:18 UTC, closed without merging