jka-799ロジックの作成～受講生側お知らせ詳細API作成(オオハシ)
yukihiroLaravel/juko_laravel pull request #525
Opened 2024-04-25 03:19 UTC by kenta-oohashi

## 概要
- 受講生側お知らせ詳細API作成の子課題　ロジックの作成
## 動作確認手順
- http://localhost:8080/login
- http://localhost:8080/api/v1/notification/1 
## 確認していただきたいこと
-アクセスしたら確認してほしいことアクセスしたら、下記のようにcourse_id,title,contentの情報を取得できるか
{
    "course_id": 1,
    "title": "レッスン「変数とは？」閲覧について",
    "content": "10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。"
}

2024-04-25 10:31 UTC, Hikaru-Giannis requested changes

2024-04-25 10:31 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        $student =  \Auth::user();
ファサードを使うことは間違いではないのですが、他の実装に合わせてRequestクラスのインスタンスから認証者を取得できるので、それに倣って修正をお願いします！

2024-04-25 10:31 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        }
firstOrFailを使うと、条件にヒットしない場合は404となるので、お知らせの取得箇所をfirstOrFailで修正をお願いします。

2024-04-26 09:29 UTC, kenta-oohashi commented
## 概要
- 受講生側お知らせ詳細API作成の子課題　ロジックの作成
## 動作確認手順
- http://localhost:8080/login
- http://localhost:8080/api/v1/notification/1 
## 確認していただきたいこと
-アクセスしたら確認してほしいことアクセスしたら、下記のようにcourse_id,title,contentの情報を取得できるか
{
    "course_id": 1,
    "title": "レッスン「変数とは？」閲覧について",
    "content": "10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。"
}
- firstOrFailが機能するcodeの書き方になっているか
## 考慮していただきたいこと
- 特にありません

2024-04-26 09:41 UTC, kenta-oohashi commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        $student =  \Auth::user();
ほかの方と取得の仕方を合わせて統一感をだしました！

2024-04-26 09:42 UTC, kenta-oohashi commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        }
firstOrFailを検索し、意味を理解して、修正しました！

2024-04-27 06:06 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        }
意味を理解した上で、76~81行目は必要でしょうか？

2024-04-27 08:43 UTC, kenta-oohashi commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        }
firstOrFailはデータベースで条件にヒットするもののみのレコードを見つけ、見つからない場合はエラーとするものだと認識していましたが、エラー文も書く必要はないという事なのですね！
ありがとうございます。早速修正いたしました！

2024-04-27 08:47 UTC, kenta-oohashi commented
## 概要
- 受講生側お知らせ詳細API作成の子課題　ロジックの作成
## 動作確認手順
- http://localhost:8080/login
- http://localhost:8080/api/v1/notification/1 
## 確認していただきたいこと
-アクセスしたら確認してほしいことアクセスしたら、下記のようにcourse_id,title,contentの情報を取得できるか
{
    "course_id": 1,
    "title": "レッスン「変数とは？」閲覧について",
    "content": "10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。"
}
- firstOrFailが機能すると、条件に当てはまるものがない場合、Codeを書かなくてもエラー404としてくれるので、if文のelse(エラーの内容）を削除しました
## 考慮していただきたいこと
- 特にありません

2024-04-28 01:32 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        }
> エラー文も書く必要はない

これは、拡大解釈かもしれません！Laravelはモデルがない場合は例外へスローされるので、こちらでエラーメッセージをコントロールしたい場合は、その例外をキャッチしてコードを記述する必要があります。
今回は一旦そこまでする必要はありませんが、興味があればapp/Http/Controllers/Api/Instructor/ChapterController.phpのsortメソッドはそうしているので、確認してみてください！

2024-04-28 01:38 UTC, Hikaru-Giannis requested changes

2024-04-28 01:38 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        }
elseがない場合、このif文自体必要でなくなると思います！
ポイントで指摘しているので、指摘されたコードを修正後、全体のコードの最適化も都度考えてみましょう！

2024-04-28 01:38 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Student/NotificationController.php
コメントは自分がデバッグした形跡を残すものではなく、他の開発者に実装をより理解してもらう痕跡を残すものです！
そのため、自分にとってのコメントであれば削除し、コードが明示的なもの関してはなるべくコメントを書かない方が良いです。これは現場により特製の違いもあるかもしれませんが、コメントもコードなので、メンテナンスされなければ負債となってしまいます...！

2024-04-28 12:21 UTC, kenta-oohashi commented
## 概要
- 受講生側お知らせ詳細API作成の子課題　ロジックの作成
## 動作確認手順
- http://localhost:8080/login
- http://localhost:8080/api/v1/notification/1 
## 確認していただきたいこと
-アクセスしたら確認してほしいことアクセスしたら、下記のようにcourse_id,title,contentの情報を取得できるか
{
    "course_id": 1,
    "title": "レッスン「変数とは？」閲覧について",
    "content": "10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。"
}
-if文を削除し、求める情報を$dataへいれて、それをjsonに代入する形式にしました
## 考慮していただきたいこと
- 特にありません

2024-04-28 12:53 UTC, Hikaru-Giannis requested changes

2024-04-28 12:53 UTC, kou-tech commented on app/Http/Controllers/Api/Student/NotificationController.php
リクエストにnotificationsテーブルのidカラムの値を含めているので、お知らせのレコードはその値から取得する必要がある。ただし、認可処理は必要なのでその周辺の修正をお願いします！
(2024/04/28 作業会にて口頭で伝え済み。)

2024-04-29 14:08 UTC, kenta-oohashi commented
## 概要
- 受講生側お知らせ詳細API作成の子課題　ロジックの作成
## 動作確認手順
- http://localhost:8080/login
- http://localhost:8080/api/v1/notification/1 
## 確認していただきたいこと
-アクセスしたら確認してほしいことアクセスしたら、下記のように情報を取得できているか
 {
  "data": {
    "notification_id": 1,
    "title": "レッスン「変数とは？」閲覧について",
    "content": "10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。",
    "start_date": "2020-10-01",
    "end_date": "2020-10-10",
    "course": {
      "course_id": 1,
      "title": "プログラミング入門",
    }
  }
- お知らせのレコードがnotificationsテーブルのidカラムの値から取得できているか
## 考慮していただきたいこと
- 前回まで、取得したい情報をcourse_id,title,contentのみにしておりましたが、子タスク①のURL,リクエスト,レスポンスのレビュー時にkouさんよりレスポンスは{
  "data": {
    "notification_id": 1,
    "title": "レッスン「変数とは？」閲覧について",
    "content": "10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。",
    "start_date": "2020-10-01",
    "end_date": "2020-10-10",
    "course": {
      "course_id": 1,
      "title": "プログラミング入門",
    }
  }のように求められていた事をを忘れておりまして、kouさんより求められたレスポンスに変更しております。（忘れており申し訳ございません）
- kouさんから頂いたレスポンスの一部（start_date,end_date,coursetitle)がDBに登録されている内容と違っておりまして、ポストマンでは違うstart_date,end_date,coursetitleが表記されます。

2024-04-30 11:28 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Student/NotificationController.php
> +                        ->firstOrFail();
オオハシさんのコードは間違っていないのですが、DBレイヤーでエラーを出力するという可読性が落ちるコードになっています！パフォーマンスの観点からすると、オオハシさんのコードに利点があります。

ただ、システムのメンテナンスもなるべく受講生の方々が行ったりする都合上、現状は可読性を優先してコードを書く方が色々と利点が多いため、次のようなアプローチで修正をお願いします！他の実装に合わせる目的もありますね。

```php
        // お知らせのidからお知らせを取得
        ...
        
        // お知らせの講座IDがログイン中の生徒の講座IDに含まれていない場合は404を返す
        ...

```

2024-05-01 15:49 UTC, kenta-oohashi commented
## 概要
- 受講生側お知らせ詳細API作成の子課題　ロジックの作成
## 動作確認手順
- http://localhost:8080/login
- http://localhost:8080/api/v1/notification/1 
## 確認していただきたいこと
-アクセスしたら確認してほしいことアクセスしたら、下記のように情報を取得できているか
 {
  "data": {
    "notification_id": 1,
    "title": "レッスン「変数とは？」閲覧について",
    "content": "10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。",
    "start_date": "2020-10-01",
    "end_date": "2020-10-10",
    "course": {
      "course_id": 1,
      "title": "プログラミング入門",
    }
  }
- お知らせのレコードがnotificationsテーブルのidカラムの値から取得できているか
- 前回頂いたレビューと定例MTGで指摘された内容に修正できているか
- URLの最後のnotification_idを1以外にするとエラーとなるか
## 考慮していただきたいこと
- 特ににありません

2024-05-01 15:50 UTC, kenta-oohashi commented on app/Http/Controllers/Api/Student/NotificationController.php
> +                        ->firstOrFail();
そのように修正に試みます！

2024-05-04 11:53 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        }
このif文のコードの書き方だと、今後if文が増える処理が増えるほどネストが深くなり、可読性や保守性が落ちてしまいます。
様々な解消方法はありますが、早期return という方法でネストを減らせるか試してみてください！

他の実装方法とかも参考にしてみると良いと思います！

2024-05-04 12:58 UTC, kenta-oohashi commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        }
ネストの意味や、早期returnを調べて、他の人のif文も参考に考えてやってみます！

2024-05-04 13:20 UTC, kenta-oohashi commented
## 概要
- 受講生側お知らせ詳細API作成の子課題　ロジックの作成
## 動作確認手順
- http://localhost:8080/login
- http://localhost:8080/api/v1/notification/1 
## 確認していただきたいこと
-アクセスしたら確認してほしいことアクセスしたら、下記のように情報を取得できているか
 {
  "data": {
    "notification_id": 1,
    "title": "レッスン「変数とは？」閲覧について",
    "content": "10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。",
    "start_date": "2020-10-01",
    "end_date": "2020-10-10",
    "course": {
      "course_id": 1,
      "title": "プログラミング入門",
    }
  }
- 早期return という方法の使い方があっていて、ネストを減らせて可読性などが落ちないcodeの書き方になっているか
## 考慮していただきたいこと
- 特ににありません

2024-05-05 10:14 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        if (!in_array($notification->course_id, $courseIds)) {
in_arrayは第３引数が大事です！
なぜ他の実装で、第３引数を指定しているのかを考えて修正をお願いします！

2024-05-05 11:36 UTC, kenta-oohashi commented on app/Http/Controllers/Api/Student/NotificationController.php
> +        if (!in_array($notification->course_id, $courseIds)) {
承知しました！第３引数に注目して、他の人の実装のcodeを見て、考えてみたいと思います！

2024-05-05 11:53 UTC, kenta-oohashi commented
## 概要
- 受講生側お知らせ詳細API作成の子課題　ロジックの作成
## 動作確認手順
- http://localhost:8080/login
- http://localhost:8080/api/v1/notification/1 
## 確認していただきたいこと
-アクセスしたら確認してほしいことアクセスしたら、下記のように情報を取得できているか
 {
  "data": {
    "notification_id": 1,
    "title": "レッスン「変数とは？」閲覧について",
    "content": "10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。",
    "start_date": "2020-10-01",
    "end_date": "2020-10-10",
    "course": {
      "course_id": 1,
      "title": "プログラミング入門",
    }
  }
- if文の第３引数があっているか、書き方もあっているか（検索する値の型まで厳密に検査するための第３引数という事をネットで調べて知りました。これもあっているか）
## 考慮していただきたいこと
- 特ににありません

2024-05-05 12:24 UTC, Hikaru-Giannis approved these changes

2024-05-05 12:25 UTC, merged