#828 お知らせ登録API作成 フォームリクエストの作成
yukihiroLaravel/juko_laravel pull request #528
Opened 2024-04-27 05:10 UTC by to-ohtomo

## issue
JKA-828

## 概要
お知らせ登録API作成 フォームリクエストの作成
（JKA-744の子課題）

## 動作確認手順
・postmanにて、
メソッド: POST、URL: http://localhost:8080/api/v1/manager/course/1/notification
に接続し、レスポンスが下記になることを確認しました。
{
    "result": true
}

・DataBaseのnotificationにデータが格納されることを確認しました。

2024-04-27 07:44 UTC, Hikaru-Giannis requested changes

2024-04-27 07:44 UTC, Hikaru-Giannis commented on app/Http/Requests/Manager/NotificationStoreRequest.php
> +            'course_id'     => ['required', 'exists:courses,id', 'integer'],
移植元と実装が違うのであれば申し訳ないのですが、論理削除されている場合もここでエラーを返すようにお願いします🙇‍♂️

2024-04-30 14:20 UTC, to-ohtomo commented on app/Http/Requests/Manager/NotificationStoreRequest.php
> +            'course_id'     => ['required', 'exists:courses,id', 'integer'],
ご指摘有難うございます。修正させていただきます。

2024-05-01 08:18 UTC, Hikaru-Giannis approved these changes

2024-05-01 08:18 UTC, merged