JKA-#808 受講生の年齢を算出・取得(マネージャー)
yukihiroLaravel/juko_laravel pull request #532
Opened 2024-04-29 14:14 UTC by yamaha-win

## issue
 - JKA-808 （マネージャー）受講生詳細APIに現在年齢を追加
## 概要
 - マネージャー権限を持つ講師アカウントで受講生詳細APIに年齢を追加で表示させる
## 考慮してほしいこと
 - 今回は特にありません。
## 確認してほしいこと
 - 今回は特にありません。

2024-04-29 14:39 UTC, yukihiroLaravel requested changes
少しコメントしましたのでお願いします！

2024-04-29 14:39 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/StudentController.php
> +        //受講生の年齢を算出
// 受講生の年齢を算出
このように、//と「受」の文字の間にスペースを一つ入れましょう！

2024-04-29 14:39 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/StudentController.php
> +        $toDay = Carbon::today();
細かいですが todayで１つの単語なので
$todayでいいと思います！

2024-04-29 14:39 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/StudentController.php
> +        $ageData = $birthDay->diffInYears($toDay);
細かいですが todayで１つの単語なので
$todayでいいと思います！

2024-04-30 11:33 UTC, Hikaru-Giannis requested changes

2024-04-30 11:33 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/StudentController.php
> +        $ageData = $birthDay->diffInYears($today);
こちらは生徒に関しての処理なので、モデルに記載しましょうか！
そうすることで、他の処理で再利用したり、単体でテストすることができる利点があります。

2024-04-30 11:33 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/StudentController.php
> +        $ageData = $birthDay->diffInYears($today);
`Carbon`はミュータブルといって、内部の状態が変更できてしまうので、可能であれば`Carbonimmutable`を使って実装をお願いします！理由は次の記事を参考にしてみると理解できるかもです！
https://qiita.com/kbys-fumi/items/b923cdfb09c8f5c35fce

2024-04-30 11:33 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/StudentController.php
> +        $birthDay = $student->birth_date; /*メンバ変数birth_date*/
実装の詳細のコメントは削除いただきたいです！
ご自身の理解のために一時的に残すのは、問題ないです。しかし、その類のコメントが反映されてしまうと他の開発者の困惑を招くので最終提出では消しましょう！

```php
/*メンバ変数birth_date*/
```

2024-05-07 14:30 UTC, yamaha-win commented on app/Http/Controllers/Api/Manager/StudentController.php
> +        $birthDay = $student->birth_date; /*メンバ変数birth_date*/
削除しました

2024-05-07 14:31 UTC, yamaha-win commented on app/Http/Controllers/Api/Manager/StudentController.php
> +        $ageData = $birthDay->diffInYears($today);
Modelに算出させるようにしました
Carbonimmutable を使いました

2024-05-07 23:02 UTC, yukihiroLaravel requested changes
いくつか指摘しましたのでご確認願います！

2024-05-07 23:02 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/StudentController.php
> +        $age = $calcAge;
こちら、newせずとも
他のモデルのメソッドを使っていたところと同じように
下記のように静的なメソッドで書き換えられると思います！

$age = Student::calcAge($birthDay, $today);

2024-05-07 23:02 UTC, yukihiroLaravel commented on app/Model/Student.php
> +     * 年齢計算
PHP Doc を書きましょう！
こちらについては、下記動画で解説しています！
https://www.loom.com/share/83ae56a783454cf4bdca56b244dc3615?sid=fb001e5c-ff29-4839-9ef7-a9df26f419a0

2024-05-08 11:18 UTC, Hikaru-Giannis requested changes

2024-05-08 11:18 UTC, Hikaru-Giannis commented on app/Model/Student.php
> +    public static function calcAge($birthDay, $today)
$birthDayは引数で渡さずとも、Studentの内部プロパティで保持しているかと思いますので、そちらを参照するように修正をお願いします！

また、staticにするとStudentモデルで記述する恩恵を受けれなくなってしまうので、staticの利用はなるべく避けましょう。
メソッドの引数に生年月日以外の日付が渡されてしまうと、その生徒の年齢ではない出力が返されてしまい、意図していないメソッドの使われ方をされてしまう問題などがあります。

2024-05-08 11:18 UTC, Hikaru-Giannis commented on app/Model/Student.php
> +    public static function calcAge($birthDay, $today)
また、細かいですが、birth_dateからbirthDayに名称を変更されていますが、どのような意図がありましたでしょうか？

他の開発者はその2つに違いがあるのかと困惑に繋がるので、確認でした！

2024-05-11 06:32 UTC, yamaha-win reviewed
質問の返信をしました

2024-05-11 06:32 UTC, yamaha-win commented on app/Model/Student.php
> +     * 年齢計算
PHP Docを追加しました。

2024-05-11 06:32 UTC, yamaha-win commented on app/Http/Controllers/Api/Manager/StudentController.php
> +        $age = $calcAge;
ご指摘いただいた書き方で年齢を算出できました。

2024-05-11 06:32 UTC, yamaha-win commented on app/Model/Student.php
> +    public static function calcAge($birthDay, $today)
birth_dateは入力されている日付データとしての参照元で、
年齢については、誕生日という基準を境にして変わっていく要素なので、変数は１日単位を表すdayにすればいいと思いました。
なので、計算に用いる変数はdayがはいる単語で命名することにしました。

2024-05-12 01:40 UTC, Hikaru-Giannis commented on app/Model/Student.php
> +    }
多分指摘した箇所の解釈が間違っていそうですね！
一度、生成したstudentインスタンスに`birth_date`は保持しているので、次のようにして誕生日を参照することができます。そして、わざわざ変数に格納する必要はなさそうなので、そのまま値をreturnするとスマートに書けそうです。

そうなると、メソッドの第１引数は不要になりますよね！

```php
$age = $this->birth_date->diffInYears($today);
```

2024-05-12 01:46 UTC, Hikaru-Giannis requested changes
レビュー修正後は、動作確認されていますか？
我々はレビュー修正後、必然的に修正が必要になる点とかまでは指摘していないので、必ずご確認お願いしますね！

2024-05-12 02:35 UTC, yamaha-win reviewed
ご指摘を受けたとおりコードを変更し、
動作確認をして、受講生の詳細が表示できるようになりました。

2024-05-12 03:33 UTC, yamaha-win reviewed
消し忘れていた部分がありました。

2024-05-12 03:40 UTC, yamaha-win reviewed
Change return int

2024-05-13 11:16 UTC, yamaha-win commented on app/Model/Student.php
> +    }
$thisを使うとエラーになるので、
$studentを使用して書き換えました。

return $student->birth_date->diffInYears($today);

2024-05-18 05:23 UTC, Hikaru-Giannis commented on app/Model/Student.php
> +    }
エラーの内容を教えていただけますか？

staitc関数とそうでない関数の呼び出し方法や特性が違うので、その辺りを意識すると解消できると思います！staticでない場合は次の呼び出し方は非推奨と警告されるので、修正する必要があります。

```php
Student::calcAge
```

2024-05-18 06:27 UTC, yamaha-win commented on app/Model/Student.php
> +    }
"message" : "Cannot use $this as parameter"

2024-05-18 06:33 UTC, yamaha-win commented on app/Model/Student.php
> +    }
![error](https://github.com/yukihiroLaravel/juko_laravel/assets/150875405/8a4d2c93-1fb3-446e-b59d-80de39f665a4)

2024-05-18 08:24 UTC, yamaha-win commented on app/Model/Student.php
> +    }
静的メソッドからnewインスタンスに書き換え、
$thisを使って処理しようとしたところ、$todayでエラーになるようです。
![error](https://github.com/yukihiroLaravel/juko_laravel/assets/150875405/6452a748-9497-4f29-ad67-9242064a61b9)

2024-05-19 13:27 UTC, Hikaru-Giannis requested changes, later dismissed

2024-05-19 13:27 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/StudentController.php
> +        ]);
$studentをResourceファイルに渡す必要があるので、次のように呼び出す必要がある。

```php
return new StudentShowResource($student);
```

2024-05-19 13:27 UTC, Hikaru-Giannis commented on app/Http/Resources/Manager/StudentShowResource.php
> +        $age = $this->resource['ageData'];
連想配列ではなく、Studentインスタンスが渡される。

2024-05-21 02:13 UTC, yukihiroLaravel requested changes
念のため確認ですが、
これで動作確認などは問題ない認識でOKでしょうか？

また、少しコメントしましたのでご確認ください！

2024-05-21 02:13 UTC, yukihiroLaravel commented on app/Http/Resources/Manager/StudentShowResource.php
> +        $student = $this;
この１行は下記の理由でなしでいいと思います！

2024-05-21 02:13 UTC, yukihiroLaravel commented on app/Http/Resources/Manager/StudentShowResource.php
> +            'profile_image' => $student->profile_image,
$stundentのところを
すべて
$this
に変更しましょう！

2024-05-21 13:23 UTC, yamaha-win commented on app/Http/Resources/Manager/StudentShowResource.php
> +            'profile_image' => $student->profile_image,
$stundentから$thisに書き換えました

2024-05-21 13:24 UTC, yamaha-win commented on app/Http/Resources/Manager/StudentShowResource.php
> +        $student = $this;
この行を削除しました

2024-05-21 13:26 UTC, yamaha-win commented
> 念のため確認ですが、 これで動作確認などは問題ない認識でOKでしょうか？
> 
> また、少しコメントしましたのでご確認ください！

動作確認はOKです！

2024-05-22 00:47 UTC, yukihiroLaravel approved these changes
OKですので、マージしました！！
いろいろ苦労されたと思いますがお疲れ様でした🙇‍♂️

2024-05-22 00:49 UTC, merged