#jka-807 講師側（講師） 受講生詳細APIに現在年齢を追加
yukihiroLaravel/juko_laravel pull request #533
Opened 2024-04-30 12:36 UTC by sol6406

## Issue
- Closes #jka-807 
## 概要
-講師側（講師） 受講生詳細APIに現在年齢を追加
　
## 動作確認手順
- postmanにてGETを選択し下記のアドレスを入力する
- http://localhost:8080/api/v1/instructor/student/1
- ヘッダーに
- 　Referer　
http://localhost:3000
- 　Origin
http://localhost:3000
- 　X-XSRF-TOKEN
{{XSRF-TOKEN}}
- を入力する
- プレリクエストスクリプトに
``
 
を入力する
送信する
受講生の詳細に年齢が追加されているかの確認

## 考慮してほしいこと

## 確認してほしいこと

2024-05-01 13:09 UTC, yukihiroLaravel requested changes
修正事項

2024-05-01 13:09 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +       // dd($courseIds);
コメントアウト削除

2024-05-01 13:09 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +        $birthday = $student->birth_date;   //student_idからbirth_dateを抽出
コメントアウト削除

2024-05-01 13:09 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +        $now = Carbon::today();//今の日付のみを取得
$today?

2024-05-01 13:09 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +        $now = Carbon::today();//今の日付のみを取得
コメントアウト削除

2024-05-01 13:09 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +        $age = $birthday->diffInYears($now);//Carbon同士で差を計算
コメントアウト削除

2024-05-01 13:09 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Student/StudentController.php
> +>>>>>>> develop
ここは丸々変更しない方が良さそう

2024-05-11 05:12 UTC, yukihiroLaravel requested changes
いくつか指摘しましたのでご確認下さい！

2024-05-11 05:12 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +
ここの空行は不要そうですね

2024-05-11 05:12 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +         $birthDay = $student->birth_date;
こちら、井出さんも指摘されている通り
混乱しないよう、
$birthDateなどに統一した方がいいと思います！

2024-05-11 05:12 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +         $age = $age ->calcAge($birthDay, $today);
ー＞の前のスペースは不要ですね！

2024-05-11 05:12 UTC, yukihiroLaravel commented on app/Model/Instructor.php
> +use App\Model\Student;
ここは今回はいじるべきファイルではないかなと思いましたので
一旦削除しましょう！

2024-05-11 05:12 UTC, yukihiroLaravel commented on app/Model/Student.php
> +    public function calcAge($birthDay, $today)
ここの変数
$birthDay
も
$birthDate
に変更

2024-05-12 13:47 UTC, sol6406 commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +
削除しました

2024-05-12 13:49 UTC, sol6406 commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +         $birthDay = $student->birth_date;
$birthDateに統一しました

2024-05-12 13:49 UTC, sol6406 commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +         $age = $age ->calcAge($birthDay, $today);
空白削除しました

2024-05-12 13:51 UTC, sol6406 commented on app/Model/Instructor.php
> +use App\Model\Student;
7、8、9行目を削除しました

2024-05-12 13:53 UTC, sol6406 commented on app/Model/Student.php
> +    public function calcAge($birthDay, $today)
$birthDateに変更しました

2024-05-19 13:38 UTC, yukihiroLaravel requested changes
本日、Kouさん・井手さんとお話ししまして
GitHubに記載の書き方に変更することになりました！

少し方針が変わりすみませんがご確認・修正お願いいたします！

2024-05-19 13:38 UTC, yukihiroLaravel commented on app/Http/Resources/Instructor/StudentShowResource.php
> +        $age = $this->resource['age'];
２２行目も下記の書き方が
おそらくできるので
$age = $this->resource['age'];
この１行は丸々削除しましょう！

2024-05-19 13:38 UTC, yukihiroLaravel commented on app/Http/Resources/Instructor/StudentShowResource.php
> +            'age' => $age,
こちらこのように書き換えられるので
直接こちらで計算できるよう
書き換えましょう！

'age' => $student->calcAge(new CarbonImmutable());

2024-05-19 13:38 UTC, yukihiroLaravel commented on app/Model/Student.php
> +    public static function calcAge($student, $today)
下記の書き方にしたいので
static
を消し、次の書き方にしましょう

public function calcAge($today)

2024-05-19 13:38 UTC, yukihiroLaravel commented on app/Model/Student.php
> +        return $student->birth_date->diffInYears($today);
$this->birth_date->diffInYears($today);

2024-05-19 13:38 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +         $age = Student::calcAge($student, $today);
すみません！
いろいろ変更になりすみませんが、
Resourcesファイルに年齢の計算を丸々移動させた方が
すっきりするのでこの上記３行は丸々消しましょう🙇‍♂️

2024-05-19 13:38 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/StudentController.php
> +            'age' => $age,
'age' => $age,

下記に伴いこの１行も削除願います・・・！

2024-05-21 02:17 UTC, yukihiroLaravel requested changes
少しさらに追記しました！

2024-05-21 02:17 UTC, yukihiroLaravel commented on app/Http/Resources/Instructor/StudentShowResource.php
> +            'birth_date' => $student->birth_date->format('Y/m/d'),
$studentをすべて
$thisに変更しましょう！

2024-05-21 02:17 UTC, yukihiroLaravel commented on app/Http/Resources/Instructor/StudentShowResource.php
> +            'profile_image' => $student->profile_image,
$studentをすべて
$thisに変更しましょう！

2024-05-21 13:54 UTC, Hikaru-Giannis approved these changes

2024-05-22 11:56 UTC, Hikaru-Giannis approved these changes

2024-05-22 15:23 UTC, yukihiroLaravel approved these changes
マージしました！
おつかれさまでした！

2024-05-22 15:23 UTC, merged