jka-832 マネージャー側 講師-講座一覧APIの作成（あべ）
yukihiroLaravel/juko_laravel pull request #535
Opened 2024-05-01 14:46 UTC by abeai0

## task
-Closes JKA-832

## 概要
- マネージャー側 講師-講座一覧APIの作成

## 動作確認手順
- postmanでマネージャー権限のあるinstructorでログイン
- http://localhost:8080/api/v1/manager/instructor/2/course/index をGETで送信して
```
{
    "data": {
        "courses": [
            {
                "course_id": 2,
                "course_title": "Laravel入門講座",
                "couese_status": "public"
            },
            {
                "course_id": 6,
                "course_title": "Vue入門講座",
                "couese_status": "public"
            }
        ],
        "pagination": {
            "page": 1,
            "total": 2
        }
    }
}
```
が返ってくることを確認

## 考慮して欲しいこと
- 特にありません
## 確認してほしいこと
- 特にありません

2024-05-02 11:48 UTC, Hikaru-Giannis requested changes

2024-05-02 11:48 UTC, Hikaru-Giannis commented on app/Http/Resources/Manager/InstructorCourseIndexResource.php
> +     * @param Collection<\App\Model\Notification> $notifications
Notificationは関係ないので、修正をお願いします！

2024-05-02 11:48 UTC, Hikaru-Giannis commented on app/Http/Resources/Manager/InstructorCourseIndexResource.php
> +                "couese_status" => $course->status
レスポンスのレビュー漏れしていたら、申し訳ございませんが、他のレスポンス構造と一貫性を保つために次のようにお願いできますか？

```php
        return $courses->map(function (Course $course) {
            return [
                "course_id" => $course->id,
                "title" => $course->title,
                "status" => $course->status
            ];
        });
```

2024-05-02 12:57 UTC, abeai0 commented on app/Http/Resources/Manager/InstructorCourseIndexResource.php
> +     * @param Collection<\App\Model\Notification> $notifications
ありがとうございます、修正します。

2024-05-02 12:58 UTC, abeai0 commented on app/Http/Resources/Manager/InstructorCourseIndexResource.php
> +                "couese_status" => $course->status
ありがとうございます、修正します。

2024-05-04 02:46 UTC, Hikaru-Giannis approved these changes

2024-05-04 11:47 UTC, merged