JKA-744 topicブランチからdevelopブランチへのマージ（ohtomo）
yukihiroLaravel/juko_laravel pull request #536
Opened 2024-05-02 10:10 UTC by to-ohtomo

## issue
JKA-837

## 概要
JKA-744 お知らせ登録API作成 topicブランチからdevelopブランチへのマージ`依頼

## 動作確認手順
・postmanにて、
メソッド: POST、URL: http://localhost:8080/api/v1/manager/course/1/notification
に接続し、レスポンスが下記になることを確認しました。
{
    "result": true
}

・DataBaseのnotificationにデータが格納されることを確認しました。

## 考慮してほしいこと
なし

## 確認してほしいこと
なし

2024-05-09 13:21 UTC, Hikaru-Giannis requested changes

2024-05-09 13:21 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +use App\Http\Resources\Manager\NotificationUpdateResource;
こちらはコントローラーのどこでも参照していないのであれば、削除お願いします！

2024-05-09 13:21 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +use Illuminate\Http\Request;
こちらもコントローラーのどこでも参照していないのであれば、削除お願いします！

2024-05-09 13:21 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +     * お知らせ登録API
phpdocを他のメソッド同様に記述をお願いします！

2024-05-18 04:50 UTC, to-ohtomo commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +use App\Http\Resources\Manager\NotificationUpdateResource;
こちらを削除させていただきます。

2024-05-18 04:51 UTC, to-ohtomo commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +use Illuminate\Http\Request;
https://github.com/yukihiroLaravel/juko_laravel/pull/560

2024-05-18 04:51 UTC, to-ohtomo commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +     * お知らせ登録API
こちらを修正させていただきます。

2024-05-22 11:48 UTC, kou-tech approved these changes

2024-05-23 11:56 UTC, merged