JKA-801　受講生側のお知らせ詳細APIの作成子課題④　リクエストフォームの作成(オオハシ）
yukihiroLaravel/juko_laravel pull request #542
Opened 2024-05-05 14:09 UTC by kenta-oohashi

## 概要
- 受講生側のお知らせ詳細APIの作成子課題④　リクエストフォームの作成
## 動作確認手順
- http://localhost:8080/login
- http://localhost:8080/api/v1/notification/1 
## 確認していただきたいこと
- アクセスしたら確認してほしいことアクセスしたら、下記のように情報を取得できているか
 {
  "data": {
    "notification_id": 1,
    "title": "レッスン「変数とは？」閲覧について",
    "content": "10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。",
    "start_date": "2020-10-01",
    "end_date": "2020-10-10",
    "course": {
      "course_id": 1,
      "title": "プログラミング入門",
    }
  }
- 作成したNotificationShowRequestの中身が求められている内容になっているか
-  NotificationShowRequest作成に伴い、NotificationControllerのshowメソッドの一部を変更したが、変更点が問題ないか
## 考慮していただきたいこと
- 特ににありません

2024-05-06 05:25 UTC, Hikaru-Giannis requested changes

2024-05-06 05:25 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Student/NotificationController.php
> +    public function show(NotificationShowRequest $request, $notification_id)
作成したFormRequestファイルでルートに紐づけているidをマージしたので、第２引数は不要になったかと思います。
正確には、$requestから取得できるので取得する必要性がないということです。
そのため、コントローラーで参照している箇所も$requestからお知らせのidを取得するように修正をお願いします。

2024-05-06 14:27 UTC, kenta-oohashi commented on app/Http/Controllers/Api/Student/NotificationController.php
> +    public function show(NotificationShowRequest $request, $notification_id)
マージされる意味がイマイチ分からなかったのですが、そういう事なのですね！承知しました！

2024-05-06 14:30 UTC, kenta-oohashi commented
## 概要
- 受講生側のお知らせ詳細APIの作成子課題④　リクエストフォームの作成
## 動作確認手順
- http://localhost:8080/login
- http://localhost:8080/api/v1/notification/1 
## 確認していただきたいこと
- アクセスしたら確認してほしいことアクセスしたら、下記のように情報を取得できているか
 {
  "data": {
    "notification_id": 1,
    "title": "レッスン「変数とは？」閲覧について",
    "content": "10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。",
    "start_date": "2020-10-01",
    "end_date": "2020-10-10",
    "course": {
      "course_id": 1,
      "title": "プログラミング入門",
    }
  }
- 前回のプルリクエスト時のレビューにあった修正がなされているか
## 考慮していただきたいこと
- 特ににありません

2024-05-07 09:53 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Student/NotificationController.php
> +                'notification_id' => $request->notification_id,
間違えではないのですが、敢えてリクエストの値を参照する必要はないので、$notifaicationからidを参照いただけますか？

システム的には、リクエストの値はシステム起因ではなくユーザー起因の値のためでした。

2024-05-08 03:22 UTC, kenta-oohashi commented
## 概要
- 受講生側のお知らせ詳細APIの作成子課題④　リクエストフォームの作成
## 動作確認手順
- http://localhost:8080/login
- http://localhost:8080/api/v1/notification/1 
## 確認していただきたいこと
- アクセスしたら確認してほしいことアクセスしたら、下記のように情報を取得できているか
 {
  "data": {
    "notification_id": 1,
    "title": "レッスン「変数とは？」閲覧について",
    "content": "10月1日〜10日の間、レッスン「変数とは？」がメンテナンスにつき閲覧できなくなります。",
    "start_date": "2020-10-01",
    "end_date": "2020-10-10",
    "course": {
      "course_id": 1,
      "title": "プログラミング入門",
    }
  }
- 前回のプルリクエスト時のレビューのご指摘の修正が間違っていないか
## 考慮していただきたいこと
- 特ににありません

2024-05-08 11:42 UTC, Hikaru-Giannis approved these changes

2024-05-08 11:42 UTC, merged