jka841 マネージャー側 お知らせ 一括（選択）表示ステータス変更API ロジック（あべ）
yukihiroLaravel/juko_laravel pull request #545
Opened 2024-05-07 10:29 UTC by abeai0

## task
-Closes JKA-841

## 概要
- マネージャー側 お知らせ 一括（選択）表示ステータス変更API

## 動作確認手順
- postmanでマネージャー権限のあるinstructorでログイン
- http://localhost:8080/api/v1/manager/notification/status/all をPUTで送信し、[] が返ってくることを確認

## 考慮して欲しいこと
- 特にありません
## 確認してほしいこと
- pu

2024-05-08 11:41 UTC, Hikaru-Giannis requested changes

2024-05-08 11:41 UTC, Hikaru-Giannis commented on app/Http/Requests/Manager/NotificationPutTypeRequest.php
> +            'notifications.*' => ['int'],
リクエストされるのは、idのみの数値の配列のため、そのidに対してのバリデーションの実装は可能ですか？
特にnotificationsテーブルにidのレコードが存在しているかを可能であれば、チェックしてエラーとして返したいです！

2024-05-08 11:41 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        ]);
間違ってはいないのですが、他の処理が増えコードが肥大化すると、どの場合にレスポンスが返されるかを追跡するのが難しくなるので、次のように修正をお願いできますか？
そうすることで、正常パターンと異常パターンでどのようなレスポンスが返されるか少し直感的に把握しやすくなるかと思いました。

```php
        try {
            $notifications->update(['type' => $type]);
            return response()->json([
                'result' => true,
            ]);
        } catch (Exception $e) {
            return response()->json([
                'result' => false,
                'message' => $e->getMessage(),
            ], 500);
        }
```

2024-05-08 11:41 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        } catch (\Exception $e) {
Exceptionを敢えてエスケープして、生成する必要性はないので、明示的にインポートをお願いします！
型解析ツールなどの恩恵が受けれなくなったりすることがあるので、よほどじゃない限りはインポートしましょう！

2024-05-08 11:41 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        }
こちらは、明示的に数値に変換しないと更新されませんでしたか？

NotificationテーブルにsetTypeAttributeがあるので、不要とも考えたため確認でした！

2024-05-08 11:41 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        if (!empty(array_diff($notificationsInstructorIds, $instructorIds))) {
標準メソッドのemptyの利用はなるべく避けたいんですよね。

ご存知かもしれませんが、配列以外でも判定するのに使うことができます。
https://qiita.com/shinichi-takii/items/00aed26f96cf6bb3fe62

よしなに判定してくれて便利な一方で、empty()によるバグを多く見てきました。

なので、次のどれかで修正をお願いしたいです！
- is_arrayと組み合わせて使う
- === []
- コレクションにして、isEmpty()

2024-05-09 13:17 UTC, kou-tech requested changes

2024-05-09 13:17 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        $notifications = Notification::whereIn('id', $request->notifications);
後述してある次のコードの直前に記述すると変数のスコープの視認性が多少良くなるかと思います。

```php
        $notificationsInstructorIds = $notifications->pluck('instructor_id')->toArray();
```

また、`whereIn`で処理を停止する必要性はなく、get()でデータの取得までしてしまって問題がないかと思ったのですが、何か意図がありましたでしょうか？

```php
        $notifications = Notification::whereIn('id', $request->notifications)->get();
```

2024-05-09 13:17 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        }
他の例外処理同様にログでエラーの出力をするようにお願いします！

2024-05-09 13:17 UTC, Hikaru-Giannis commented on app/Http/Requests/Manager/NotificationPutTypeRequest.php
> +        }
下のルール追加だけで、問題がないような気がしたのですがいかがでしょうか？
不要であれば、インポート箇所含めて削除お願いします。

```php
            'notifications.*' => ['integer', 'exists:notifications,id,deleted_at,NULL'],
```

2024-05-11 01:42 UTC, Hikaru-Giannis approved these changes

2024-05-12 01:13 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +            Log::error($e);
この2つが明示的なインポートがされていないので、適切な例外処理が実行されないので、修正をお願いします！

2024-05-12 10:29 UTC, abeai0 commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        ]);
ありがとうございます、修正します。

2024-05-12 10:29 UTC, abeai0 commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        } catch (\Exception $e) {
vscodeの補完機能でエスケープされていて深く考えずにそのまま使っていました。
ありがとうございます、修正します。

2024-05-12 10:29 UTC, abeai0 commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        }
最初はif文を入れていなかったのですが、update処理の時にエラーが出てしまったので、入れました。
try catchの中でeachでNotificationをfillとsaveで更新するよう書き換えてみました。

2024-05-12 10:29 UTC, abeai0 commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        if (!empty(array_diff($notificationsInstructorIds, $instructorIds))) {
empty、is_nullなどなんとなくで使ってしまっていました、ありがとうございます。
一番わかりやすかった===[]に修正します。

2024-05-12 10:29 UTC, abeai0 commented on app/Http/Requests/Manager/NotificationPutTypeRequest.php
> +            'notifications.*' => ['int'],
ありがとうございます、修正してみます！

2024-05-12 10:29 UTC, abeai0 commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        $notifications = Notification::whereIn('id', $request->notifications);
whereInで止めていたのはget()でデータ取得するとupdateで何かエラーが出ていたためだった気がしますが、今はfillを使用していて、特に問題ないので、修正します！

2024-05-12 10:29 UTC, abeai0 commented on app/Http/Requests/Manager/NotificationPutTypeRequest.php
> +        }
ifの部分は削除し忘れでした、すみません、修正します！

```
 'type' => ['required',  new NotificationUpdateStatusRule()],
 'notifications' => ['required', 'array'],
```
の部分も不要ということでしょうか？

2024-05-12 10:29 UTC, abeai0 commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        }
修正しました

2024-05-12 10:29 UTC, abeai0 commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +            Log::error($e);
ありがとうございます、修正します

2024-05-13 11:08 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
こちらtry~catchがあるもののトランザクションが反映されていなかったので、反映するようにお願いします！

理由としては複数レコードの更新が想定されるものの、ループ処理中に障害等が起きるとデータの不整合が起こりうる可能性があるためでした。

2024-05-13 16:43 UTC, abeai0 commented on app/Http/Controllers/Api/Manager/NotificationController.php
ありがとうございます、修正します

2024-05-14 13:46 UTC, Hikaru-Giannis approved these changes

2024-05-14 13:46 UTC, merged