JKA-806（講師側 ダッシュボード 今月のレッスン・チャプター完了数 取得API）ロジック実装（西田　修）
yukihiroLaravel/juko_laravel pull request #546
Opened 2024-05-08 13:29 UTC by osmnishida

## 概要
 講師側ダッシュボード今月のレッスン・チャプタ完了数取得APIーロジック実装

## 動作確認方法
以下はPostmanでの操作
- Headersにアクセス元のURLを設定  
   Referer → http://localhost:3000/  
   Origin → http://localhost:3000/
- http://localhost:8080/api/v1/instructor/course/1/attendance/status/this-month　にGET送信
- 今月のレッスン完了数（completed_lessons_count）及びチャプター完了数（completed_chapters_count）が、返ってきているかを確認

## 考慮してほしいこと
- 特になし

2024-05-09 12:56 UTC, Hikaru-Giannis requested changes

2024-05-09 12:56 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                return $lessonAttendance->status === 'completed_attendance' && $lessonAttendance->updated_at->isCurrentMonth();
'completed_attendance'も定数を参照しましょう！

2024-05-09 12:56 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +    public function showStatusThisMonth(AttendanceShowRequest $request): JsonResponse
AttendanceShowRequestは一時的に参照している認識であっていますか？

2024-05-11 01:05 UTC, osmnishida commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                return $lessonAttendance->status === 'completed_attendance' && $lessonAttendance->updated_at->isCurrentMonth();
モデルのLessonAttendance.phpに定数として設定している'STATUS_COMPLETED_ATTENDANCE'を参照するよう修正しました。

2024-05-11 01:05 UTC, osmnishida commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +    public function showStatusThisMonth(AttendanceShowRequest $request): JsonResponse
showStatusThisMonthが呼び出されたときだけの一時的に参照しているという認識です。

2024-05-11 07:45 UTC, Hikaru-Giannis approved these changes

2024-05-11 07:47 UTC, merged