JKA-838 講師側お知らせ削除API ロジック作成（小林）
yukihiroLaravel/juko_laravel pull request #548
Opened 2024-05-09 00:15 UTC by Celadon67

## issue
- https://gut-familie.atlassian.net/browse/JKA-838
## 概要
- 講師側 お知らせ 一括（選択）削除API作成　子課題
  ロジック作成
## 動作確認手順
- DELETEリクエストで　http://localhost:8080/api/v1/instructor/notification
  を実行すると以下の返答が返ってきた

```
{
    "result": true
}
```

## 考慮してほしいこと
- 今回は特にありません。
## 確認してほしいこと
- 今回は特にありません。

2024-05-09 06:18 UTC, yukihiroLaravel requested changes
いくつか指摘させていただきました！
ご確認お願いします！

2024-05-09 06:18 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +    * お知らせ全削除
もともと全削除でしたが
分かりやすく
名前を今は「選択」削除にしましたので
選択削除に変更お願いします！

2024-05-09 06:18 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        $user = Auth::guard('instructor')->user();
今のままですと
notificationを作った本人でない場合、削除できないですが
エラーが出ずに、削除できないだけで終わってしまい
何が原因で失敗したのかわからないので、
if文を用いた認証を書き、
さらにその中でresultがfalseになる
エラーを返すパターンも作成しましょう。

2024-05-09 06:18 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        return response()->json(['result' => true]);
他のところを見てもらうと下記のような書き方なので
変更しましょう！
```
            return response()->json([
                'result' => true,
            ]);
```

2024-05-09 06:18 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +                ->delete();
上記に伴いこちらの記述方法も変わってくるかと思います

2024-05-09 07:05 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +    * お知らせ全削除
変更しました。

2024-05-09 07:14 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        return response()->json(['result' => true]);
修正しました。

2024-05-09 07:14 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +                ->delete();
上記に伴い変更させました。

2024-05-09 07:17 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        $user = Auth::guard('instructor')->user();
①削除対象のお知らせがログインユーザーのものかどうかを確認
②削除対象のお知らせが存在しない、またはログインユーザーと一致しない場合はエラーを返す
③削除対象のお知らせが存在し、かつログインユーザーと一致する場合は削除を実行
の考え方でコード変更しました。

2024-05-09 10:20 UTC, yukihiroLaravel requested changes
いくつかコメントしました！

2024-05-09 10:20 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +                'message' => 'Failed to delete notifications. Either the notifications do not exist or you are not authorized to delete them.',
~ or ~
のようなエラーの出し方だと
エラーの原因特定がやりにくくなるので、ここでは
エラーメッセージにdo not exit などの文言は不要になると思います。

多分、
invalid notification_id.
などの文言で十分かな？と思います。

2024-05-09 10:20 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +                    ->delete();
１１６行目と同じ内容で検索してしまっているので無駄はなくしましょう！

2024-05-09 10:20 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +                        ->get();
他の部分と統一性を持たせるために
if文で １つ１つのnotificationのinstructor_idと、$user->idの照合を掛けるのをまず
行った方がいいと思いました。

2024-05-09 12:31 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +                'message' => 'Failed to delete notifications. Either the notifications do not exist or you are not authorized to delete them.',
修正しました。

2024-05-09 12:36 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +                    ->delete();
削除しました。

2024-05-09 12:44 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +                        ->get();
修正いたしました。

2024-05-09 16:32 UTC, Hikaru-Giannis requested changes

2024-05-09 16:32 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        });
同じ変数名の格納は困惑を招くので避けた方が良いです。
そもそも同じ変数名だが処理の前後で変わるのであれば、バグの一因になることが多々あります。

2024-05-09 16:32 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        $notifications->each->delete();
こちらはeachの記述の必須でしたか？

2024-05-10 02:25 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        $notifications->each->delete();
削除しました。

2024-05-10 02:31 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        });
修正しました。

2024-05-11 07:25 UTC, Hikaru-Giannis requested changes

2024-05-11 07:25 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        }
処理は間違っていないのですが、他の開発者がコードを見た時に理解するという面では大変そうな雰囲気がありますよね。
好みも含みますが、次のようなコレクションメソッドを使用しつつ、コメントで補足するとどうでしょうか？

```php
        if ($notifications->contains(function (Notification $notification) use ($user) {
            return $notification->instructor_id !== $user->id;
        })) {
            // 認証者と一致しないお知らせが含まれている場合はエラー
            return response()->json([
                'result' => false,
                'message' => 'Forbidden, not allowed to delete notifications.',
            ], 403);
        }
```

2024-05-11 07:25 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        ->delete();
お知らせは既に取得しているので、再度DBにアクセスする必要性はないかと思います！

2024-05-11 08:19 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        ->delete();
上記コメントで、　`$notifications->each->delete();`　は削除しましたので、代替として、　`Notification::destroy($filteredNotifications->pluck('id')->toArray());`　としました。

2024-05-11 08:55 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        }
コメントで補足しました。

2024-05-12 01:50 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        ->delete();
@Celadon67 
再度DBにアクセスするは、修正されていないのでご確認お願いします！
分からないことがあれば、また質問してください。

2024-05-13 13:34 UTC, Hikaru-Giannis commented
- `viewed_once_notifications`のレコードを削除
- トランザクションを導入

2024-05-15 13:20 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +                DB::table('viewed_once_notifications')->where('notification_id', $notification->id)->delete();
現状システム全体として、一貫して`Eloquent`を介してデータベースへの操作を行っているので、こちらも同様に`Eloquent`でご対応いただけますか？

複雑なSQL文などを理由に、クエリビルダで書く時もあるので間違いではないのですが、現状はEloquentで書くようにお願いいたします！モデルがない場合、モデルの作成からお願いいたします🙇‍♂️

2024-05-16 07:18 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +                DB::table('viewed_once_notifications')->where('notification_id', $notification->id)->delete();
モデルがないため加えました。それに伴いコントローラー、Notificationモデルも変更いたしました。

2024-05-16 15:36 UTC, Hikaru-Giannis requested changes
viewedOnceNotificationsのSeederを一つで構いませんので、作成していただくようにお願いします！

2024-05-16 15:36 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            });
これ以前共有したQiitaの記事の通り、次の記述でデータベースのレイヤーで一括削除が実行できます。
https://qiita.com/atkzw3/items/c4e4a5c0f3a866b9b95a 

```php
            Notification::whereIn('id', $notificationIds)->delete();
```

そのため、次の手順で削除するのがパフォーマンスとして、利点がありそうなので、修正いただけますか？
1. viewedOnceNotificationsテーブルのレコードを一括削除
2. notificationsテーブルのレコードを一括削除

2024-05-17 11:44 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            });
viewedOnceNotificationsのSeederを作成し、一括削除のコードに修正いたしました。

2024-05-18 05:08 UTC, Hikaru-Giannis requested changes

2024-05-18 05:08 UTC, Hikaru-Giannis commented on database/seeds/ViewedOnceNotificationSeeder.php
Seederを再実行すると次のエラーが出力されるので、ご確認いただけますか？

```txt
 Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails
```

2024-05-18 05:08 UTC, Hikaru-Giannis commented on database/seeds/ViewedOnceNotificationSeeder.php
不整合データは動作確認のノイズとなりやすいので、避けたいです！
お知らせの既読状態を管理しているのは、`notifications`テーブルの`type`が`once`の時だけです。

なので、`notification_id=2`と`student_id=2`のレコードを一件だけインサートするシーダーでお願いいたします！

2024-05-18 05:08 UTC, Hikaru-Giannis commented on database/migrations/2023_09_03_013745_create_viewed_once_notifications_table.php
> +            $table->timestamps();
こちら修正前後で列の型が変わってしまっているのは、意図的ですか？
timestampだと次の懸念があり、他の実装で意図せずtimestampを使ってしまっていますが、なるべくdatetime型でお願いしたいです！
https://zenn.dev/kenghaya/articles/89bc9a6e9e8381

2024-05-18 11:38 UTC, Celadon67 commented on database/seeds/ViewedOnceNotificationSeeder.php
修正しました。

2024-05-18 11:39 UTC, Celadon67 commented on database/migrations/2023_09_03_013745_create_viewed_once_notifications_table.php
> +            $table->timestamps();
修正しました。

2024-05-19 11:57 UTC, Hikaru-Giannis requested changes

2024-05-19 11:57 UTC, Hikaru-Giannis commented on composer.json
> +            "Database\\Seeders\\": "database/seeders/"
おそらく新規に作成したSeederが動作しなかった対応だと思いますが、composerのキャッシュの問題だと思われるので、こちらは修正を取り消していただき、次のコマンドでご自身のcomposerを更新しましょう！

```shell
$ composer dump-autoload
```

2024-05-19 12:47 UTC, Celadon67 commented on composer.json
> +            "Database\\Seeders\\": "database/seeders/"
修正を取り消して変更がなくなりました。

2024-05-20 18:07 UTC, Hikaru-Giannis approved these changes

2024-05-20 18:07 UTC, merged