講師側 お知らせ 一括（選択）表示ステータス変更API作成 ロジックの作成(近藤佑哉)
yukihiroLaravel/juko_laravel pull request #552
Opened 2024-05-13 12:31 UTC by yuyakondo333

## task
- Closes JKA-840
## 概要
- 講師側 お知らせ 一括（選択）表示ステータス変更API作成 ロジックの作成
## 動作確認
- postmanでマネージャー権限のあるinstructorでログイン
- http://localhost:8080/api/v1/manager/notification/type/always の Body に
```
{
    "type" : "once",
    "notifications" : [1,4]
}
```
## 質問

1.どの機能の実装/改修をしているのか
講師側 お知らせ 一括（選択）表示ステータス変更API作成 ロジックの作成

2.どのような現象が起きているのか
動作確認をしたところ以下の画像のエラーが返ってきました。
解像度が低くて申し訳ございませんが、ご教授お願い致します。
![スクリーンショット 2024-05-12 13 47 59](https://github.com/yukihiroLaravel/juko_laravel/assets/150170336/c37505f2-3382-45bb-87fd-7617ff327c9e)
![スクリーンショット 2024-05-12 13 48 23](https://github.com/yukihiroLaravel/juko_laravel/assets/150170336/08cf8e09-92aa-44ac-bfbf-62c4b713e584)

3.どのような原因であると推測/仮定しているのか

4.どのように調査/修正を試みたが解決しなかったのか
動作確認をしたところ以下の画像のエラーが返ってきました。

解像度が低くて申し訳ございませんが、ご教授お願い致します。

2024-05-14 07:17 UTC, yuyakondo333 commented
## 質問
- どの機能の実装/改修をしているのか
講師側 お知らせ 一括（選択）表示ステータス変更API作成 ロジックの作成

- どのような現象が起きているのか
アクセス権限の確認で$notifications と $notificationsInstructorIds が同じではない場合にfalseを返すコードを記述したのですが、同じIDでもfalseが返ってくるようになってしまいます。
![スクリーンショット 2024-05-14 16 10 17](https://github.com/yukihiroLaravel/juko_laravel/assets/150170336/b7c65c70-4596-4464-83cb-dae1ae6bd47a)

- どのような原因であると推測/仮定しているのか
$notificationsが配列で返ってきてないことが原因であると考えています。

- どのように調査/修正を試みたが解決しなかったのか
dd($notifications, $notificationsInstructorIds)でIDが同じことを確認したのですが、falseが返ってきました。
![スクリーンショット 2024-05-14 16 15 52](https://github.com/yukihiroLaravel/juko_laravel/assets/150170336/7f021734-c8e0-4fbb-b190-401a294505f6)

ご教授お願い致します。

2024-05-14 13:31 UTC, Hikaru-Giannis requested changes

2024-05-14 13:31 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            });
更新に必要なのは`type`だけですよね。
`$request`を`use`してしまうと、様々なプロパティを参照することができてしまい、関数型スタイルの利点が消えてしまうので、`type`のみ`use`するようにしましょう！
一度変数に格納する必要があるかもしれません。

2024-05-14 13:31 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            ]);
Commitされていないのですが、データベース上のデータも更新されているところまで動作確認までされていましたでしょうか？

2024-05-14 13:31 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            }
テーブルに存在しないケースは、Requestファイルで担保されているので不要ではありませんか？

2024-05-14 13:31 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            }
foreachの実装はなるべく避けたいです。
理由としては汎用的なループ処理は、そのループ処理の中で様々な副作用を生むコードを書くことができ、保守性に欠けるからです。
現状は他の開発者でも保守できることが、利点が大きいので、コレクションメソッドを利用して、関数型スタイルで修正してみてほしいです！

2024-05-14 13:31 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            }
次の等式は値と配列を比較しているので、不適切ではありませんか？
`$instructorId !== $notificationsInstructorIds`

2024-05-14 13:31 UTC, Hikaru-Giannis commented on app/Model/Notification.php
> +    }
参照しないのであれば削除をお願いします！

2024-05-14 13:31 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +// use
不要な改行、コメントは削除お願いします！

2024-05-14 17:13 UTC, yuyakondo333 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +// use
削除しました。

2024-05-14 17:13 UTC, yuyakondo333 commented on app/Model/Notification.php
> +    }
削除しました。

2024-05-14 17:13 UTC, yuyakondo333 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            }
おっしゃる通り不要でした。削除します。

2024-05-14 17:43 UTC, yuyakondo333 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            });
一度変数に格納して修正しました。

2024-05-14 17:44 UTC, yuyakondo333 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            ]);
失礼しました。
`DB::commit();`
こちらを-`>save();`の後に追加しました。

2024-05-15 12:49 UTC, yuyakondo333 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            }
関数型スタイルで修正しました。
`$instructorId !== $notification->instructor_id`
以上のコードに修正しまして、値と値の比較をするようにしました。

2024-05-15 13:12 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        });
114行目の`return`は無名関数の`return`となるので、機能していない。

コレクションメソッドの中に`contains`というメソッドがあり、お知らせの講師と認証者の講師のIDが一致しないものが含まれているかを論理値で返すことができるので、そのアプローチで修正を依頼済み。(2024/05/15)

2024-05-15 13:46 UTC, yuyakondo333 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        });
containsメソッドを利用しまして修正後、動作確認しました。

2024-05-16 15:19 UTC, kou-tech approved these changes

2024-05-17 05:59 UTC, merged