JKA-870 講師側 お知らせ削除API作成~③ロジックの作成
yukihiroLaravel/juko_laravel pull request #561
Opened 2024-05-18 15:08 UTC by kenta-oohashi

## 概要
- 講師側お知らせ削除API作成のロジックの作成
## 現状
- ポストマンでエラーが起きている
## ご教授いただきたいこと
- ①自分の考えているロジックがそもそもあっているか
前提
DBのnotificationsを見ると、notification_id欄には、courese_idとinsturctor_idが入っているので、その二つのidの情報を取得する必要があると考えています。

deleteに必要だと考えている内容。

1.insutructor_idを調べる

2.先ほど取得したinstructor_idを使い、courseモデルから、その講師が担当しているcourse_idを手に入れる。

3.NotificationモデルからCourse_idと一致するnotification_idを取得する

4.$notificationからとったinstructor_idと$instuructor_idが一致せず、かつ、notificationから取得したcourse_idがcouseiIdsの中にない場合は、403でエラーを返す。

その条件に当てはまらなければ、notificationを削除し、レスポンスでtrueを返す
-  ②エラーを解消するためにcodeのどのあたりを直せばいいかアドバイスを頂きたいです
-  ③Couseモデルがinsutructorモデルとリレーションされていなかったので、hasmanyで記述したが、それは必要か

2024-05-19 12:06 UTC, Hikaru-Giannis commented
> notification_id欄には、courese_idとinsturctor_idが入っているので、その二つのidの情報を取得する必要があると考えています

上の説明の詳細をお伺いしたいです！削除するレコードは`notification_id`から特定できそうですよね。
そのレコードを削除して問題がないかは、そのレコードの`insturctor_id`と認証者の`insturctor_id`が一致しているかどうかを検証すると良いと思います！

2024-05-21 05:28 UTC, kenta-oohashi commented
## 概要
- 講師側お知らせ削除API作成のロジックの作成
## 動作確認
- http://localhost:8080/login/instructor にて、POSTリクエストで、bodyのキーにemailとpasswordを。値にtest_instructor@example.comとpasswordをそれぞれ入力し、instructor1にログイン
## 確認していただきたいこと
- DELETEリクエストでhttp://localhost:8080/api/v1/instructor/notification/1 を送信し、
'result' => true,
            'message' => 'Notification deleted successfully.'と表示されるか
- ログインをinstructor1のまま、DELETEリクエストでhttp://localhost:8080/api/v1/instructor/notification/2 で送信したときに、
'result' => false,
                'message' => 'Notification is not associated with the instructor\'s course.',と表示されるか
- コンフリクトが解消されているか
## 考慮していただきたいこと
- 特にないです

2024-05-21 13:41 UTC, Hikaru-Giannis commented on app/Model/Course.php
この実装はどのような意図があって、コミットされましたか？

2024-05-21 13:43 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
お知らせを削除するときに、viewed_once_notificationsテーブルでお知らせを一度だけ表示するケースにおける既読状態を管理しています。

その場合、viewed_once_notificationsテーブルはnotification_idを外部キーを保持しているので、先にviewed_once_notificationsのレコードがある場合は既読レコードを削除してから、お知らせを削除するように修正をお願いいたします！

2024-05-25 21:53 UTC, kenta-oohashi commented
## 概要
- 講師側お知らせ削除API作成のロジックの作成
## 現状
- ポストマンでエラーが起きている
## ご教授いただきたいこと
- クラスを追加したらオートローダーの再構築などもすると調べてわかったのですが、エラーが解消できず、Codeを見て頂き、アドバイスを頂きたいです。よろしくお願いいたします。

2024-05-25 21:53 UTC, kenta-oohashi commented on app/Http/Controllers/Api/Instructor/NotificationController.php
承知いたしました！

2024-05-25 21:53 UTC, kenta-oohashi commented on app/Model/Course.php
間違えてコミットしてしまいました。以後気を付けます

2024-05-27 13:35 UTC, kenta-oohashi commented
## 概要
- 講師側お知らせ削除API作成のロジックの作成
## 動作確認
- http://localhost:8080/login/instructor にて、POSTリクエストで、bodyのキーにemailとpasswordを。値にtest_instructor@example.comとpasswordをそれぞれ入力し、instructor1にログイン
## 確認していただきたいこと
- DELETEリクエストでhttp://localhost:8080/api/v1/instructor/notification/1 を送信し、
'result' => true,
            'message' => 'Notification deleted successfully.'と表示されるか
- ログインをinstructor1のまま、DELETEリクエストでhttp://localhost:8080/api/v1/instructor/notification/2 で送信したときに、
'result' => false,
                'message' => 'Notification is not associated with the instructor\'s course.',と表示されるか
- 前回のレビューで頂いた、先にviewed_once_notificationsのレコードがある場合は既読レコードを削除してから、お知らせを削除するようになっているか
## 考慮していただきたいこと
- 特にないです

2024-05-28 13:14 UTC, Hikaru-Giannis requested changes

2024-05-28 13:14 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            ViewedOnceNotification::where('notification_id', $notification_id)->firstOrFail()->delete();
`firstOrFail`は必要でしょうか？
その場合、どのような問題が起こりそうか考えてみましょう！

2024-05-28 13:14 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        } catch (\Exception $e) {
エスケープではなく、意図的にインポートしましょう！

2024-05-28 13:14 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +                'error' => $e->getMessage()
他の実装との一貫性を持たせるべく、`result`だけにしましょう！
`$e->getMessage()`は場合によっては、情報リークになりかねないので注意です！

2024-05-28 13:14 UTC, Hikaru-Giannis commented on app/Model/Course.php
> +    }
今回の機能の実装で、こちらの記述は必要でしたでしょうか？

2024-05-28 14:22 UTC, kenta-oohashi commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            ViewedOnceNotification::where('notification_id', $notification_id)->firstOrFail()->delete();
すみません、エラーを直すときに試行錯誤していて、消したつもりでしたが、残したままでしたので、削除しました。
firstOrFailがある時とないときの違いを調べなおしてみました！

2024-05-28 14:22 UTC, kenta-oohashi commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +        } catch (\Exception $e) {
承知しました！

2024-05-28 14:26 UTC, kenta-oohashi commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +                'error' => $e->getMessage()
承知しました。139行目と140行目は削除いたしました。
なるほど、$e->getMessage()は、セキュリティー上のもんだいがあるのですね。気を付けます！

2024-05-28 14:35 UTC, kenta-oohashi commented
## 概要
- 講師側お知らせ削除API作成のロジックの作成
## 動作確認
- http://localhost:8080/login/instructor にて、POSTリクエストで、bodyのキーにemailとpasswordを。値にtest_instructor@example.comとpasswordをそれぞれ入力し、instructor1にログイン
## 確認していただきたいこと
- DELETEリクエストでhttp://localhost:8080/api/v1/instructor/notification/1 を送信し、
'result' => true,
            'message' => 'Notification deleted successfully.'と表示されるか
- ログインをinstructor1のまま、DELETEリクエストでhttp://localhost:8080/api/v1/instructor/notification/2 で送信したときに、
'result' => false,
                'message' => 'Notification is not associated with the instructor\'s course.',と表示されるか
- 前回のレビューで頂いたものが解決されているか
## 考慮していただきたいこと
- レビューで頂いた、エスケープではなく、意図的にインポートしましょう！の箇所を自分で調べてみましたが、変更内容が合っているかわからないです。もしあっていなければもう少し、詳細に教えて頂けると助かります。よろしくお願いいたします。

2024-05-28 14:42 UTC, kenta-oohashi commented on app/Model/Course.php
> +    }
以前courseも使うのかもと思いcodeを書いていた時に、作成したものでした。
今回はcourseは使わないので、このリレーションは削除しておきました。

2024-05-29 12:10 UTC, Hikaru-Giannis requested changes

2024-05-29 12:10 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +use App\Model\Instructor;
こちら参照しないのであれば、削除しましょう！

2024-05-29 12:10 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +                'message' => 'Notification deleted successfully.'
このメッセージも削除して問題ないです！

2024-05-29 14:26 UTC, kenta-oohashi commented
## 概要
- 講師側お知らせ削除API作成のロジックの作成
## 動作確認
- http://localhost:8080/login/instructor にて、POSTリクエストで、bodyのキーにemailとpasswordを。値にtest_instructor2@example.comとpasswordをそれぞれ入力し、instructor2にログイン
## 確認していただきたいこと
- DELETEリクエストでhttp://localhost:8080/api/v1/instructor/notification/2 を送信し、
'result' => true,と表示されるか
- アドマイナー上で、viewedonce_notificationsテーブルのid1(notificatino_id2に関係するもの)に一致するものが削除され、かつ、notificationsテーブルのid2番が削除されているか
- ログインをinstructor２のまま、DELETEリクエストでhttp://localhost:8080/api/v1/instructor/notification/1 で送信したときに、
'result' => false,
                'message' => 'Notification is not associated with the instructor\'s course.',と表示されるか
- 前回のレビューで頂いたものが解決されているか
## 考慮していただきたいこと
-一度プッシュした後に、訂正しきれていない箇所があったので、修正し、再度プッシュしたため、[1ffcdd3](https://github.com/yukihiroLaravel/juko_laravel/pull/561/commits/1ffcdd306c9bb14fa737e70b667bd3f06520f7db)と[3481a7b](https://github.com/yukihiroLaravel/juko_laravel/pull/561/commits/3481a7be84a8170711ca657877f07ea9622c79c3)が存在します。チェックしづらくしてしまい、申し訳ございません。

2024-05-30 13:08 UTC, Hikaru-Giannis approved these changes

2024-05-30 13:08 UTC, merged