JKA-838 講師側お知らせ削除API フォームリクエストの作成（小林）
yukihiroLaravel/juko_laravel pull request #562
Opened 2024-05-20 01:39 UTC by Celadon67

2024-05-20 10:58 UTC, yukihiroLaravel requested changes
リクエストファイルについてコメントさせていただきました！

2024-05-20 10:58 UTC, yukihiroLaravel commented on app/Http/Requests/Instructor/NotificationBulkDeleteRequest.php
> +            'notifications.*' => ['integer', 'exists:notifications,id'],
２８行目は
空配列だとNGかなと思うので
requiredと
,deleted_at,NULL
も必要かと思います！

2024-05-20 12:12 UTC, Celadon67 commented on app/Http/Requests/Instructor/NotificationBulkDeleteRequest.php
> +            'notifications.*' => ['integer', 'exists:notifications,id'],
修正いたしました。

2024-05-22 13:01 UTC, kou-tech approved these changes

2024-05-22 15:22 UTC, yukihiroLaravel approved these changes
マージしました！おつかれさまでした！！

2024-05-22 15:22 UTC, merged