マネージャー側 お知らせ 一括（選択）削除API作成 ロジックの作成 (近藤)
yukihiroLaravel/juko_laravel pull request #566
Opened 2024-05-22 17:08 UTC by yuyakondo333

## task
- [https://gut-familie.atlassian.net/browse/JKA-839]()
## 概要
- マネージャー側 お知らせ 一括（選択）削除API作成 ロジックの作成
## 動作確認
- `http://localhost:8080/login/instructor` インストラクターでログイン
- `http://localhost:8080/api/v1/instructor/notification/index` お知らせ一覧でお知らせ情報があることを確認
- `http://localhost:8080/api/v1/manager/notification` DELETEメソッドで実行すると以下が返ってきた
```
{
    "result": true
}
```
- `http://localhost:8080/api/v1/instructor/notification/index` お知らせ一覧を確認するとお知らせがなくなっていることを確認

## 考慮して欲しいこと
- リクエストファイルを作成していないのでバリデーションエラーは出ないようになっております。
- コンフリクトが発生しないようにする為、小林さんのコードを元に作成しまして新しくモデルとシーダーを作っております。
## 確認して欲しいこと
- 特にありません。

2024-05-23 12:02 UTC, Hikaru-Giannis requested changes

2024-05-23 12:02 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        // dd($notifications);
デバッグコードは削除お願いします！

2024-05-23 12:02 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +            Notification::whereIn('id', $notifications)->delete();
こちら動作確認されて問題なかった感じですかね...？
確認した理由としては、`$notifications`はレコードのコレクションクラスで、idの数値配列ではない認識だったからです。
SQL文として直感的ではないので、お知らせのidの数値配列を渡すように修正をお願いしてよろしいでしょうか？

2024-05-23 16:05 UTC, yuyakondo333 commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +            Notification::whereIn('id', $notifications)->delete();
動作確認をして問題はありませんでした。
`$notificationIds = $notifications->pluck('id')->toArray();`
こちらを追記して$notificationIds 配列を $notifications コレクションから pluck メソッドを使って抽出するように修正しました。

2024-05-24 22:37 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        $notificationIds = $notifications->pluck('id')->toArray();
後述で`$notifications`を参照しないのであれば、一度変数に入れる必要性はないかと思うのですがいかがでしょうか？
下のようなイメージです！動作確認していないです。

```php
$notificationIds = Notification::whereIn('id', $request->notifications)->pluck('id')->toArray()
```

2024-05-25 02:39 UTC, yuyakondo333 commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +        // dd($notifications);
削除しました。

2024-05-26 13:34 UTC, merged