JKA-838 講師側お知らせ削除API topicブランチからdevelopへのプルリク（小林）
yukihiroLaravel/juko_laravel pull request #567
Opened 2024-05-22 20:07 UTC by Celadon67

## issue
-https://gut-familie.atlassian.net/browse/JKA-838
## 概要
- 講師側 お知らせ 一括（選択）削除API作成　子課題
   topicブランチからdevelopへのプルリク
## 動作確認手順
- topicブランチからdevelopへのプルリク　を行い、動作確認したところ問題ありませんでした。

## 考慮してほしいこと
- 今回は特にありません。
## 確認してほしいこと
- 今回は特にありません。

2024-05-23 02:12 UTC, yukihiroLaravel requested changes
今更ながら、
１点指摘させていただきましたので
ご確認お願いいたします！

2024-05-23 02:12 UTC, yukihiroLaravel commented on app/Model/Notification.php
> +    }
今更ながらこちらの関数は使われていないと思い、
使われていないなら一旦は消すべきかと思うのですがいかがでしょうか？

2024-05-23 12:04 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +use Illuminate\Http\Request;
こちら参照していないので、削除お願いいただけますか？

2024-05-23 12:16 UTC, Hikaru-Giannis approved these changes

2024-05-24 04:01 UTC, yukihiroLaravel approved these changes
問題ありませんので
マージしました！
おつかれさまでした☺️

2024-05-24 04:01 UTC, merged