JKA-883 講師側ダッシュボード レッスン完了数・チャプター完了数の本日・今月を同一APIに統一（あべ）
yukihiroLaravel/juko_laravel pull request #571
Opened 2024-05-26 14:50 UTC by abeai0

## task
-Closes JKA-883
https://gut-familie.atlassian.net/browse/JKA-883?atlOrigin=eyJpIjoiOTY4ZWZmMzI5ZDhmNGQ5Mjk3NWI1MjBjOGM1MTI5MDUiLCJwIjoiaiJ9

## 概要
- 講師側ダッシュボード レッスン完了数・チャプター完了数の本日・今月を同一APIに統一

## 動作確認手順
- postmanでマネージャー権限のあるinstructorでログイン
- http://localhost:8080/api/v1/instructor/course/1/attendance/status/today(またはmonth) をGETで送信し、値が返ってくることを確認

## 考慮して欲しいこと
- 特にありません
## 確認してほしいこと
- 条件分岐にif文を使用しましたが、switchと迷いました。どのように使い分けるのが良いのでしょうか？

2024-05-27 12:58 UTC, Hikaru-Giannis requested changes

2024-05-27 12:58 UTC, kou-tech commented on app/Model/LessonAttendance.php
> +    //$periodのバリデーションに利用する定数
モデルファイルでこのコメントだけを見ると、`$period`とは？となったり、果たしてこれら定数はバリデーションのみに使っているでしょうか？なるべく他の開発者が困惑しない適切なコメントに修正をお願いします！

2024-05-27 12:58 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            ->filter(function (LessonAttendance $lessonAttendance) use ($request) {
`$request`をuseするのは避けたいです！
理由としては、$requestの実態がこの処理のコードだけでは分かりづらいためでした。
明確に期間の識別値であることが分かれば、この処理の改修しやすさが向上するかと思います！

2024-05-27 12:58 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                }
間違いではないのですが、この場合は同列の階層と捉えてelse ifを利用した方が良いかと思います！

2024-05-27 12:58 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                }
間違いではないのですが、この場合は同列の階層と捉えてelse ifを利用した方が良いかと思います！

2024-05-27 12:58 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        $completedLessonsCount = $attendances->flatMap(function (Attendance $attendance) use ($request) {
$requestをuseするのは避けたいです！
理由としては、$requestの実態がこの処理のコードだけでは分かりづらいためでした。
明確に期間の識別値であることが分かれば、この処理の改修しやすさが向上するかと思います！

2024-05-27 13:08 UTC, abeai0 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +        $completedLessonsCount = $attendances->flatMap(function (Attendance $attendance) use ($request) {
ありがとうございます、修正します

2024-05-27 13:09 UTC, abeai0 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                }
ありがとうございます、修正します

2024-05-27 13:10 UTC, abeai0 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +            ->filter(function (LessonAttendance $lessonAttendance) use ($request) {
ありがとうございます、修正します

2024-05-27 13:10 UTC, abeai0 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                }
ありがとうございます、修正します

2024-05-27 13:20 UTC, abeai0 commented on app/Model/LessonAttendance.php
> +    //$periodのバリデーションに利用する定数
端的にわかりやすく伝えられる定数名が浮かばなかったので、文章になってしまいました。
`// 期間内の受講状況を取得する際の期間に関する定数`
これで伝わるでしょうか？

2024-05-28 13:09 UTC, kou-tech requested changes

2024-05-28 13:09 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                }
小技として、今後識別値が増えた場合は、これらの処理も改修が必須となることが推測されますよね。
その場合、次のようにして意図的に例外をスローさせて実装中に発見できるようにしておきましょう！

```php
                } else {
                    throw new Exception('Invalid period');
                }

```

2024-05-28 13:09 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                }
小技として、今後識別値が増えた場合は、これらの処理も改修が必須となることが推測されますよね。
その場合、次のようにして意図的に例外をスローさせて実装中に発見できるようにしておきましょう！

                } else {
                    throw new Exception('Invalid period');
                }

2024-05-28 23:44 UTC, abeai0 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                }
ありがとうございます、修正します

2024-05-28 23:44 UTC, abeai0 commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
> +                }
ありがとうございます、修正します

2024-05-29 12:13 UTC, Hikaru-Giannis approved these changes

2024-05-29 12:13 UTC, merged