講師チャプターレッスン公開非公開API 空の配列を返すルーターとコントローラの作成（小林）
yukihiroLaravel/juko_laravel pull request #572
Opened 2024-05-27 03:37 UTC by Celadon67

2024-05-27 12:20 UTC, yukihiroLaravel requested changes

2024-05-27 12:20 UTC, yukihiroLaravel commented on routes/api.php
>                          Route::prefix('{chapter_id}')->group(function () {
prefixを使う

2024-05-27 12:20 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +    public function updateLessonStatus()
Lessonコントローラに移す

2024-05-27 12:20 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +use Illuminate\Http\Request;
消す

2024-05-27 12:23 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +use Illuminate\Http\Request;
消去いたしました。

2024-05-27 12:24 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +    public function updateLessonStatus()
移動いたしました。

2024-05-27 13:08 UTC, Celadon67 commented on routes/api.php
>                          Route::prefix('{chapter_id}')->group(function () {
移動いたしました。

2024-05-28 13:16 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +     * 選択済みのレッスン公開/非公開API
`公開/非公開API`というよりは、`ステータス一括更新`で良いです！
その他のステータスが増えたときに、このコメントだと更新されないことが予想されます...。

2024-05-28 13:25 UTC, yukihiroLaravel approved these changes
ありがとうございます！
マージしました！おつかれさまでした！

2024-05-28 13:25 UTC, merged