講師チャプターレッスン公開非公開API ロジックの作成（小林）
yukihiroLaravel/juko_laravel pull request #575
Opened 2024-05-28 13:55 UTC by Celadon67

## issue
- https://gut-familie.atlassian.net/browse/JKA-891
## 概要
- 講師側 チャプター作成画面 選択済レッスンを公開/非公開にするAPI作成　子課題
  ロジックの作成
## 動作確認手順
- PUTリクエストで　http://localhost:8080/api/v1/instructor/course/1/chapter/1/lesson/status
にログインすると下記のエラーが正常にでる。

```
{
    "message": "The given data was invalid.",
    "errors": {
        "lessons": [
            "The lessons field is required."
        ],
        "status": [
            "The status field is required."
        ]
    }
}
```

## 考慮してほしいこと
- 今回は特にありません。
## 確認してほしいこと
- 今回は特にありません。

2024-05-31 04:14 UTC, yukihiroLaravel requested changes
コメントしましたのでご確認ください！

2024-05-31 04:14 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                ->firstOrFail();
現在、$chapterを一切使っていないですよね？

2024-05-31 04:14 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            }
数を数えただけでは
lessonがそれぞれURLのcourseやchapterに属しているか分からないので
前回プルリクで記述されていたようなやり方で
$request->lessonsのidと照合する必要があると思います！

2024-05-31 04:14 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        }
トランザクションをなくしたので
try catchも不要で、その結果
ValidationErrorException
なども不要だと思います！

2024-05-31 06:14 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                ->firstOrFail();
失礼いたしました。修正いたしました。

2024-05-31 06:15 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            }
修正しました。

2024-05-31 06:15 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        }
修正しました。

2024-05-31 10:41 UTC, yukihiroLaravel requested changes
いくつかコメントしました！

2024-05-31 10:41 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            ->whereIn('id', $request->lessons)
ここですでに $request->lessons で検索しているのでしたら
３３０行目でdiffで比較した時に絶対に合致するので
下で照合している意味がないと思いました！

2024-05-31 10:41 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                'message' => 'Some lessons do not belong to the specified course or chapter.',
エラーメッセージは他と統一して
もっとシンプルに
Invalid chapter_id.
などで良い気がします！

2024-05-31 10:41 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        $course = Course::findOrFail($course_id);
$lessons = Lesson::with('chapter.course')->whereIn('id', ~)->get();

下記のsortメソッドで使われているように
withを使う形で一括でcourseなどとともにLessonを持ってくれば
今のように個別でcourseを取得してこなくて良いかと思いました。

https://github.com/yukihiroLaravel/juko_laravel/blob/develop/app/Http/Controllers/Api/Instructor/LessonController.php

2024-05-31 10:41 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        }
下記のsortメソッドで使われているように
このあたりの認可処理は下記のような形で行うのが
（２回目のpush時にも言いましたが
　最初のプルリクで上げてくれていたforeachのような形がまだ近い）
いいかなと思いました！

$lessons->each(function ($lesson) use

https://github.com/yukihiroLaravel/juko_laravel/blob/develop/app/Http/Controllers/Api/Instructor/LessonController.php

2024-05-31 10:53 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                'message' => 'Some lessons do not belong to the specified course or chapter.',
修正しました。

2024-05-31 12:36 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            ->whereIn('id', $request->lessons)
修正しました。

2024-05-31 12:56 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        $course = Course::findOrFail($course_id);
修正いたしました。

2024-05-31 14:09 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        }
sortメソッドをまねて該当部分を記述しましたが、以下のコードでも試しましたが同じ結果になったのですが、どちらが望ましいとかありますか?

```
`foreach ($lessons as $lesson) {
    if ($lesson->chapter->course->instructor_id !== $user->id) {
        throw new ValidationErrorException('Invalid instructor_id.');
    }
    if ($lesson->chapter->course_id !== $course_id) {
        throw new ValidationErrorException('Invalid course_id.');
    }
    if ($lesson->chapter_id !== $chapter_id) {
        throw new ValidationErrorException('Invalid chapter_id.');
    }
}
`
```

2024-06-01 07:44 UTC, yukihiroLaravel requested changes
また少しコメントしました！
ご確認ください！

2024-06-01 07:44 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        }
sortメソッドと同じように
lessonsが空だったりnullの場合は、フロント側で
はじくと思うのでここはいらないかと思います！

2024-06-01 07:44 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                ->get();
インデントがこちらおかしいですね！

2024-06-01 07:48 UTC, yukihiroLaravel requested changes

2024-06-01 07:48 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                ->where('chapter_id', $chapter_id)
下で
指定したチャプターIDがレッスンのチャプターIDと一致しない場合
を検証しているので、ここで
->where('chapter_id', $chapter_id)
は不要な気がします！

2024-06-01 07:58 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        }
修正いたしました。

2024-06-01 07:59 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                ->get();
修正いたしました。

2024-06-01 08:11 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                ->where('chapter_id', $chapter_id)
削除いたしました。

2024-06-01 08:34 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        }
そういうご事情でしたら
一旦バリデーションも含んでおいて大丈夫です！

2024-06-02 05:15 UTC, Hikaru-Giannis requested changes

2024-06-02 05:15 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        });
この実装だと例外をフレームワークの機能でキャッチして、エラーを返されているので、意図的にキャッチしてエラーを返すようにしましょう！一旦、返すエラーは次の内容でお願いします。
ただこのHTTPステータスは不適切なので、本来は認可拒否である403が適切な気がします...。

```php
            return response()->json([
                'result' => false,
                'message' => $e->getMessage(),
            ], 422);
```

2024-06-02 05:15 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +use App\Model\Chapter;
このインポートの変更は従来の実装に影響しませんか？
そもそも変更する必要があるのか疑問なので、意図があればお聞きしたいです！

2024-06-02 07:30 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +use App\Model\Chapter;
そうですね、失礼いたしました。変更したほうがいいかと当初思ってそのままでしたが、必要なかったので元に戻しました。

2024-06-02 07:43 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        });
修正しました

2024-06-02 10:41 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            ], 403);
非常に良いアプローチで修正していただいているのですが、こちらの処理の動作確認はされていましたでしょうか？

2024-06-02 10:44 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            ], 403);
postmanの結果、エラー文が出ず以下のように値が返ってきましたが、問題ありましたでしょうか?
```
{
    "message": "The given data was invalid.",
    "errors": {
        "lessons": [
            "The lessons field is required."
        ],
        "status": [
            "The status field is required."
        ]
    }
}
```

2024-06-02 12:21 UTC, Hikaru-Giannis approved these changes

2024-06-02 16:06 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！

2024-06-02 16:06 UTC, merged