#jka-886 マネージャー側ダッシュボード本日のレッスン・チャプター完了数の取得API　空の配列を返す
yukihiroLaravel/juko_laravel pull request #576
Opened 2024-05-29 20:55 UTC by sol6406

## Issue
- Closes #jka-886 
## 概要
- 「マネージャー側ダッシュボード本日のレッスン・チャプター完了数」の取得API
- 空の配列を返すルーターとコントローラの作成
　
## 動作確認手順
- postmanにて
- http://localhost:8080/api/v1/manager/course/1/attendance/status/today
- にアクセスし空の配列が返ってくる
## 考慮してほしいこと
ありません
## 確認してほしいこと
ブランチ操作が間違っているところがあり、再度ブランチを作成しやり直したのでブランチがごちゃごちゃしています。上手い整理方法などがあれば教えていただきたいです。

2024-05-30 06:44 UTC, yukihiroLaravel requested changes
少しコメントしましたので
ご確認ください😃

2024-05-30 06:44 UTC, yukihiroLaravel commented on routes/api.php
> +                            Route::get('status/today', 'Api\Manager\AttendanceController@showStatusToday');
こちらさらにこのルーティングを
Route::prefix('status')->group(function () {
});
で囲んで
'status/today'
の部分を
'today'
だけにしましょう！

2024-05-30 07:25 UTC, sol6406 commented on routes/api.php
> +                            Route::get('status/today', 'Api\Manager\AttendanceController@showStatusToday');
変更しました。

2024-05-31 04:23 UTC, yukihiroLaravel requested changes
１点だけ指摘漏れていましたのでご指摘しました！

2024-05-31 04:23 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
>      }
ここに１行空行を入れましょう！

2024-05-31 06:52 UTC, sol6406 commented on app/Http/Controllers/Api/Manager/AttendanceController.php
>      }
９４行目の下に空行入れました。

2024-05-31 14:13 UTC, Hikaru-Giannis approved these changes

2024-05-31 22:17 UTC, yukihiroLaravel approved these changes
マージしました！！

2024-05-31 22:17 UTC, merged