講師チャプターレッスン公開非公開API 講師チャプターレッスン公開非公開API リクエストファイルの作成（小林）
yukihiroLaravel/juko_laravel pull request #578
Opened 2024-05-31 01:28 UTC by Celadon67

2024-05-31 01:32 UTC, Celadon67 commented
## issue
- https://gut-familie.atlassian.net/browse/JKA-891
## 概要
- 講師側 チャプター作成画面 選択済レッスンを公開/非公開にするAPI作成　子課題
  リクエストファイルの作成
## 動作確認手順
- PUTリクエストで　http://localhost:8080/api/v1/instructor/course/1/chapter/1/lesson/status

## 考慮してほしいこと
- 今回は特にありません。
## 確認してほしいこと
- 今回は特にありません。

2024-05-31 04:18 UTC, yukihiroLaravel requested changes
いくつかコメントしました！
ご確認ください！

2024-05-31 04:18 UTC, yukihiroLaravel commented on app/Http/Requests/Instructor/LessonputStatusRequest.php
> +            'lessons.*' => 'integer|exists:lessons,id',
ここもrequiredが必要だと思います！

2024-05-31 04:18 UTC, yukihiroLaravel commented on app/Http/Requests/Instructor/LessonputStatusRequest.php
> +            'status' => 'required|string|in:public,private'
public,privateのところは
下記のRuleクラスが使えます！

他でも同様に利用しているところがありますので
参考にしてみてください！
https://github.com/yukihiroLaravel/juko_laravel/blob/develop/app/Rules/LessonStatusRule.php

2024-05-31 04:18 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +    public function putStatus(LessonputStatusRequest $request, int $course_id, int $chapter_id): JsonResponse
course_id と chapter_idはここでは消すことができ
その結果フォームリクエストの中に含むことができるようになります！

2024-05-31 06:32 UTC, Celadon67 commented on app/Http/Requests/Instructor/LessonputStatusRequest.php
> +            'lessons.*' => 'integer|exists:lessons,id',
修正いたしました。

2024-05-31 06:33 UTC, Celadon67 commented on app/Http/Requests/Instructor/LessonputStatusRequest.php
> +            'status' => 'required|string|in:public,private'
他のところを参考にすると、今回の修正のようになりましたが、このような感じですか?

2024-05-31 06:34 UTC, Celadon67 commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +    public function putStatus(LessonputStatusRequest $request, int $course_id, int $chapter_id): JsonResponse
了解いたしました!!

2024-05-31 10:49 UTC, yukihiroLaravel requested changes
今だと動作確認などできていないと思いますので
今後慎重に動作確認など行ってからプルリクしましょう！

2024-05-31 10:49 UTC, yukihiroLaravel commented on app/Rules/LessonStatusRule.php
>      /**
このファイルは変更すべきでないと思うので元にもどしましょう！

2024-05-31 10:49 UTC, yukihiroLaravel commented on app/Http/Requests/Instructor/LessonputStatusRequest.php
> +<?php
ファイル名がおかしいです！
ただしくは

LessonPutStatusRequest.php

だと思います！

2024-05-31 10:49 UTC, yukihiroLaravel commented on app/Http/Requests/Instructor/LessonputStatusRequest.php
> +
動作確認ができていないと思います！

$chapter_idや$course_idが未定義でエラーになりますよね？

なので、
このあたりにURLから下記IDをmergeする記述が必須かと思います！
course_id, chapter_id

他のリクエストファイルでよく出てくる
（過去のタスクでも出てきた）部分だと思いますので
参考に記述し直しましょう

2024-05-31 11:30 UTC, Celadon67 commented on app/Http/Requests/Instructor/LessonputStatusRequest.php
> +<?php
1回目レビューいただいたときに大文字にしないといけないと思って変更したのですが、リモートでは反映されていないようですが、1回目レビューいただいた際にすでに変更しているので、リモート上のこの不具合についてはよくわかりません。そちらから指摘される前に1回目のレビュー時に変更していることは1回目レビューいただいた時点でのControllerでのRequest名で変更済みです。
![image](https://github.com/yukihiroLaravel/juko_laravel/assets/151298156/d6fc6f13-aa2c-4d5e-b101-06d5b4c9d00b)
![image](https://github.com/yukihiroLaravel/juko_laravel/assets/151298156/11007d2d-78df-4a4c-ad67-71f9c138be26)

2024-05-31 11:30 UTC, Celadon67 commented on app/Http/Requests/Instructor/LessonputStatusRequest.php
> +
動作確認はした結果でしたが、少し手違いがあったなら失礼いたしました。修正しました。

2024-05-31 11:45 UTC, yukihiroLaravel requested changes
また少しコメントしました！

ロジックの中身については一旦いじらなくてOKです

2024-05-31 11:45 UTC, yukihiroLaravel commented on app/Http/Requests/Instructor/LessonputStatusRequest.php
> +        ]);
他の同様な部分は参考にされましたか？
他と同じように下記のprepareForValidationという関数を設けて
記述すべきかと思います！

```
    protected function prepareForValidation()
    {
        $this->merge([
        ]);
    }
```

2024-05-31 11:45 UTC, yukihiroLaravel commented on app/Http/Requests/Instructor/LessonputStatusRequest.php
> +<?php
原因がわかりませんが、
きちんとアドとコミットができていれば
反映されるはずですが、、、。

2024-06-02 13:35 UTC, Hikaru-Giannis requested changes

2024-06-02 13:35 UTC, Hikaru-Giannis commented on app/Http/Requests/Instructor/LessonputStatusRequest.php
> +            'chapter_id' => 'required|integer|exists:chapters,id',
バリデーションの記法を統一したいですね！
私個人の意見も含みますが、複数要素を文字列で記述するのは直感的ではないので、配列に統一すると良いと思います！

2024-06-02 13:35 UTC, Hikaru-Giannis commented on app/Http/Requests/Instructor/LessonputStatusRequest.php
> +            'chapter_id' => 'required|integer|exists:chapters,id',
各主キーにおいて、論理削除されている場合もエラーを返すようにお願いします！

2024-06-02 14:06 UTC, Celadon67 commented on app/Http/Requests/Instructor/LessonputStatusRequest.php
> +            'chapter_id' => 'required|integer|exists:chapters,id',
上記2点、修正いたしました

2024-06-03 13:06 UTC, Hikaru-Giannis requested changes

2024-06-03 13:06 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +    public function putStatus(LessonPutStatusRequest $request, int $course_id, int $chapter_id): JsonResponse
`course_id`と`chapter_id`はRequestファイルでマージしているので、Requestインスタンスから参照するようにお願いします！

2024-06-03 13:06 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        $lessons = Lesson::with('chapter.course')->whereIn('id', $request->validated()['lessons'])->get();
次の書き方は間違いではないのですが、直感的ではないのと、$requestの値を参照するたびに記述するのは、冗長である気がします。

```php
$request->validated()['lessons']
```

バリデーション処理は済んでいるので、そのままプロパティを参照するか、どうしても`validated ()`を使うのであれば一度変数に格納してから参照するようにお願いします！

2024-06-03 22:31 UTC, Hikaru-Giannis requested changes

2024-06-03 22:31 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        $chapter_id = $request->chapter_id;
変数名はキャメルケースにしましょう！

2024-06-03 22:31 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        $chapter_id = $request->chapter_id;
実装に一貫性がないのでどちらかに寄せて欲しいです。

どうして、講座idとチャプターidはプロパティで参照しているのに、他の値は`validated()`から参照しているのでしょうか？
今回はすべての値をvalidateしている状態なので、そもそも`validated()`から参照する必要性はないです。

`validated()`を参照するたびに、`$request->validated()['status']`とするのは冗長であるため変数に入れた方がいいという話でした。

```php
$validated = $request->validated();
```

2024-06-04 01:06 UTC, Celadon67 commented
失礼いたしました。昨日ゆきひろさんからその点ご指摘いただき、修正できていなかったため、一旦あげたプルリクのSlackメッセージを削除させていただいていました。

帰宅次第修正いたします。

2024年6月4日(火) 7:31 Kou ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In app/Http/Controllers/Api/Instructor/LessonController.php
> <https://github.com/yukihiroLaravel/juko_laravel/pull/578#discussion_r1625123220>
> :
>
> > +        // リクエストからコースIDとチャプターIDを取得
> +        $course_id = $request->course_id;
> +        $chapter_id = $request->chapter_id;
>
> 変数名はキャメルケースにしましょう！
> ------------------------------
>
> In app/Http/Controllers/Api/Instructor/LessonController.php
> <https://github.com/yukihiroLaravel/juko_laravel/pull/578#discussion_r1625125903>
> :
>
> > +        // リクエストからコースIDとチャプターIDを取得
> +        $course_id = $request->course_id;
> +        $chapter_id = $request->chapter_id;
>
> 実装に一貫性がないのでどちらかに寄せて欲しいです。
>
> どうして、講座idとチャプターidはプロパティで参照しているのに、他の値はvalidated()から参照しているのでしょうか？
> 今回はすべての値をvalidateしている状態なので、そもそもvalidated()から参照する必要性はないです。
>
> validated()を参照するたびに、$request->validated()['status']
> とするのは冗長であるため変数に入れた方がいいという話でした。
>
> $validated = $request->validated();
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/yukihiroLaravel/juko_laravel/pull/578#pullrequestreview-2094971082>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BECKA3E4LQCPCF7XISFIGEDZFTVFHAVCNFSM6AAAAABIR5JCUCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAOJUHE3TCMBYGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-05 08:28 UTC, closed without merging