#912 empty_array_create
yukihiroLaravel/juko_laravel pull request #587
Opened 2024-06-16 08:35 UTC by tokechan

## issue
- #912 JKA  空の配列を返すルーターとコントローラの作成

## 概要
- ControllerにshowStatusメソッドを記述
- api.phpにRouteを新たに記述

## 動作確認手順
- 下記コマンドを実行
- docker exec -it  laravel_app bashにてログイン後、http://localhost:8080/　
にてバックエンド起動確認する
- POSTmanを使用して通信を確認する
URL：
http://localhost:8080/api/v1/manager/course/{course_id}/attendance/status/today
- メソッド：GET
- レスポンス：空の配列→ []が表示されることを確認する

## 確認して欲しい事
- Routeに記述したコードの書いてる箇所がおかしくないかチェックお願いします
- また、全体的におかしなとこあればアドバイスをよろしくお願いします

2024-06-16 12:27 UTC, yukihiroLaravel requested changes
いくつかコメントしましたので
ご確認お願いします！

2024-06-16 12:27 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +    /**
この上に１つ空行を入れましょう

2024-06-16 12:27 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +     * 完了済みレッスン数と完了済みチャプター数を取得するAPI
一旦は、

本日のレッスン・チャプター完了数の取得API

という名前に変更しましょう

2024-06-16 12:27 UTC, yukihiroLaravel commented on routes/api.php
> +                                Route::get('status/{period}', 'Api\Manager\AttendanceController@showStatus');
このURLの
statusも
prefixでまとめられると思います！

また一旦、{period}は削除して
URLは、'today'
にしましょう！

また
showStatusToday()
という関数名にしましょう！

2024-06-16 12:27 UTC, yukihiroLaravel commented on routes/api.php
> +                    Route::prefix('student')->group(function () {
このあたり全体的にいじってしまったらダメな部分をいじってしまっている気がしますので
元に戻しましょう！

2024-06-16 12:27 UTC, yukihiroLaravel commented on routes/api.php
> -        Route::post('/', 'Api\Student\StudentController@store');
このあたり全体的にいじってしまったらダメな部分をいじってしまっている気がしますので
元に戻しましょう！

2024-06-16 12:27 UTC, yukihiroLaravel commented on routes/api.php
> +                });
このあたり全体的にいじってしまったらダメな部分をいじってしまっている気がしますので
元に戻しましょう！

2024-06-16 12:27 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +use Composer\DependencyResolver\Request;
こちらいらなくないでしょうか？
もし使うとしても
必要になったタイミングで呼び出しましょう！

2024-06-17 04:47 UTC, tokechan commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +    /**
修正完了。

2024-06-17 04:47 UTC, tokechan commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +     * 完了済みレッスン数と完了済みチャプター数を取得するAPI
修正完了。

2024-06-18 10:34 UTC, Hikaru-Giannis approved these changes

2024-06-21 08:38 UTC, merged