jka-923 マネージャー(講師側) チャプター作成画面 選択済チャプターを削除するAPI作成 3.ロジックの作成
yukihiroLaravel/juko_laravel pull request #593
Opened 2024-06-30 01:04 UTC by masashi-tamayama

## タスク
- Closes #  jka-923

## 概要
- **3.ロジックの作成**

## 動作確認手順

**1. Postmanでマネージャー権限のあるinstructorでログイン**
`InstructorSeeder.php`
`'type' => 'manager'`のinstructorを選ぶ

**2. Postmanにて下記を入力**
- URL
`http://localhost:8080/api/v1/manager/course/1/chapter`
- リクエスト
`DELETE`
- リクエストボディ
RAW　JSON
```
{
    "chapters": [1, 2, 3]
}
```
- レスポンス
```
{
    "result": true,
    "deleted_chapters": [
        1,
        2,
        3
    ]
}
```

が返ってくることを確認
![スクリーンショット 2024-06-29 111029](https://github.com/yukihiroLaravel/juko_laravel/assets/156323724/a4da8027-1a8f-4399-b6e7-7309d253369f)

**3. Adminer→chaptersデータにて指定したchapter_idが削除されているか確認**
![スクリーンショット 2024-06-29 111002](https://github.com/yukihiroLaravel/juko_laravel/assets/156323724/2ccc01e0-e44a-44ed-9b91-91a0f1f7742d)

## 考慮して欲しいこと
- 特になし
## 確認して欲しいこと
- 特になし

2024-06-30 14:41 UTC, Hikaru-Giannis requested changes

2024-06-30 14:41 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            }
こちらはいわゆるN + 1問題が起きているので、解消をお願いします！
あえてここでは詳細を言及しないので、どういった問題なのか調べてみてください！

2024-06-30 14:41 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +                'deleted_chapters' => $deletedChapters,
削除されたチャプターを返すこと自体は間違いではないのですが、他の実装に合わせて現状は削除するようにお願いします！

2024-07-02 11:01 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/ChapterController.php
送信されてくるチャプターIDのリストに入ってくるチャプターIDが、認証しているマネージャーが削除して問題がないかの認可処理の追加をお願いします！

2024-07-02 11:01 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/ChapterController.php
認可処理を通すことで、送信されてくるチャプターIDのリストは全て問題なく削除できるということになるので、Eloquentを用いたバルクデリートを実行しましょう！一括削除のようなイメージです！

これだとDBへのアクセスを減らすことができると思います！

2024-07-04 20:40 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            }
N + 1問題を自分なりに調べて修正しました。
削除対象のチャプターを一度に取得してからループ内で削除する記述を行い、N + 1問題を回避しています。これにより、パフォーマンスが向上し、データベースクエリの数が減少しているかと思います。

2024-07-04 20:40 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +                'deleted_chapters' => $deletedChapters,
他の実装に合わせて削除の結果のみを返すように242行目を削除して、レスポンス形式の統一を行いました。

2024-07-04 20:40 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        }
取得したチャプターIDリストに含まれる各チャプターが、認証された講師（マネージャーやその配下の講師）が担当するコースに属しているか確認。

2024-07-04 20:40 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
>      }
認可されたチャプターIDリストをバルクデリートで一括で削除します。

2024-07-04 20:40 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
認可処理とバルクデリートを実装することで、認証されたマネージャーが問題なく削除できるチャプターのみを一括で削除できるように実装し、コメントアウトにて講師（マネージャー）が分かるように記述しました。

2024-07-04 21:48 UTC, Hikaru-Giannis requested changes

2024-07-04 21:48 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        }
入力のチャプターの要素数と、入力のチャプターのIDと、講座の講師が一致しているを条件としたレコード数が一致しているかのチェックでバリデーションを行なっていると解釈しています。
正しいか間違いかでいうと、挙動としては正しいです！

しかし、理解性という観点で可読性が良いかというとそうではないと感じました。(直感的ではないという判断軸は難しいので、個人の主観が含まれていることはご了承ください...)
他の実装で参考になりそうな部分で、`app/Http/Controllers/Api/Instructor/LessonController.php`の`sort`メソッドがあります。

```php
            // レッスン一括取得
            $lessons = Lesson::with('chapter.course')->whereIn('id', array_column($inputLessons, 'lesson_id'))->get();

            // 認可
            $lessons->each(function ($lesson) use ($instructorId, $courseId, $chapterId) {
                // 講座に紐づく講師でない場合は許可しない
                if ((int) $instructorId !== $lesson->chapter->course->instructor_id) {
                    throw new ValidationErrorException('Invalid instructor_id.');
                }
                // 指定した講座IDが1レッスンの講座IDと一致しない場合は許可しない
                if ((int) $courseId !== $lesson->chapter->course_id) {
                    throw new ValidationErrorException('Invalid course.');
                }
                // 指定したチャプターIDがレッスンのチャプターIDと一致しない場合は許可しない
                if ((int) $chapterId !== $lesson->chapter_id) {
                    throw new ValidationErrorException('Invalid chapter.');
                }
            });
```
次のような処理を行なっているので、参考に実装してみてください！
1. リクエストのIDを条件に、DBのレコードリストを取得。
2. 1.で取得したリストを`map`でループ処理を行う。
3. 講師idが一致しているか検証を行う
4. 講座idが一致しているか検証を行う
5. 検証でエラーの場合は、catchしてエラーを返す。

2024-07-07 12:36 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        }
参考にして修正をしました。

2024-07-07 12:43 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        $chapters = Chapter::with('course')->where('course_id', $course_id)->whereIn('id', $chapterIds)->get();
with メソッドを使用することで、course リレーションシップを事前にロードし、チャプターのデータを取得する際に関連するコースの情報も同時に取得します。これにより、チャプターごとの認可処理が効率的に行えます。
where メソッドを使用して、指定された条件に基づいてチャプターをフィルタリングします。

2024-07-07 12:43 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        });
each メソッドを使用してコレクションの各要素に対してコールバック関数を適用しました。
each メソッドを使用してコレクションのループ処理

1. 講師IDの認可
2. コースIDの認可
3. チャプターIDの認可
4. いずれかの条件が満たされない場合は、ValidationErrorException を投げて処理を中断し、エラーメッセージを返す。

2024-07-08 11:24 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        });
try ~ catchの中に記述して、ValidationErrorExceptionをcatchして、エラーを返すようにしましょう！

2024-07-08 11:28 UTC, Hikaru-Giannis requested changes

2024-07-08 11:28 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        }
後続のバリデーションと検証が重複していませんか？
重複しているのであれば、削除して良いと思います！

2024-07-09 11:26 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        }
重複していました💧削除しました。

2024-07-09 11:27 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        });
修正しました。

2024-07-09 11:28 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        }
バリデーションと認可処理を try ブロックに内包し、ValidationErrorException を catch してエラーレスポンスを返すように修正しました。

2024-07-09 11:31 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            });
in_array($chapter->course->instructor_id, $instructorIds, true) を使用して、認証された講師（マネージャー）およびその配下の講師のIDリストにチャプターの講師IDが含まれているか確認しています。

2024-07-10 11:42 UTC, Hikaru-Giannis requested changes

2024-07-10 11:42 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        }
try ~ catchはすでにあるものを利用するようにお願いします！

1つのtryに対して、複数のcatchは指定することができるので、今回の実装ケースにおいては冗長になってしまいます。

2024-07-11 12:35 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        }
修正しました。

2024-07-11 12:37 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        }
冗長な try ~ catch の排除：try ブロックを一つにまとめ、複数の catch ブロックを利用することで冗長性を避けました。

2024-07-11 13:09 UTC, Hikaru-Giannis requested changes

2024-07-11 13:09 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/ChapterController.php
`ValidationErrorException`の場合の動作確認をしてみましょう！
例えば、URLの$course_idを他のシーダー値にしてみるとかで、確認できると思います！

2024-07-11 13:09 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +                if (!in_array($chapter->course->instructor_id, $instructorIds, true)) {
`$instructorIds`が、useされていないので、参照できなくないですか？
動作確認時にエラーが起きたりはしていない感じですかね？

2024-07-12 14:10 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +                if (!in_array($chapter->course->instructor_id, $instructorIds, true)) {
動作確認時にエラーが発生しました。修正をおります。

2024-07-12 14:24 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
URL
http://localhost:8080/api/v1/manager/course/999/chapter
存在しないコースIDに変更しても期待するレスポンスが返ってこないです。
![スクリーンショット 2024-07-12 230256](https://github.com/user-attachments/assets/3ce533ea-bd9c-423c-ace6-efce1ba509a2)

インポートする記述を一行の追加は実施しています。
`use App\Exceptions\ValidationErrorException;`

想定として
コースの存在チェック及びチャプターの存在チェック等が必要になるのかなと想定しています。
そうすると現状の記述内容がまた変わってくるかと思うのですが...
ご教授よろしくお願いします。

2024-07-13 02:39 UTC, Hikaru-Giannis requested changes

2024-07-13 02:39 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> コースの存在チェック及びチャプターの存在チェック等が必要になる

システム内ではコースを講座と表現しているので、講座で説明しますね。
存在チェックはあるにこしたことはないですが、`FormRequest`で実装するので現状はなくても問題ないです！
現状は複合的な要素が重なって動作確認ができないように思われます。
例えば、こちらは削除APIなので、一度削除されてしまうとレコードを取得することができないので、再度マイグレーションとシーダーの実行をお願いします！

その上で、URLの`course_id`を2で、Bodyを次のようにしたりして動作確認してみてください！

```json
{
    "chapters": [1, 2, 3]
}
```

2024-07-13 02:39 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            $chapters->each(function ($chapter) use ($instructorIds, $course_id, $chapterIds) {
`$chapter`に型宣言をお願いします！

2024-07-13 02:39 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +                }
ここは、214行目でwhereの条件で指定いる箇所なので、不要かと思います！

2024-07-13 02:39 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            $chapters = Chapter::with('course')->where('course_id', $course_id)->whereIn('id', $chapterIds)->get();
間違いではないですが、今回対象ではない講座の`chapter`はエラーと返したいので、次の記述を削除お願いできますか？
```php
->where('course_id', $course_id)
```

それでないと、リクエストした`chapter_id`が実は削除されていないなどの困惑に繋がるのを避けるためでした。

2024-07-13 12:48 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            $chapters->each(function ($chapter) use ($instructorIds, $course_id, $chapterIds) {
7行目　use App\Model\Chapter;
にすでに記述されていた為、追記は不要としております。

2024-07-13 12:50 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +                }
重複している役割の内容を確認し227行目～230行目を削除しました。

2024-07-13 12:54 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            $chapters = Chapter::with('course')->where('course_id', $course_id)->whereIn('id', $chapterIds)->get();
214行目　`->where('course_id', $course_id)`
削除しました。

2024-07-13 13:08 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> システム内ではコースを講座と表現しているので、講座で説明しますね。

- コメントアウトの記述をコース→講座に変更してます。

> 存在チェックはあるにこしたことはないですが、FormRequestで実装するので現状はなくても問題ないです！

- 了解です。

> 現状は複合的な要素が重なって動作確認ができないように思われます。
> 例えば、こちらは削除APIなので、一度削除されてしまうとレコードを取得することができないので、再度マイグレーションとシーダーの実行をお願いします！

- 先に他のレビュー指摘項目を解消してから再度マイグレーションとシーダーの実行を行い、その上で動作確認を行った所、期待するレスポンスが返ってきました。
![スクリーンショット 2024-07-13 220325](https://github.com/user-attachments/assets/065f49ec-eb72-485b-9deb-556f1ec9844e)

2024-07-14 05:57 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            $chapters->each(function ($chapter) use ($instructorIds, $course_id, $chapterIds) {
指摘内容を誤解しているかと思いました！

次のようにして欲しいということでした！静的解析やIDEのサポートが受けられるなどの開発体験のメリットが大きいためでした。
```php
            $chapters->each(function (Chapter $chapter) use ($instructorIds, $course_id, $chapterIds) {
```

2024-07-14 08:01 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            $chapters->each(function ($chapter) use ($instructorIds, $course_id, $chapterIds) {
完全に誤解をしておりました💧
修正しています。よろしくお願いします。

2024-07-14 12:02 UTC, Hikaru-Giannis approved these changes

2024-07-14 12:02 UTC, merged