Feature/toke/jka 913/controller logic
yukihiroLaravel/juko_laravel pull request #596
Opened 2024-07-01 14:41 UTC by tokechan

## issue
- #JKA-913 本日完了したレッスンの数を取得し、APIを返却する

## 概要
- 本日の完了したレッスンの数を取得し、APIを返却する

## 動作確認手順

1. Postmanでマネージャー権限のあるinstructorでログイン
2. Postmanで下記を入力
- URL
``` http://localhot:8080//api/v1/manager/course/{course_id}/attendance/status/today```
- リクエスト
```GET```
- Headers
```Key```  Referer, Origin
```Value``` http://localhost:3000

3. Postmanにデータが返ってくるを確認
<img width="1392" alt="Screenshot 2024-07-01 at 21 45 02" src="https://github.com/yukihiroLaravel/juko_laravel/assets/36120057/05d22678-2ba2-41df-af71-1145baf52d55">

## 考慮して欲しいこと
- 一旦、コメントアウトしたものを記述しています。それ以外で問題ないか確認をお願いします。最後のマージ前にコメントアウトは修正します。

## 確認して欲しい事
特になし

2024-07-02 00:38 UTC, yukihiroLaravel requested changes
チャプター数関連の記述と
マネージャー関連の記述を除いてはこれでOKだと思います！

ただ、不要な認識は持たれていると思いますが
現在ある不要なddやコメントアウトはマージされるにあたっては
残さないと次タスク的にまずい状況などを除いて
原則削除すべきなので削除しましょう！

2024-07-02 00:38 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +        // });
マージされるにあたっては、
一旦不要なddやコメントアウトは消しましょう！

2024-07-02 00:38 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            // dd($compleatedLessonAttendances);
マージされるにあたっては、
一旦不要なddやコメントアウトは消しましょう！

2024-07-02 00:38 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +        //dd($completedLessonsCount);
マージされるにあたっては、
一旦不要なddやコメントアウトは消しましょう！

2024-07-02 11:04 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +                return $lessonAttendance->status === 'completed_attendance' && $lessonAttendance->updated_at->isToday();
'completed_attendance'をベタ書きはマジックナンバーではありませんが、同類の問題が起きてしまうので、定数を参照するようにお願いします！

2024-07-04 03:49 UTC, tokechan commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +        // });
承知しました！

2024-07-04 03:49 UTC, tokechan commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            // dd($compleatedLessonAttendances);
承知しました！

2024-07-04 03:49 UTC, tokechan commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +        //dd($completedLessonsCount);
承知しました！

2024-07-04 03:52 UTC, tokechan commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +                return $lessonAttendance->status === 'completed_attendance' && $lessonAttendance->updated_at->isToday();
なるほどです！
LessonAttendanceモデルの中に定数が作成されていたので、そちらを参照するということでいいでしょうか？一旦それで、書き直した上でPostmanで通信ができることは確認できましたので、再度プッシュいたします。

2024-07-04 21:59 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +        $completedLessonsCount = $completedLessonsCount->count();
156行目の変数名は、その時点で数値ではないので不適切かと思いました！
またケースバイケースですが、156行目と162行目で同じ変数名の使い回しも極力避けた方がいいです。後続処理に影響し、バグの発生の原因になります。

そもそも今回は、処理を分割する必要はないように感じました。
次のように記述しなかったのは意図があったりしますでしょうか？特に意図がなければ、冗長性を解消するべく提案したコードで修正をお願いしたいです！

```php
        $completedLessonsCount = $attendances->flatMap(function (Attendance $attendance) {
            $compleatedLessonAttendances = $attendance->lessonAttendances->filter(function (LessonAttendance $lessonAttendance) {
                return $lessonAttendance->status === LessonAttendance::STATUS_COMPLETED_ATTENDANCE && $lessonAttendance->updated_at->isToday();
            });
            return $compleatedLessonAttendances;
        })
        ->count();
```

2024-07-04 23:15 UTC, tokechan commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +        $completedLessonsCount = $completedLessonsCount->count();
確かに、同じ変数名を使っておりました。こちらは、私の認識ミスです。
合わせて、処理を分割したとこもご指摘通りだと思いましたので、指摘いただいたコードへ修正いたします。

2024-07-05 10:00 UTC, Hikaru-Giannis approved these changes

2024-07-05 11:33 UTC, yukihiroLaravel approved these changes
OKなのでマージしました！
おつかれさまでした😃

2024-07-05 11:33 UTC, merged