JKA-815 講師側（マネージャー側）受講生詳細画面の学習状況API ロジックの作成（とさか）
yukihiroLaravel/juko_laravel pull request #599
Opened 2024-07-04 21:34 UTC by tosakafullyremote

## issue
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-815

## 概要
- マネージャー 受講生詳細画面の学習状況を取得するAPIを作成　子課題
ロジックの作成

## 動作確認手順
- ポストマンにてGETリクエストで/api/v1/instructor/attendance/{attendance_id}/statusを実行
{attendance_id}は動的のため、１を入れると下記レスポンスが返ってくる

レスポンス
```
{
    "data": {
        "attendance_id": 1,
        "progress": 10,
        "course": {
            "course_id": 1,
            "title": "PHP入門講座",
            "status": "public",
            "image": "course/4459908b-3cdf-4521-94fa-c2a9746d92e1.png",
            "chapter": [
                {
                    "chapter_id": 1,
                    "title": "PHPとは？",
                    "status": "public"
                },
                {
                    "chapter_id": 2,
                    "title": "PHPの基礎を学ぼう",
                    "status": "public"
                },
                {
                    "chapter_id": 3,
                    "title": "PHPの応用にチャレンジしよう",
                    "status": "public"
                }
            ]
        }
    }
}
```
が返ってくることを確認

存在しない50を入れるとエラーメッセージが返ってくる
レスポンス
```
{
    "message": "No query results for model [App\\Model\\Attendance] 50",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
    "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php",
    "line": 224,
    "trace": [
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php",
            "line": 200,
            "function": "prepareException",
            "class": "Illuminate\\Foundation\\Exceptions\\Handler",
            "type": "->"
        },
```

## 考慮してほしいこと
- 今回は特にありません。

## 確認してほしいこと
- エラーメッセージが気になりますが、attendance_idに50が無いエラーと思ってます。認識に相違がないかご確認よろしくお願いいたします。

2024-07-07 08:47 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +                    }),
チャプターの進捗を計算して、レスポンスに含める必要がありますのでお願いします！

仕様は次のとおりでした！
`チャプターに含まれるレッスンの受講状態が完了済みの数 / チャプターに含まれるレッスンの合計数 * 100`

2024-07-08 16:49 UTC, tosakafullyremote commented
## issue
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-815

## 概要
- マネージャー 受講生詳細画面の学習状況を取得するAPIを作成　子課題
ロジックの作成

## 動作確認手順
- ポストマンにてGETリクエストで/api/v1/instructor/attendance/{attendance_id}/statusを実行
{attendance_id}は動的のため、１を入れると下記レスポンスが返ってくる

レスポンス
```
{
    "data": {
        "attendance_id": 1,
        "progress": 10,
        "course": {
            "course_id": 1,
            "title": "PHP入門講座",
            "status": "public",
            "image": "course/4459908b-3cdf-4521-94fa-c2a9746d92e1.png",
            "chapters": [
                {
                    "chapter_id": 1,
                    "title": "PHPとは？",
                    "status": "public",
                    "progress": 100
                },
                {
                    "chapter_id": 2,
                    "title": "PHPの基礎を学ぼう",
                    "status": "public",
                    "progress": 25
                },
                {
                    "chapter_id": 3,
                    "title": "PHPの応用にチャレンジしよう",
                    "status": "public",
                    "progress": 0
                }
            ]
        }
    }
}
```
が返ってくることを確認

存在しない50を入れるとエラーメッセージが返ってくる
レスポンス
```
{
    "message": "No query results for model [App\\Model\\Attendance] 50",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
    "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php",
    "line": 224,
    "trace": [
```


## 考慮してほしいこと
- 今回は特にありません。

## 確認してほしいこと
- ポストマンで　下記APIでGETした際に（:attendance_idに1を入力）、下記apiと同じ値が出たため、問題ない想定です。
http://localhost:8080//api/v1/instructor/attendance/:attendance_id/status

2024-07-09 17:37 UTC, tosakafullyremote commented
## issue
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-815

## 概要
- マネージャー 受講生詳細画面の学習状況を取得するAPIを作成　子課題
ロジックの作成

## 動作確認手順
- ポストマンにてGETリクエストで/api/v1/instructor/attendance/{attendance_id}/statusを実行
{attendance_id}は動的のため、１を入れると下記レスポンスが返ってくる

レスポンス
```
{
    "data": {
        "attendance_id": 1,
        "progress": 10,
        "course": {
            "course_id": 1,
            "title": "PHP入門講座",
            "status": "public",
            "image": "course/4459908b-3cdf-4521-94fa-c2a9746d92e1.png",
            "chapters": [
                {
                    "chapter_id": 1,
                    "title": "PHPとは？",
                    "status": "public",
                    "progress": 100
                },
                {
                    "chapter_id": 2,
                    "title": "PHPの基礎を学ぼう",
                    "status": "public",
                    "progress": 25
                },
                {
                    "chapter_id": 3,
                    "title": "PHPの応用にチャレンジしよう",
                    "status": "public",
                    "progress": 0
                }
            ]
        }
    }
}
```
が返ってくることを確認

存在しない50を入れるとエラーメッセージが返ってくる
レスポンス
```
{
    "message": "No query results for model [App\\Model\\Attendance] 50",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
    "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php",
    "line": 224,
    "trace": [
```


## 考慮してほしいこと
- 今回は特にありません。

## 確認してほしいこと
- ポストマンで　下記APIでGETした際に（:attendance_idに1を入力）、下記apiと同じ値が出たため、問題ない想定です。
http://localhost:8080//api/v1/instructor/attendance/:attendance_id/status

2024-07-10 11:45 UTC, Hikaru-Giannis requested changes

2024-07-10 11:45 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +use Illuminate\Support\Facades\DB;
16行目のインポートと重複していませんか？

2024-07-10 12:37 UTC, Hikaru-Giannis commented
> エラーメッセージが気になりますが、attendance_idに50が無いエラーと思ってます。認識に相違がないかご確認よろしくお願いいたします。

これはリクエストファイルで解決できるので、今は無視して問題ないです！

2024-07-11 13:13 UTC, merged