JKA-934 今月完了したレッスン数を取得し、APIから返却する(あちょこ)
yukihiroLaravel/juko_laravel pull request #600
Opened 2024-07-07 07:59 UTC by achoko3

## task
- JKA-934
## 概要
- 今月完了したレッスン数を取得し、APIから返却する
## 動作確認手順
- Postmanでマネージャー権限のあるinstructorでログイン
- Postmanで下記を入力
URL
http://localhot:8080/api/v1/manager/course/{course_id}/attendance/status/this-month
リクエスト
GET
Headers
Key Referer, Origin
Value http://localhost:3000/
Postmanにデータが返ってくることを確認
## 考慮して欲しいこと
特に無し
## 確認して欲しいこと
特に無し

2024-07-07 13:11 UTC, yukihiroLaravel requested changes

2024-07-07 13:11 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +        'completed_lessons_count' => $completedLessonsCount,
ここはインデントの問題で
スペース４つ分右に配置が必要かと思います！

2024-07-07 13:11 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +use App\Http\Requests\Instructor\AttendanceShowThisMonthRequest;
こちらは現時点では使っていない気がするので消しておきましょう！

2024-07-08 11:29 UTC, Hikaru-Giannis approved these changes

2024-07-08 13:14 UTC, yukihiroLaravel approved these changes

2024-07-08 13:14 UTC, merged