create form request of capter status
yukihiroLaravel/juko_laravel pull request #601
Opened 2024-07-07 14:01 UTC by yuuhei-koutoku

## issue
- https://gut-familie.atlassian.net/browse/JKA-941
- https://gut-familie.atlassian.net/browse/JKA-893

## 概要
- [講師側 チャプター作成画面 選択済チャプターを公開/非公開にするAPI作成](https://gut-familie.atlassian.net/browse/JKA-893)における、フォームリクエストの作成。

## 動作確認手順
- Postmanにて確認
    - HTTTPメソッド：PATCH
    - URL：http://localhost:8080/api/v1/manager/course/:course_id/chapter/status
    - Headers
        - X-XSRF-TOKEN: {{XSRF-TOKEN}}
        - Referer: http://localhost:3000/
        - Origin: http://localhost:3000/
    - Body(row json形式)
        - status: "public" or "private"
        - chapters: [1, 2, 3, 4, 5]
    - Pre-request Script
```
pm.environment.set("variable_key", "variable_value");
pm.sendRequest({
    url: 'http://localhost:8080/sanctum/csrf-cookie',
    method: 'GET'
}, function (error, response, { cookies }) {
    let xsrfCookie = cookies.one('XSRF-TOKEN');
    if (xsrfCookie) {
        let xsrfToken = decodeURIComponent(xsrfCookie['value']);
        console.log(xsrfToken);
        pm.request.headers.upsert({
            key: 'X-XSRF-TOKEN',
            value: xsrfToken,
        });                
        pm.environment.set('XSRF-TOKEN', xsrfToken);
    }
})
```

## 考慮して欲しいこと
- 特になし。

## 確認して欲しいこと
- エラーが発生しないこと。
- バリデーションの設定が仕様通りであること。

2024-07-08 11:21 UTC, Hikaru-Giannis requested changes

2024-07-08 11:21 UTC, Hikaru-Giannis commented on app/Http/Requests/Manager/ChapterSwitchStatusRequest.php
> +class ChapterSwitchStatusRequest extends FormRequest
Requestのファイル名は、他の実装に倣ってコントローラーのメソッド名に合わせて実装をお願いします！

2024-07-08 11:21 UTC, Hikaru-Giannis commented on app/Http/Requests/Manager/ChapterSwitchStatusRequest.php
Pathパラメータの`course_id`に対して、バリデーションを行うように実装をお願いします！
ただ、Queryパラメータ通りにいかない点があるので、他の実装を参考にしてみてください！

2024-07-08 11:21 UTC, Hikaru-Giannis commented on app/Http/Requests/Manager/ChapterSwitchStatusRequest.php
> +            'status' => ['required'],
statusの値は、`private`と`public`に制限しましょう！
他APIの実装によって、カスタムルールファイルが作成されているかもしれませんので、すでにそちらがあればそれに倣って実装をお願いします！

以下、カスタムルールに関してのドキュメントです。11のドキュメントですが、6でも通用する内容かと思います！
https://laravel.com/docs/11.x/validation#custom-validation-rules

2024-07-08 11:21 UTC, Hikaru-Giannis commented on app/Http/Requests/Manager/ChapterSwitchStatusRequest.php
> +            'chapters' => ['required', 'array'],
`chapters`の中の要素は、chapterテーブルのプライマリキーがリクエストされる認識です。
この段階で、chapterテーブルに存在しない or 論理削除されている 場合は、エラーを返すようにお願いします！
こちらも他のRequestファイルの実装を参考にできるかと思います！

2024-07-13 01:19 UTC, yuuhei-koutoku commented on app/Http/Requests/Manager/ChapterSwitchStatusRequest.php
> +class ChapterSwitchStatusRequest extends FormRequest
@Hikaru-Giannis 
今回僕がコントローラーで扱っているメソッドは`patchStatus`です。
本来は`ChapterPatchStatusRequest`を作成したかったのですが、既にその名前のフォームリクエストが作られています。
[app/Http/Requests/Manager/ChapterPatchStatusRequest.php](https://github.com/yukihiroLaravel/juko_laravel/blob/develop/app/Http/Requests/Manager/ChapterPatchStatusRequest.php)
僕が新規で実装したい内容と、既存の`ChapterPatchStatusRequest`の共通化は難しいと考え、仕方なく新規でメソッド名とはマッチしないフォームリクエストを作成した次第です。
この場合、どのように対処するのがよろしいでしょうか？

2024-07-13 02:46 UTC, Hikaru-Giannis commented on app/Http/Requests/Manager/ChapterSwitchStatusRequest.php
> +class ChapterSwitchStatusRequest extends FormRequest
すでに`updateStatus`などのメソッドもあり、メソッドが競合している状況なのが把握できました...。
今回は一括ステータス更新という表現で、`bulkPatchStatus`にメソッド名を変更し、それに沿ったリクエスト名に変更をお願いしたいです！

2024-07-14 05:46 UTC, Hikaru-Giannis requested changes

2024-07-14 05:46 UTC, Hikaru-Giannis commented on app/Http/Requests/Manager/BulkPatchStatusRequest.php
> +            'chapters' => ['required', 'array', 'exists:chapters,id,deleted_at,NULL'],
現時点でも、`chapters`の中のidが1つでも誤っているとエラーが返されるのですが、どの箇所にエラーが起きているか特定するべく次のように修正をお願いしたいです！
修正以前で、挙動が変わるかと思います！

```php
            'chapters' => ['required', 'array'],
            'chapters.*' => ['required', 'integer', 'exists:chapters,id,deleted_at,NULL'],
```

2024-07-14 12:01 UTC, Hikaru-Giannis approved these changes

2024-07-14 12:01 UTC, merged