JKA-940 今月完了したチャプター数を取得し、APIから返却する(あちょこ)
yukihiroLaravel/juko_laravel pull request #606
Opened 2024-07-13 07:40 UTC by achoko3

## task
JKA-940

## 概要
- 今月完了したチャプター数を取得し、APIから返却する

## 動作確認手順
- Postmanでマネージャー権限のあるinstructorでログイン
- Postmanで下記を入力
URL
[http://localhot:8080/api/v1/manager/course/{course_id}/attendance/status/this-month]
リクエスト
GET
Headers
Key→Referer, Origin
Value→http://localhost:3000/
- Postmanにデータが返ってくることを確認

2024-07-13 13:13 UTC, yukihiroLaravel requested changes
いい感じだと思いますので
細かい点のみ指摘させて頂きました！
ご確認ください😊

2024-07-13 13:13 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            'completed_chapters_count' =>  $completedChaptersCount
=> $completedChaptersCount
　↑
ここのスペースは１つでいいかと思います！

2024-07-14 05:48 UTC, Hikaru-Giannis approved these changes

2024-07-14 05:52 UTC, yukihiroLaravel approved these changes
マージしました！！おつかれさまでした！

2024-07-14 05:52 UTC, merged