JKA-994 自分と配下のinstructorの講座情報のみにアクセスできるロジック(マネージャーの認証ロジック)
yukihiroLaravel/juko_laravel pull request #607
Opened 2024-07-13 15:42 UTC by tokechan

## issue
-  https://gut-familie.atlassian.net/browse/JKA-944

## 概要
- 自分と配下のinstructorの講座情報のみにアクセスできるロジック(マネージャーの認証ロジック)

## 動作確認手順
1.Postmanでマネージャー権限のあるinstructorでログイン

2.Postmanで下記を入力
URL
http://localhot:8080//api/v1/manager/course/{course_id}/attendance/status/today
リクエスト
```GET```

Headers
```Key``` Referer, Origin
```Value``` http://localhost:3000/
3.Postmanにデータが返ってくるを確認しました
- Manager権限を持つidでエラーが出ないことを確認（id_1 とid_4）
- それ以外の権限だとエラーが返ってくることを確認
<img width="977" alt="Screenshot 2024-07-14 at 0 15 32" src="https://github.com/user-attachments/assets/836ec668-ed92-4671-b271-7e89dcbc0080">
　
<img width="918" alt="Screenshot 2024-07-14 at 0 14 36" src="https://github.com/user-attachments/assets/e4237e32-e407-4d4a-ad9f-d22d19fdc5d3">

## 考慮して欲しいこと
サンプルのコードを参考にしてますが、理解度は7割程度です
また、処理内容を理解するためにコメントアウトで何を実行しているかを記述しています

## 確認して欲しい事
特になし

2024-07-14 05:51 UTC, yukihiroLaravel requested changes
いいですね！
少しコメントしましたのでご確認ください😊

2024-07-14 05:51 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            'coures' => $course,
この情報はタスクとしては不要なので削除した方が良さそうです！

2024-07-14 05:51 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +                'message' => "Forbidden, not allowed to edit this course.",
not allowed to edit
だと編集する前提のエラー文なので
not allowed to access
などに変えましょう！

2024-07-14 06:01 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +        $course = Course::FindOrFail($request->course_id);
一応ドキュメント通りのメソッドとはずれているので、`findOrFail `に変更をお願いします。
そのうちのバージョンアップで急に使えなくなる可能性があります。

2024-07-14 09:06 UTC, tokechan commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            'coures' => $course,
なるほど！確かに、不必要ですね😅

2024-07-14 09:06 UTC, tokechan commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +                'message' => "Forbidden, not allowed to edit this course.",
確かに！完全に、コピペしたままでした。。。すいません。

2024-07-14 09:12 UTC, tokechan commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +        $course = Course::FindOrFail($request->course_id);
なるほど。確かに調べたら、先頭文字が小文字が公式ドキュメントの情報でした。
[https://laravel.com/docs/11.x/eloquent#retrieving-single-models](url)
修正いたします！

2024-07-16 11:00 UTC, Hikaru-Giannis approved these changes

2024-07-16 11:05 UTC, yukihiroLaravel approved these changes

2024-07-16 11:05 UTC, merged