JKA-932 ロジックの作成（ゆうへい）
yukihiroLaravel/juko_laravel pull request #608
Opened 2024-07-14 13:48 UTC by yuuhei-koutoku

## issue
- https://gut-familie.atlassian.net/browse/JKA-932
- https://gut-familie.atlassian.net/browse/JKA-893

## 概要
- [講師側 チャプター作成画面 選択済チャプターを公開/非公開にするAPI作成](https://gut-familie.atlassian.net/browse/JKA-893)における、ロジックの作成。

## 動作確認手順
- Postmanにて確認
    - HTTTPメソッド：PATCH
    - URL：http://localhost:8080/api/v1/manager/course/:course_id/chapter/status
    - Headers
        - X-XSRF-TOKEN: {{XSRF-TOKEN}}
        - Referer: http://localhost:3000/
        - Origin: http://localhost:3000/
    - Body(row json形式)
        - status: "public" or "private"
        - chapters: [1, 2, 3]
    - Pre-request Script
```
pm.environment.set("variable_key", "variable_value");
pm.sendRequest({
    url: 'http://localhost:8080/sanctum/csrf-cookie',
    method: 'GET'
}, function (error, response, { cookies }) {
    let xsrfCookie = cookies.one('XSRF-TOKEN');
    if (xsrfCookie) {
        let xsrfToken = decodeURIComponent(xsrfCookie['value']);
        console.log(xsrfToken);
        pm.request.headers.upsert({
            key: 'X-XSRF-TOKEN',
            value: xsrfToken,
        });                
        pm.environment.set('XSRF-TOKEN', xsrfToken);
    }
})
```

## 考慮して欲しいこと
- 特になし。

## 確認して欲しいこと
- エラーが発生しないこと。
- statusが想定通りに更新されていること。

2024-07-15 09:02 UTC, Hikaru-Giannis requested changes

2024-07-15 09:02 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +                           ->whereIn('id', $request->chapters);
`where('course_id', $course_id)`は、一旦抜きで取得していただきたいです！

理由としては、この実装ではリクエストの`$chapters`と一致しない講座は暗黙的に更新されない実装になっているためでした。満たす要件としては、`$chapters`の中に`$course_id`と一致しないidが含まれている場合は、エラーとして返すAPIにして欲しいです！

2024-07-15 09:02 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +                           ->whereIn('id', $request->chapters);
前回のタスクで作成したRequestファイルによって、`$course_id`はパスからマージされて参照できるようになっていますので、`$request`インスタンスから講座のidを参照するように修正をお願いします！
そのため最終的に192行目は、次のようになります。
```php
    public function bulkPatchStatus(BulkPatchStatusRequest $request)
```

2024-07-16 11:03 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        }
これでは、`chapters`の数だけDBのアクセスが発生してしまいます！
以前のように`whereIn`を利用すれば、そこは一度のアクセスで完結できるので、`whereIn`でチャプターのリストを取得するようにしましょう！

2024-07-16 16:22 UTC, yuuhei-koutoku commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        }
@Hikaru-Giannis 
質問①
試しにwhereInを使ってみましたが、、、仕様を満たす処理を実装するのがなかなかうまくいきません。
```
        $chapters = Chapter::whereIn('id', $request->chapters);
        foreach ($chapters as $chapter) {
            if ($chapter->course_id !== intval($request->course_id)) {
                return response()->json([
                    'result' => false,
                ]);
            }
        }
```
間違ったchapter_idで更新処理が走った際に、エラーで処理を止めることができないです。。。

質問②
「コレクションメソッドを活用し、ループ処理を行う」がよくわからないです。
Collectionクラスで使用できるメソッドの中で、ループ処理ができるものと使って実装しようという意味でしょうか？？？
https://readouble.com/laravel/6.x/ja/collections.html

2024-07-17 10:24 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        }
@yuuhei-koutoku 
質問①に関して
`whereIn`のみの記述では、まだコレクションへ変換できていないです。これはクエリを発行している状態なので、`get()`などの取得メソッドを利用することで、可能になります！

質問②に関して
その認識で問題ありません！
どうして`foreach`ではなく、コレクションメソッドを推奨している理由は次のとおりです。
1. `map`メソッドは他のコレクションメソッドとチェーンすることができ、コードの可読性が向上する。
2.  `map`メソッドを使用すると、ループ処理がシンプルで簡潔なコードになる傾向がある。
3.  `map`メソッドは元のコレクションを変更せずに新しいコレクションを返すため、副作用を避けることができる。

決して、`foreach`は悪いとかそういう話ではなくさまざまな観点から現状はコレクションメソッドを使った方が利点があるという理解をしていただければと思います！

2024-07-18 13:48 UTC, yuuhei-koutoku commented
@Hikaru-Giannis 
すみません。
現状のソースコードではバグが発生しますね。。。

<img width="985" alt="スクリーンショット 2024-07-18 22 43 54" src="https://github.com/user-attachments/assets/c4f62068-ff49-4500-89e2-15a8468f0a32">

dbに存在しない`chapters.id`を指定するとエラーが起きます。
この場合、エラーが起きたら`'result' => false,`をjsonでreturnするのが良さそうでしょうか？

2024-07-19 02:54 UTC, Hikaru-Giannis commented
@yuuhei-koutoku 
それはバグではなく、前のタスクで実装したバリデーションの仕様です！
言い換えれば、コントローラーで渡される`chapters`の値は必ずDBに存在していることが保証されているので、その懸念をしなくていいことですので、問題ないです！

ただし、DBには存在しているがそれを操作する権限があるかは話が別なので、その部分の実装をお願いしているというイメージなのですが、伝わりますでしょうか？

2024-07-19 03:11 UTC, Hikaru-Giannis requested changes

2024-07-19 03:11 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +        }
このコードでも動作上は問題なさそうですね。
ただ、他の実装と一貫性を持たせたりするなどの都合、`try ~ catch`を活用し、map内のクロージャーの中でエラーが起きた場合は例外を投げ、`catch`でキャッチし、エラーを返すように修正をお願いします！
`app/Http/Controllers/Api/Instructor/LessonController.php`の`sort`メソッドが参考になるかと思います！

よろしくお願いします！

2024-07-20 01:53 UTC, yuuhei-koutoku commented
commit: `from manager to instructor`
マネージャーから講師（インストラクター）へ、ソースコードを移行。

- URL
  - `/api/v1/instructor/course/{course_id}/chapter/status`
  - `manager`から`instructor`へ修正
- HTTPメソッド
  - PATCH
- リクエストボディ
```
{
  "status": "public" or "private",
  "chapters": [1, 2, 3]
}
```
- レスポンス
```
{
 "result": true
}
```

2024-07-20 03:33 UTC, yuuhei-koutoku commented
@Hikaru-Giannis 
**質問③**
下記のコードに関して、`map`メソッド内に記載しようと考えていましたが、フォームリクエストのバリデーションで弾く実装にしているため、削除しました。
```
// $chaptersの中に$course_idと一致しないidが含まれている場合はエラーを返す
if ((int) $request->course_id !== $chapter->course_id) {
    throw new ValidationErrorException('Invalid course_id.', 422);
}
```
この判断は問題ないでしょうか？

**質問④**
ステータスコードに関して、参考にした`app/Http/Controllers/Api/Instructor/LessonController.php`の`sort`メソッドでは`422`を使用していました。
```
        } catch (ValidationErrorException $e) {
            return response()->json([
                'result' => false,
                'message' => $e->getMessage(),
            ], 422);
```
今回僕が実装したコードでは、`ValidationErrorException`のコンストラクターで初期値として設定されている`403`を使わせてもらいました。
```
class ValidationErrorException extends Exception
{
    protected $statusCode;

    public function __construct($message = '', $statusCode = 403)
    {
        $this->statusCode = $statusCode;
        parent::__construct($message, $statusCode);
    }
}
```
`403`での設定が適切かどうか教えていただきたいです。

2024-07-20 13:35 UTC, Hikaru-Giannis commented
@yuuhei-koutoku 
## 質問③に関して
それに関してはフォームリクエストのバリデーションでルール化していないので、必要かと思います！
あくまで、フォームリクエストのバリデーションは`chapters`の要素の`id`のレコードが、テーブルに存在しているかどうかしか確認していません！それが、意図している講座のチャプターのidかどうかはまた別で考える必要があるという主張です。

## 質問④に関して
HTTPステータスを厳密に定義して運用しているわけではありませんが、403は認可に関するエラーとなることから、今回は適切だと考えられるので、問題ないです！

2024-07-21 04:26 UTC, yuuhei-koutoku commented
@Hikaru-Giannis 
> 意図している講座のチャプターのidかどうかはまた別で考える必要があるという主張です。
こちらに関して、理解しました。
ご指摘ありがとうございます。
コードを追加しました。

**質問⑤**
今回のプルリクエストに関して、そこまで規模は大きくありませんが、修正を繰り返した結果コミット数が多くなってしまいました。
このプルリクエストをクローズし、別でプルリクエストを新規作成した方が良いでしょうか？
<img width="1002" alt="スクリーンショット 2024-07-21 13 23 16" src="https://github.com/user-attachments/assets/d9a5d570-6187-4499-a2fc-c491b3ee58b3">

2024-07-21 10:20 UTC, Hikaru-Giannis requested changes

2024-07-21 10:20 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +            });
すみません、2点修正をお願いしたいです！
- コレクションメソッドを`map`から`each`へ変更する。
- クロージャーの引数`$chapter`に型宣言を加える。

`map`メソッドはコレクションの各アイテムに対して指定したコールバックを適用し、新しいコレクションを返す場合に利用します。今回は`return`がなく、コレクションに対して副作用を起こす処理を行うため、`each`の方が適切であるという判断です！

型宣言は、バグの早期発見やIDEの支援を受けることができるのが利点です！

2024-07-21 10:20 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +            ]);
動作上問題ないのですが、すでに`$chapters`として取得しているので、次のように最適化できないでしょうか？
私の方で動作確認はしていないです。

```php
            $chapters->update([
                'status' => $request->status,
            ]);
```

2024-07-21 10:20 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +            Log::error($e);
少し細かいですが、一旦ログには出力しなくて問題ないです！

現場によって、ログに出すべきエラーレベルの定義は異なるので、間違いではないです。
ただし、ここではクライアントにエラーメッセージを返すだけで解決できると判断し、ログには出力する必要性はないと現状は判断しています。

2024-07-21 10:25 UTC, Hikaru-Giannis commented
## 質問5に関して
この現場では厳密にコミット管理しているわけではないので、問題ないです！
今回はこのプルリクエストのまま引き続き対応をお願いします！

補足すると、コミットが多くなったからブランチ分けることよりも、想定以上の影響範囲であったため、プルリクエストを分けることのほうが多いです。特にFile Changed (修正ファイル数)が、数十個になってきたら少し注意が必要です。

2024-07-22 10:08 UTC, Hikaru-Giannis approved these changes

2024-07-23 14:25 UTC, Hikaru-Giannis approved these changes

2024-07-23 14:25 UTC, merged