JKA-924 マネージャー(講師側) チャプター作成画面 選択済チャプターを削除するAPI作成4.フォームリクエストの作成（たまやま）
yukihiroLaravel/juko_laravel pull request #609
Opened 2024-07-14 15:02 UTC by masashi-tamayama

## タスク
- Closes #

## 概要
- **4.フォームリクエストの作成**
- **※3.ロジックの作成**
ゆきひろさん指摘のインデントを一部修正しております。
`app/Http/Controllers/Api/Manager/ChapterController.php`
218行目～227行目

## 動作確認手順

**1. Postmanでマネージャー権限のあるinstructorでログイン**
- `database/seeds/InstructorSeeder.php`
`'type' => 'manager'`のinstructorを選ぶ

**2. Postmanにて下記を入力**
- URL
`http://localhost:8080/api/v1/manager/course/:{course_id}/chapter`

- リクエスト
`DELETE`

- リクエストボディ
RAW　JSON
```
{
    "chapters": [1, 2, 3]
}
```
- パラメーター
`{course_id}`の値をテスト的に入力（下記スクリーンショット参照）

- レスポンス（{course_id}が999の時）
![スクリーンショット 2024-07-14 232821](https://github.com/user-attachments/assets/78d99380-41e4-468c-ae0c-def667f157a9)
- レスポンス（{course_id}がaの時）
![スクリーンショット 2024-07-14 230235](https://github.com/user-attachments/assets/b852b913-73d2-4ae9-83c7-2545c47764d6)
- レスポンス（{course_id}が1でありdeleted_at が NULLでない時）
![スクリーンショット 2024-07-14 234257](https://github.com/user-attachments/assets/02478a4f-eef4-47dd-891a-1e3e9610c9f0)
![スクリーンショット 2024-07-14 234454](https://github.com/user-attachments/assets/ac9b3ea0-7309-4a81-907c-e7b2a89e728c)

削除テストの為、途中`php artisan migrate:fresh --seed`を入力しテスト実施。
期待するレスポンスがそれぞれ返ってくることを確認

## 考慮して欲しいこと
- 特になし
## 確認して欲しいこと
- 特になし

2024-07-14 15:04 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            });
ゆきひろさんご指摘の箇所になります。インデントを一部修正しております。

2024-07-15 09:05 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +    public function bulkDelete(ChapterbulkDeleteRequest $request, $course_id)
作成した`Request`ファイルによって、`$request`インスタンスから、`$course_id`を参照できるので、そのように修正をお願いします！
そのため最終的に198行目は、次のようになります。
```php
    public function bulkDelete(ChapterbulkDeleteRequest $request)
```

2024-07-15 11:51 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +    public function bulkDelete(ChapterbulkDeleteRequest $request, $course_id)
198行目内容を調べてから修正しております。

- `prepareForValidation`メソッドを使って、リクエストデータにルートパラメータとして渡される`course_id`をマージしているため、`$course_id`パラメータが不要になる

- `prepareForValidation`メソッドの働きにより、`course_id`はリクエストのデータとして扱われるため、コントローラーメソッドの引数として別途渡す必要がなくなる。

- この修正により、コントローラーメソッドがよりシンプルになり、引数の重複を避けることができる。

2024-07-15 13:19 UTC, Hikaru-Giannis requested changes

2024-07-15 13:19 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +use App\Http\Requests\Manager\ChapterbulkDeleteRequest;
`ChapterBulkDeleteRequest`にいして欲しいです！

2024-07-15 13:19 UTC, Hikaru-Giannis commented on app/Http/Requests/Manager/ChapterBulkDeleteRequest.php
> +class ChapterbulkDeleteRequest extends FormRequest
`ChapterBulkDeleteRequest`にして欲しいです！

2024-07-15 13:19 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
>       * @param int $course_id
`@param int $course_id`は削除して問題ないです！

2024-07-15 13:19 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            $chapters->each(function (Chapter $chapter) use ($instructorIds, $course_id, $chapterIds) {
$course_idは未定義の変数となっているので、修正をお願いします！
また、`$chapterIds`はクロージャー内で参照していないので、useの中から削除して問題ありません。

2024-07-15 13:19 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +    public function bulkDelete(ChapterbulkDeleteRequest $request, $course_id)
調べている内容はあっています！

2024-07-15 23:57 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +use App\Http\Requests\Manager\ChapterbulkDeleteRequest;
`ChapterBulkDeleteRequest`に修正をしました。

2024-07-15 23:58 UTC, masashi-tamayama commented on app/Http/Requests/Manager/ChapterBulkDeleteRequest.php
> +class ChapterbulkDeleteRequest extends FormRequest
`ChapterBulkDeleteRequest`に修正をしました。

2024-07-16 00:05 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
>       * @param int $course_id
195行目　削除しています。

- **調べた内容**
`course_id`がリクエストクラス（`ChapterbulkDeleteRequest`）内で処理されるため、コントローラーメソッドの引数として`course_id`を直接受け取る必要がなくなる。

2024-07-16 00:24 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            $chapters->each(function (Chapter $chapter) use ($instructorIds, $course_id, $chapterIds) {
> $course_idは未定義の変数となっているので、修正をお願いします！

- **クロージャ外での$course_id定義**
// リクエストからcourse_idを取得
 `$course_id = $request->input('course_id');`

1.  クロージャの外で$course_idをリクエストオブジェクトから取得する。
2. これにより、クロージャ内で$course_idが未定義の変数として扱われることを防ぐ。

> また、$chapterIdsはクロージャー内で参照していないので、useの中から削除して問題ありません。

削除しています。
また前回プルリク提出前に動作確認を行ってはいましたが、返ってきたレスポンスの勘違いでした。
（コードを再現して行いました。正常な動作が出来ていない事を確認致しました。原因としてはその前のバリデーション確認時のレスポンスと間違えていました💧すみませんでした🙇今後気を付けて行きます。）
下記は今回の動作確認状態です。
![スクリーンショット 2024-07-16 082643](https://github.com/user-attachments/assets/93398284-3e40-4bd2-95dc-025c6a724481)

2024-07-16 11:07 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            $course_id = $request->input('course_id');
変数名はキャメルケースにしましょう！

2024-07-16 21:34 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            $course_id = $request->input('course_id');
キャメルケースに修正しています。
`$course_id`→`$courseId`
その他4箇所とも修正しております。

2024-07-16 21:35 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            $courseId = $request->input('course_id');
キャメルケースに修正しています。
$course_id→$courseId

2024-07-16 21:36 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            // リクエストからcourseIdを取得
キャメルケースに修正しています。
$course_id→$courseId

2024-07-16 21:36 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            $chapters->each(function (Chapter $chapter) use ($instructorIds, $courseId) {
キャメルケースに修正しています。
$course_id→$courseId

2024-07-16 21:36 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +                if ((int) $courseId !== $chapter->course_id) {
キャメルケースに修正しています。
$course_id→$courseId

2024-07-17 11:20 UTC, merged