JKA-945 マネージャーと配下のinstructorの講座情報のみにアクセスできるロジックの作成
yukihiroLaravel/juko_laravel pull request #610
Opened 2024-07-15 14:47 UTC by achoko3

## task
- jka-945
## 概要
- マネージャーと配下のinstructorの講座情報のみにアクセスできるロジックの作成
## 動作確認手順
- Postmanでマネージャー権限のあるinstructorでログイン
- Postmanで下記を入力
URL
[http://localhot:8080/api/v1/manager/course/{course_id}/attendance/status/this-month]
リクエスト
GET
Headers
Key→Referer, Origin
Value→http://localhost:3000/
- Postmanに正しいデータが返ってくることを確認
## 確認して欲しいこと
- 一つ前のタスクでインデントの修正をしていない箇所があったのでこちらで修正しています

2024-07-15 21:43 UTC, yukihiroLaravel requested changes
１点のみ指摘しました！

2024-07-15 21:43 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +
ここは空行１つ削除して
空行１行にしたほうがいいかとおもいました！

2024-07-16 11:06 UTC, Hikaru-Giannis approved these changes

2024-07-17 06:37 UTC, yukihiroLaravel approved these changes

2024-07-17 06:37 UTC, merged