JKA-815 講師側（マネージャー側）受講生詳細画面の学習状況API レスポンス整形のリソースファイル作成(とさか)
yukihiroLaravel/juko_laravel pull request #611
Opened 2024-07-16 04:13 UTC by tosakafullyremote

## issue
- https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-946

## 概要
- 講師側（マネージャー側）受講生詳細画面の学習状況を取得するAPIを作成　子課題
 4.レスポンス整形のリソースファイル作成

## 動作確認手順
- ポストマンのGETリクエストで/api/v1/instructor/attendance/{attendance_id}/statusを実行
{attendance_id}　に1を入れると下記が返る
manajerも同じレスポンスが返ることを確認済み

レスポンス
```
{
    "data": {
        "attendance_id": 1,
        "progress": 10,
        "course": {
            "course_id": 1,
            "title": "PHP入門講座",
            "status": "public",
            "image": "course/4459908b-3cdf-4521-94fa-c2a9746d92e1.png",
            "chapters": [
                {
                    "chapter_id": 1,
                    "title": "PHPとは？",
                    "status": "public",
                    "progress": 100
                },
                {
                    "chapter_id": 2,
                    "title": "PHPの基礎を学ぼう",
                    "status": "public",
                    "progress": 25
                },
                {
                    "chapter_id": 3,
                    "title": "PHPの応用にチャレンジしよう",
                    "status": "public",
                    "progress": 0
                }
            ]
        }
    }
}
```

{attendance_id}　に存在しない50やnを入れても、instructor、manajerも同じレスポンスが返ることを確認済み

## 考慮してほしいこと
- 今回は特にありません。

## 確認してほしいこと
- 今回は特にありません。

2024-07-16 11:11 UTC, Hikaru-Giannis requested changes

2024-07-16 11:11 UTC, kou-tech commented on app/Http/Resources/Manager/AttendanceStatusResource.php
> +            ],
移植元も同様の実装になっている場合でも修正して欲しいのですが、おそらく`data`の階層を取り除いても同様の結果が得られると思うので、修正をお願いできますか？

2024-07-16 17:29 UTC, tosakafullyremote commented on app/Http/Resources/Manager/AttendanceStatusResource.php
> +            ],
修正しました。`data`の階層を取り除いても同様の結果が得られました。
ご確認よろしくお願いいたします。
instructor の[AttendanceStatusResource.php]　も修正したのですが、他の方のタスクのため修正不要でしたでしょうか？

すみません。修正する前に聞けばよかったです。

2024-07-17 10:38 UTC, Hikaru-Giannis approved these changes

2024-07-17 10:40 UTC, Hikaru-Giannis commented on app/Http/Resources/Manager/AttendanceStatusResource.php
> +            ],
ケースによっては確認した方が良いこともありますが、今回は助かりました！
ありがとうございます！

2024-07-17 10:40 UTC, merged