マネージャー側（講師側） チャプター作成画面 選択済レッスンを公開/非公開にするAPI作成(Tokeshi)
yukihiroLaravel/juko_laravel pull request #617
Opened 2024-07-19 15:43 UTC by tokechan

## issue
- https://gut-familie.atlassian.net/browse/JKA-892

## 概要
- マネージャー側 ダッシュボード 本日のレッスン・チャプター完了数 取得API

## 動作確認手順
1.Postmanでマネージャー権限のあるinstructorでログイン

2.Postmanで下記を入力
```URL```
[http://localhot:8080//api/v1/manager/course/{course_id}/attendance/status/today](http://localhot:8080//api/v1/manager/course/%7Bcourse_id%7D/attendance/status/today)
リクエスト
```GET```

Headers
```Key``` Referer, Origin
```Value``` http://localhost:3000/
3.Postmanにデータが返ってくるを確認しました

- 子タスクを全てマージした上で、正しい値が返ってくることを確認

## 確認して欲しい事
プルリクのコンフリクトが起きて、色々と試行錯誤していたら元の記述したコードが全て消えてしました
なので```git reflog``` を活用して過去のコミットを調べて問題がないコミットに戻して(```git checkout e360f548```)に戻り、php docsを追加した上で、動作確認も問題ありませんでしたのでプルリクを出しております
このやり方でよかったのでしょうか？

2024-07-19 21:08 UTC, yukihiroLaravel requested changes
いくつかコメントしました！

2024-07-19 21:08 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +                    "message" => "Unauthorized: The authenticated instructor does not have permission to delete this attendance record",
他のメソッドを書き換えているのはダメですね！

2024-07-19 21:08 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            // Error response
この辺全体ですが、他のメソッドを書き換えているのはダメですね！

2024-07-21 09:58 UTC, Hikaru-Giannis approved these changes

2024-07-21 11:13 UTC, yukihiroLaravel approved these changes

2024-07-21 11:13 UTC, merged