JKA-938講師側レッスン選択削除空配列を返すルータ、コントローラの作成(シンタロウ）
yukihiroLaravel/juko_laravel pull request #618
Opened 2024-07-21 04:01 UTC by ShintaroYasuda

## 概要
- 講師側 チャプター作成画面 選択済レッスンを削除するAPI作成タスクの子タスク、空の配列を返すルーターとコントローラーの作成しました。

## 動作確認手順
- postmanを使ってインストラクターでログイン後http://localhost:8080/api/v1/instructor/course/1/chapter/1/lessons
にアクセスし、空の配列が返って来たのを確認しました。

2024-07-21 10:26 UTC, Hikaru-Giannis commented on routes/api.php
> +                            Route::delete('lessons', 'Api\Instructor\LessonController@bulkDelete');
すみません、URLのプリフィックスは`lessons`ではなく、`lesson`に修正をお願いします！

2024-07-22 13:58 UTC, ShintaroYasuda commented on routes/api.php
> +                            Route::delete('lessons', 'Api\Instructor\LessonController@bulkDelete');
変更し、pushしました。
ご確認お願いいたします。

2024-07-23 04:43 UTC, yukihiroLaravel requested changes
１点修正についてコメントしました！

2024-07-23 04:43 UTC, yukihiroLaravel commented on routes/api.php
>                                  Route::post('/', 'Api\Instructor\LessonController@store');
Kouさんが言われているのは
このあたりにルーティングを書き
URLは/のみにするということではないでしょうか？

2024-07-23 10:27 UTC, ShintaroYasuda commented on routes/api.php
>                                  Route::post('/', 'Api\Instructor\LessonController@store');
理解しました。
修正しましたので、ご確認をお願いいたします。

2024-07-23 14:31 UTC, Hikaru-Giannis approved these changes

2024-07-23 21:29 UTC, merged