Topic/jka 814/manager dashboard monthly lessons completion
yukihiroLaravel/juko_laravel pull request #621
Opened 2024-07-21 12:16 UTC by achoko3

2024-07-22 05:59 UTC, yukihiroLaravel requested changes
いくつか指摘させていただきました！

2024-07-22 05:59 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            * 本日のレッスン・チャプター完了数の取得API
ここのインデントもおかしいのと
この前の行もおかしいですね。

```
    /**
    * 今月のレッスン・チャプター完了数の取得API
 ```

こうならないとイケないはずです！

2024-07-22 05:59 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +     * 講座受講状況-今月
ここは、
* 今月のレッスン・チャプター完了数の取得API
という表示にしないといけないはずです！

2024-07-22 05:59 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +    */
ここは削除しましょう！

2024-07-23 04:40 UTC, yukihiroLaravel requested changes
概ねOKです😊
ただ、１点だけコメントしました！
ご確認ください！

2024-07-23 04:40 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +
ここに空行は不要かと思います！

2024-07-23 04:40 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +
ここに空行は不要かと思います！

2024-07-23 14:37 UTC, Hikaru-Giannis approved these changes

2024-07-23 21:28 UTC, yukihiroLaravel approved these changes
マージしました！
お疲れ様でした☺️

2024-07-23 21:28 UTC, merged