JKA-956マネージャー側（講師） 講師一覧APIの作成 3.フォームリクエストの作成（たまやま）
yukihiroLaravel/juko_laravel pull request #631
Opened 2024-07-29 21:18 UTC by masashi-tamayama

## タスク
- Closes #
- 子タスク https://gut-familie.atlassian.net/browse/JKA-956
- 親タスク https://gut-familie.atlassian.net/browse/JKA-830
## 概要
- **3.フォームリクエストの作成**

## 動作確認手順

**1. Postmanでマネージャー権限のあるinstructorでログイン**

- `database/seeds/InstructorSeeder.php`
`'type' => 'manager'`のinstructorを選ぶ

**2. Postmanにて下記を入力**
- URL
http://localhost:8080/api/v1/manager/instructor/index
- リクエスト
GET
- リクエストボディ
無し
- ヘッダー
![スクリーンショット 2024-07-28 212756](https://github.com/user-attachments/assets/c8292023-acea-44a2-880d-511f47150073)

- Pre-request Script にスクリプトを記述
![スクリーンショット 2024-07-28 213001](https://github.com/user-attachments/assets/2d049785-c291-4b00-b146-8a26f206a4d2)

- パラメーター（正しい値を入力した場合）
![スクリーンショット 2024-07-28 212819](https://github.com/user-attachments/assets/6ad617b4-0053-407a-9056-c975d9a4aae2)

- レスポンス（正しい値を入力した場合）
```
{
    "data": {
        "pagination": {
            "page": 1,
            "total": 3
        },
        "instructor": [
            {
                "instructor_id": 3,
                "nick_name": "Suzuki",
                "email": "test_instructor3@example.com",
                "profile_image": null,
                "created_at": "2024-07-21 16:16:50"
            },
            {
                "instructor_id": 2,
                "nick_name": "Hanako",
                "email": "test_instructor2@example.com",
                "profile_image": null,
                "created_at": "2024-07-21 16:16:50"
            },
            {
                "instructor_id": 1,
                "nick_name": "Yamada",
                "email": "test_instructor@example.com",
                "profile_image": "instructor/default.png",
                "created_at": "2024-07-21 16:16:50"
            }
        ]
    }
}
```
### バリデーションテスト

- 無効な page 値を入力した場合
![スクリーンショット 2024-07-29 105441](https://github.com/user-attachments/assets/0db51e3c-db1c-40f3-9002-48c2048ea32e)

- 無効な per_page 値を入力した場合
![スクリーンショット 2024-07-29 104851](https://github.com/user-attachments/assets/fa9ca945-aa04-4f74-8bf6-79dc663d2e4a)

- 無効な sort_by 値を入力した場合
![スクリーンショット 2024-07-29 105825](https://github.com/user-attachments/assets/e4290576-0636-42e3-a7ea-69d9b8280f52)

- 無効な order 値を入力した場合
![スクリーンショット 2024-07-29 110146](https://github.com/user-attachments/assets/6fb1a7ba-8072-4e01-a4df-8df67ec41688)

## 考慮して欲しいこと
- 特になし
## 確認して欲しいこと
- 特になし

2024-07-30 12:11 UTC, Hikaru-Giannis requested changes

2024-07-30 12:11 UTC, Hikaru-Giannis commented on app/Http/Requests/Manager/InstructorIndexRequest.php
> +            'sort_by' => ['string', 'in:email,nick_name,created_at'],
ここは、カスタムルールを作成しましょう！
次のファイルが参考になりそうです！参考元のファイル名は、変更を検討するくらい汎用的な名前になっていますね...。

`app/Rules/IndexSortByRule.php`

2024-07-31 00:27 UTC, masashi-tamayama commented on app/Http/Requests/Manager/InstructorIndexRequest.php
> +            'sort_by' => ['string', 'in:email,nick_name,created_at'],
`InstructorIndexSortByRule.php`ファイルを新たに作成しました。

旧　`'sort_by' => ['string', 'in:email,nick_name,created_at'],`
修正後　`'sort_by' => ['string', new InstructorIndexSortByRule()],`
この様に修正を行った後、動作確認を行いました。

2024-07-31 10:53 UTC, Hikaru-Giannis commented on app/Rules/InstructorIndexSortByRule.php
> +    ];
この方法は間違いではないという前提のもと、`app/Model/Instructor.php`で定数を定義してそちらの識別値を参照するようにお願いします！

2024-07-31 21:51 UTC, masashi-tamayama commented on app/Rules/InstructorIndexSortByRule.php
> +    ];
> この方法は間違いではないという前提のもと、

- 今一度バリデーションの動作確認を行い、バリデーションが正しく機能していることを確認しました。
「この方法は間違いではない」という前提の確認を行いました。

> `app/Model/Instructor.php`で定数を定義して

- `app/Model/Instructor.php`に
```
    // ソート対象フィールドの定数
    const SORT_BY_EMAIL = 'email';
    const SORT_BY_NICK_NAME = 'nick_name';
    const SORT_BY_CREATED_AT = 'created_at';
```
上記の定数を定義しました。

> そちらの識別値を参照するようにお願いします！

- `Instructor`モデルで定義した定数を`InstructorIndexSortByRule`クラスの`$validSortByFields`配列内で使用するように変更しました。

2024-08-01 13:51 UTC, Hikaru-Giannis commented on app/Rules/InstructorIndexSortByRule.php
> +    ];
`protected`プロパティで定義している意図はありますか？
特になければ、今回は比較的シンプルなバリデーションルールなので、直接配列を生成して問題ないのと、プロパティで定義するにも継承元とは関係がないので、`private`で問題ないかと思いました！

2024-08-01 22:04 UTC, masashi-tamayama commented on app/Rules/InstructorIndexSortByRule.php
> +    ];
> protectedプロパティで定義している意図はありますか？

- 定義している意図としては特にありません。

> 特になければ、今回は比較的シンプルなバリデーションルールなので、直接配列を生成して問題ないのと、プロパティで定義するにも継承元とは関係がないので、privateで問題ないかと思いました！

- 定義している意図が特にないのでプロパティを使わずに、passesメソッド内で直接配列を生成する方法を行いコード修正後、正しい値での動作と正常にバリデーションが動作する事を確認しました。
`app/Rules/InstructorIndexSortByRule.php`
```
    public function passes($attribute, $value)
    {
        $validSortByFields = [
            Instructor::SORT_BY_EMAIL,
            Instructor::SORT_BY_NICK_NAME,
            Instructor::SORT_BY_CREATED_AT,
        ];
        
        return in_array($value, $validSortByFields, true);
    }
```

2024-08-03 02:33 UTC, Hikaru-Giannis approved these changes

2024-08-03 02:33 UTC, merged