JKA-950 マネージャー側（講師側） チャプター作成画面 選択済レッスンを公開/非公開にするAPI作成のロジック作成（Tokeshi）
yukihiroLaravel/juko_laravel pull request #633
Opened 2024-07-30 17:50 UTC by tokechan

## issue
- https://gut-familie.atlassian.net/browse/JKA-950

## 概要
- [ マネージャー側（講師側） チャプター作成画面 選択済レッスンを公開/非公開にするAPI作成](https://gut-familie.atlassian.net/browse/JKA-892)のロジック作成

## 動作確認手順
- Postmanにて確認
- HTTPメソッド: ```PUT``` 
- URL:```/api/v1/manager/course/{course_id}/chapter/{chapter_id}/lesson/status```
- Headers
   X-XSRF-TOKEN:```{{XSRF-TOKEN}}```
   Referer:```http://localhost :3000/```
   Origin:```http://localhost :3000/```
- Body
  status: "public" or "private"
  lessons:[1,2,3,4,5]
- Pre-request Script
```
pm.environment.set("variable_key", "variable_value");
pm.sendRequest({
    url: 'http://localhost:8080/sanctum/csrf-cookie',
    method: 'GET'
}, function (error, response, { cookies }) {
    let xsrfCookie = cookies.one('XSRF-TOKEN');
    if (xsrfCookie) {
        let xsrfToken = decodeURIComponent(xsrfCookie['value']);
        console.log(xsrfToken);
        pm.request.headers.upsert({
            key: 'X-XSRF-TOKEN',
            value: xsrfToken,
        });                
        pm.environment.set('XSRF-TOKEN', xsrfToken);
    }
})
```

## 考慮して欲しいこと
- 特になし

## 確認して欲しい事
- エラーが発生しないこと
- 選択済みレッスンのステータスが変更できるかどうか
- マネージャーの配下（instructor）のレッスンのステータスが変更できるかどうか

2024-07-31 10:21 UTC, yukihiroLaravel requested changes
２点のみ指摘させていただきました！
お願いします！

2024-07-31 10:21 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/LessonController.php
> +     * @param LessonUpdateStatusRequest $request
ここのフォームリクエストファイルまだ決まっていないので一旦削除しておきましょう

2024-07-31 10:21 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/LessonController.php
> +            //エラーハンドリング、認可に失敗した場合エラーを返す
コメントアウト入れるなら、
下記のように、 } catch とインデントを合わせた方がいいかと思いました！

  // エラーハンドリング、認可に失敗した場合エラーを返す
  } catch (AuthorizationException $e) {

2024-07-31 11:15 UTC, Hikaru-Giannis approved these changes

2024-07-31 11:35 UTC, tokechan commented on app/Http/Controllers/Api/Manager/LessonController.php
> +     * @param LessonUpdateStatusRequest $request
なるほどです。承知しました。

2024-07-31 11:35 UTC, tokechan commented on app/Http/Controllers/Api/Manager/LessonController.php
> +            //エラーハンドリング、認可に失敗した場合エラーを返す
なるほどです。勉強になります。

2024-08-01 13:38 UTC, Hikaru-Giannis approved these changes

2024-08-01 23:25 UTC, yukihiroLaravel approved these changes

2024-08-01 23:25 UTC, merged