JKA-951 フォームリクエストの作成
yukihiroLaravel/juko_laravel pull request #636
Opened 2024-08-01 15:02 UTC by tokechan

## issue
- https://gut-familie.atlassian.net/browse/JKA-968 

## 概要
- [マネージャー側（講師側） チャプター作成画面 選択済レッスンを公開/非公開にするAPI作成 ](https://gut-familie.atlassian.net/browse/JKA-892)のフォームリクエストの作成 

## 動作確認手順
- Postmanにて確認
- HTTPメソッド: ```PUT```
- URL:```/api/v1/manager/course/{course_id}/chapter/{chapter_id}/lesson/status```
- Headers
   X-XSRF-TOKEN:```{{XSRF-TOKEN}}```
   Referer:```http://localhost :3000/```
   Origin:```http://localhost :3000/```
- Body
   status: "public" or "private"
   lessons:[1,2,3,4,5]
- Pre-request Script
```
pm.environment.set("variable_key", "variable_value");
pm.sendRequest({
    url: 'http://localhost:8080/sanctum/csrf-cookie',
    method: 'GET'
}, function (error, response, { cookies }) {
    let xsrfCookie = cookies.one('XSRF-TOKEN');
    if (xsrfCookie) {
        let xsrfToken = decodeURIComponent(xsrfCookie['value']);
        console.log(xsrfToken);
        pm.request.headers.upsert({
            key: 'X-XSRF-TOKEN',
            value: xsrfToken,
        });                
        pm.environment.set('XSRF-TOKEN', xsrfToken);
    }
})

```
## 考慮して欲しいこと
- 特になし

## 確認して欲しい事
- リクエストフォームがエラーを出さないかどうか
-

2024-08-01 23:33 UTC, yukihiroLaravel requested changes
１点コメントしました！

2024-08-01 23:33 UTC, yukihiroLaravel commented on app/Http/Requests/Manager/LessonPutStatusRequest.php
> +            //course_idは必須で整数であることを指定し、coursesテーブルのidカラムに存在すること、deleted_atカラムがNULLであることを確認
コメントはご自身でわかるように記述されているのだと思いますが
他のフォームリクエスト部分は原則コメントが付いていないので
他と比較したときに見づらいので
マージすべき内容としてはコメントは消しておきましょう！

2024-08-02 00:14 UTC, tokechan commented on app/Http/Requests/Manager/LessonPutStatusRequest.php
> +            //course_idは必須で整数であることを指定し、coursesテーブルのidカラムに存在すること、deleted_atカラムがNULLであることを確認
確かに、、、そうですね！削除いたします。

2024-08-03 02:39 UTC, Hikaru-Giannis approved these changes

2024-08-03 11:00 UTC, yukihiroLaravel approved these changes
マージしました！！

2024-08-03 11:00 UTC, merged