JKA-976 空の配列を返すルーターとコントローラの作成(Tokeshi)
yukihiroLaravel/juko_laravel pull request #639
Opened 2024-08-03 16:23 UTC by tokechan

##Issue
-  JKA-898 マネージャー側（講師側） チャプター作成画面 選択済レッスンを削除するAPI作成の子タスク 空の配列を返すルーターとコントローラの作成 https://gut-familie.atlassian.net/browse/JKA-976

## 動作確認手順
- Postmanにて確認
- HTTTPメソッド：```DELETE```
- URL：http://localhost:8080//api/v1/manager/course/{course_id}/chapter/{chapter_id}/lesson     
- Headers
   X-XSRF-TOKEN: ```{{XSRF-TOKEN}}```
   Referer: http://localhost:3000/
   Origin: http://localhost:3000/
- Body(row json形式)
   chapters: [1, 2, 3]
- Pre-request Script
```
pm.environment.set("variable_key", "variable_value");
pm.sendRequest({
    url: 'http://localhost:8080/sanctum/csrf-cookie',
    method: 'GET'
}, function (error, response, { cookies }) {
    let xsrfCookie = cookies.one('XSRF-TOKEN');
    if (xsrfCookie) {
        let xsrfToken = decodeURIComponent(xsrfCookie['value']);
        console.log(xsrfToken);
        pm.request.headers.upsert({
            key: 'X-XSRF-TOKEN',
            value: xsrfToken,
        });                
        pm.environment.set('XSRF-TOKEN', xsrfToken);
    }
})
```
## 考慮して欲しいこと
- 特になし
## 確認して欲しいこと
- 空配列が返ること
- エラーがないかどうか

2024-08-04 13:25 UTC, yukihiroLaravel requested changes
１点のみご確認お願いします！

2024-08-04 13:25 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/LessonController.php
> +     * 選択ずみレッスン削除API
細かいですが、ずみを漢字にしましょう！

2024-08-05 11:58 UTC, Hikaru-Giannis approved these changes

2024-08-05 12:10 UTC, yukihiroLaravel approved these changes

2024-08-05 12:10 UTC, merged