JKA-957マネージャー側（講師） 講師一覧APIの作成 4.レスポンス整形のリソースファイル作成（たまやま）
yukihiroLaravel/juko_laravel pull request #640
Opened 2024-08-03 23:48 UTC by masashi-tamayama

## タスク
- Closes #
- 子タスク https://gut-familie.atlassian.net/browse/JKA-957
- 親タスク https://gut-familie.atlassian.net/browse/JKA-830
## 概要
- **4.レスポンス整形のリソースファイル作成**
`app/Http/Resources/Manager/StudentIndexResource.php`ファイルを参考として作成

## 動作確認手順
**※動作確認方法は【JKA-956 3.フォームリクエストの作成】と同様です。**

**1. Postmanでマネージャー権限のあるinstructorでログイン**

- `database/seeds/InstructorSeeder.php`
`'type' => 'manager'`のinstructorを選ぶ

**2. Postmanにて下記を入力**
- URL
http://localhost:8080/api/v1/manager/instructor/index
- リクエスト
GET
- リクエストボディ
無し
- ヘッダー
![スクリーンショット 2024-07-28 212756](https://github.com/user-attachments/assets/c8292023-acea-44a2-880d-511f47150073)

- Pre-request Script にスクリプトを記述
![スクリーンショット 2024-07-28 213001](https://github.com/user-attachments/assets/2d049785-c291-4b00-b146-8a26f206a4d2)

- パラメーター（正しい値を入力した場合）
![スクリーンショット 2024-07-28 212819](https://github.com/user-attachments/assets/6ad617b4-0053-407a-9056-c975d9a4aae2)

- レスポンス（正しい値を入力した場合）
```
{
    "data": {
        "pagination": {
            "page": 1,
            "total": 3
        },
        "instructor": [
            {
                "instructor_id": 3,
                "nick_name": "Suzuki",
                "email": "test_instructor3@example.com",
                "profile_image": null,
                "created_at": "2024-07-21 16:16:50"
            },
            {
                "instructor_id": 2,
                "nick_name": "Hanako",
                "email": "test_instructor2@example.com",
                "profile_image": null,
                "created_at": "2024-07-21 16:16:50"
            },
            {
                "instructor_id": 1,
                "nick_name": "Yamada",
                "email": "test_instructor@example.com",
                "profile_image": "instructor/default.png",
                "created_at": "2024-07-21 16:16:50"
            }
        ]
    }
}
```
### バリデーションテスト

- 無効な page 値を入力した場合
![スクリーンショット 2024-07-29 105441](https://github.com/user-attachments/assets/0db51e3c-db1c-40f3-9002-48c2048ea32e)

- 無効な per_page 値を入力した場合
![スクリーンショット 2024-07-29 104851](https://github.com/user-attachments/assets/fa9ca945-aa04-4f74-8bf6-79dc663d2e4a)

- 無効な sort_by 値を入力した場合
![スクリーンショット 2024-07-29 105825](https://github.com/user-attachments/assets/e4290576-0636-42e3-a7ea-69d9b8280f52)

- 無効な order 値を入力した場合
![スクリーンショット 2024-07-29 110146](https://github.com/user-attachments/assets/6fb1a7ba-8072-4e01-a4df-8df67ec41688)

## 考慮して欲しいこと
- 特になし
## 確認して欲しいこと
- 特になし

2024-08-04 10:05 UTC, Hikaru-Giannis requested changes

2024-08-04 10:05 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/Instructor/InstructorController.php
> +        ]);
わざわざ連想配列にする必要はないので、コレクションクラスをそのまま渡しましょう！

2024-08-04 10:05 UTC, Hikaru-Giannis commented on app/Http/Resources/Manager/InstructorIndexResource.php
> +            'instructors' => $data->map(function ($instructor) {
mapの引数のクロージャーの引数を型宣言しましょう！

2024-08-04 12:43 UTC, masashi-tamayama commented on app/Http/Controllers/Api/Manager/Instructor/InstructorController.php
> +        ]);
`return new InstructorIndexResource($instructors);`
この一行の修正を行い
`InstructorIndexResource` のインスタンス化にコレクションをそのまま渡すように変更をしました。

`app/Http/Resources/Manager/InstructorIndexResource.php`
旧　　　$data = $this->resource['data'];
修正後　$data = $this->resource;
このように修正を行いました。

2024-08-04 12:51 UTC, masashi-tamayama commented on app/Http/Resources/Manager/InstructorIndexResource.php
> +            'instructors' => $data->map(function ($instructor) {
`'instructors' => $data->getCollection()->map(function (Instructor $instructor) {`
getCollection() メソッドを使用して、実際のデータ部分だけを取り出して操作出来るように修正を行いました。

2024-08-05 11:57 UTC, Hikaru-Giannis approved these changes

2024-08-05 12:17 UTC, merged