JKA-963 講師側選択削除ロジック認可処理(シンタロウ)
yukihiroLaravel/juko_laravel pull request #646
Opened 2024-08-07 11:16 UTC by ShintaroYasuda

## issue
- https://gut-familie.atlassian.net/browse/JKA-897
- https://gut-familie.atlassian.net/browse/JKA-939
- https://gut-familie.atlassian.net/browse/JKA-963

## 概要
- 講師側 チャプター作成画面 選択済レッスンを削除するAPI作成の子タスク、ロジックの作成について、認可処理の記述

## 動作確認手順
-postmanを使ってインストラクターでログイン後http://localhost:8080/api/v1/instructor/course/1/chapter/1/lessons
にアクセスし、trueが返って来たのを確認しました。

## 確認してほしい事
- trueが返ってきた事が認可処理機能の確認になるのか

2024-08-07 13:42 UTC, yukihiroLaravel requested changes
いくつか指摘しましたので
ご確認願います！

2024-08-07 13:42 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            if (!in_array($lesson->chapter->course->instructor_id, $instructorId, true)) {
今回は $instructorId の中身は配列ではなく１つの値しか入っていないと思うので
in_arrayではなく普通に比較演算子で比較
if (A !== B) {
でいいと思います！

2024-08-07 13:42 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                throw new ValidationErrorException('Invalid course.');
Invalid course.
というより
Invalid chapter.
かと思います！

2024-08-07 13:42 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            }
この下に
$courseId
とレッスンの属するcouse_idが合致するか？の
認可処理を行わないといけないと思われます！

2024-08-08 11:12 UTC, ShintaroYasuda commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            if (!in_array($lesson->chapter->course->instructor_id, $instructorId, true)) {
修正いたしました。

2024-08-08 11:13 UTC, ShintaroYasuda commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                throw new ValidationErrorException('Invalid course.');
修正いたしました。

2024-08-08 11:14 UTC, ShintaroYasuda commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            }
修正し、postmanで確認したところ、"Invalid instructor_id."と表示されました。どこか間違っているのでしょうか？

2024-08-08 21:22 UTC, yukihiroLaravel requested changes
コメントしました！！

2024-08-08 21:22 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                throw new ValidationErrorException('Invalid instructor_id.');
エラー内容的に
"Invalid instructor_id."
でしたらここが原因で
(int) を $instructorId に
付けていないからだと思いますよ！

2024-08-08 23:56 UTC, ShintaroYasuda commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                throw new ValidationErrorException('Invalid instructor_id.');
(int) を付けてみましたが、同じエラーが出てしまいます。

2024-08-09 09:45 UTC, ShintaroYasuda commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                throw new ValidationErrorException('Invalid instructor_id.');
postmanのリクエストボディが間違えておりました。ログイン中インストラクターに属するlessonIdを指定し、問題なくdeleteできました。
ご指摘ありがとうございました。

2024-08-09 11:35 UTC, Hikaru-Giannis approved these changes

2024-08-09 11:58 UTC, yukihiroLaravel approved these changes

2024-08-09 11:58 UTC, merged