JKA-977 ロジック作成
yukihiroLaravel/juko_laravel pull request #647
Opened 2024-08-08 03:16 UTC by tokechan

## Issue
- （JKA-898 マネージャー側（講師側） チャプター作成画面 選択済レッスンを削除するAPI作成
## 動作確認手順
- Postmanにて確認
- HTTTPメソッド：DELETE
- URL：[http://localhost:8080//api/v1/manager/course/{course_id}/chapter/{chapter_id}/lesson](http://localhost:8080//api/v1/manager/course/%7Bcourse_id%7D/chapter/%7Bchapter_id%7D/lesson)
- Headers
   X-XSRF-TOKEN: {{XSRF-TOKEN}}
   Referer: http://localhost:3000/
   Origin: http://localhost:3000/
- Body(row json形式) 
   lessons: [1, 2, 3]
- Pre-request Script
```
pm.environment.set("variable_key", "variable_value");
pm.sendRequest({
    url: 'http://localhost:8080/sanctum/csrf-cookie',
    method: 'GET'
}, function (error, response, { cookies }) {
    let xsrfCookie = cookies.one('XSRF-TOKEN');
    if (xsrfCookie) {
        let xsrfToken = decodeURIComponent(xsrfCookie['value']);
        console.log(xsrfToken);
        pm.request.headers.upsert({
            key: 'X-XSRF-TOKEN',
            value: xsrfToken,
        });                
        pm.environment.set('XSRF-TOKEN', xsrfToken);
    }
})
```
## 考慮してほしいこと
- 特になし

## 確認してほしいとこ
- 認可のところでうまくいってないです。受講状況のどこを変更すると正しい値が返ってくるのか理解ができたません。
　一旦、考えたコードを提出しますのでどこがおかしいかご教授いただきたいです。
- 
<img width="1405" alt="Screenshot 2024-08-08 at 12 14 55" src="https://github.com/user-attachments/assets/e57d3e65-4970-4b7a-8e4f-bb6209daa820">

<img width="1146" alt="Screenshot 2024-08-08 at 12 09 36" src="https://github.com/user-attachments/assets/aad38040-9a6a-441b-a0c2-7b2b3091e2cd">
<img width="1144" alt="Screenshot 2024-08-08 at 12 09 53" src="https://github.com/user-attachments/assets/256096a4-3d8f-4ff7-bfbb-b6c75a38f85b">
<img width="1144" alt="Screenshot 2024-08-08 at 12 09 53" src="https://github.com/user-attachments/assets/1be9fb5e-31c0-490e-a13a-91f181991973">
<img width="1140" alt="Screenshot 2024-08-08 at 12 12 10" src="https://github.com/user-attachments/assets/5fcd2cb9-d5e5-4939-987b-4abe6c7b67e7">

2024-08-09 10:20 UTC, yukihiroLaravel requested changes

2024-08-09 10:20 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/LessonController.php
> +            // $lesson->delete();
ここは不要ですね！

2024-08-09 11:33 UTC, Hikaru-Giannis requested changes

2024-08-09 11:33 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/LessonController.php
> +                });
こちらも他の実装に倣って、関数の引数に型宣言を適用しましょうか！

2024-08-09 11:33 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/LessonController.php
> +                }
ここはN+1問題が起きていると思いますので、解消をお願いできますか？

2024-08-09 15:39 UTC, tokechan commented on app/Http/Controllers/Api/Manager/LessonController.php
> +            // $lesson->delete();
すいません！！明らかに私の最終チェックミスです。修正します。

2024-08-09 16:34 UTC, tokechan commented on app/Http/Controllers/Api/Manager/LessonController.php
> +                });
型宣言をタイプヒンティングというんですね？？
調べてみたら、理解できましたが修正したものは当たっていますでしょうか？

2024-08-10 07:15 UTC, Hikaru-Giannis requested changes

2024-08-10 07:15 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        $lesson = Lesson::with('chapter.course')->whereIn('id', $lessonIds)->get();
364行目で、レッスン受講状態のリストも取得できる気がするのですがいかがでしょう？

2024-08-10 07:15 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/LessonController.php
> +                });
タイプヒンティングも間違いじゃないのですが、最近のバージョンだと引数のヒントだったころより制約要素が強まっている気がするので、`型宣言`で覚えて問題ないと思います！
次がマニュアルの記事です！
https://www.php.net/manual/ja/language.types.declarations.php

2024-08-11 09:25 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        $lesson = Lesson::with('chapter.course', 'attendances')->whereIn('id', $lessonIds)->get();
これだと受講(=`attendance`)のため、修正以前と実装が違うかと思いました！

2024-08-12 06:40 UTC, Hikaru-Giannis approved these changes

2024-08-13 00:07 UTC, yukihiroLaravel approved these changes
マージしました！
おつかれさまでした！

2024-08-13 00:08 UTC, merged