Feature/toke/jka 978/create formrequest
yukihiroLaravel/juko_laravel pull request #650
Opened 2024-08-09 22:41 UTC by tokechan

## Issue
- JKA-898 マネージャー側（講師側） チャプター作成画面 選択済レッスンを削除するAPI作成(親)
- https://gut-familie.atlassian.net/browse/JKA-978

## 概要
- マネージャー側（講師側） チャプター作成画面 選択済レッスンを削除するAPI作成のフォームリクエストの作成

## 動作確認手順
- Postmanにて確認
- HTTPメソッド: PUT
   URL:[http://localhost:8080//api/v1/manager/course/{course_id}/chapter/{chapter_id}/lesson](http://localhost:8080//api/v1/manager/course/%7Bcourse_id%7D/chapter/%7Bchapter_id%7D/lesson)
- Headers
   X-XSRF-TOKEN:{{XSRF-TOKEN}}
   Referer:http://localhost :3000/
   Origin:http://localhost :3000/
- Body
   lessons:[1,2,3,4,5]
- Pre-request Script
```
pm.environment.set("variable_key", "variable_value");
pm.sendRequest({
    url: 'http://localhost:8080/sanctum/csrf-cookie',
    method: 'GET'
}, function (error, response, { cookies }) {
    let xsrfCookie = cookies.one('XSRF-TOKEN');
    if (xsrfCookie) {
        let xsrfToken = decodeURIComponent(xsrfCookie['value']);
        console.log(xsrfToken);
        pm.request.headers.upsert({
            key: 'X-XSRF-TOKEN',
            value: xsrfToken,
        });                
        pm.environment.set('XSRF-TOKEN', xsrfToken);
    }
})

```

## 考慮してほしいこと
- 特になし

## 確認して欲しい事
- このファイルを作成してPostmanでの挙動確認はできましたが、エラーが起きないかどうかをみていただきたいです

2024-08-10 06:38 UTC, yukihiroLaravel requested changes
１点指摘しました！

2024-08-10 06:38 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/LessonController.php
> +    public function bulkDelete(LessonBulkDeleteRequest $request, $course_id, $chapter_id): JsonResponse
フォームリクエストファイルでmergeしているので
, $course_id, $chapter_id
この記述はまるまる不要になると思います！

2024-08-13 11:27 UTC, Hikaru-Giannis approved these changes

2024-08-13 19:57 UTC, yukihiroLaravel approved these changes
OKですのでマージしました！
おつかれさまでした！！

2024-08-13 19:57 UTC, merged