マネージャー側（講師側） チャプター作成画面 選択済チャプターを公開/非公開API作成topicブランチからdevelopへのプルリク（たわらつみだ）
yukihiroLaravel/juko_laravel pull request #656
Opened 2024-08-25 23:47 UTC by manabuandy

## 概要
- マネージャー側（講師側） チャプター作成画面 選択済チャプターを公開/非公開API作成topicブランチからdevelopへのプルリク

## 動作確認
Postmanにて確認

- http://localhost:8080/api/v1/manager/course/:course_id/chapter/status

- 講師側でログイン
- HTTPメソッド
- patchリクエスト
- ボディ（statusはpublicかprivateで実施、chaptersは1～5のいずれかで実施）
{
  "status": "public" or "private" ,
  "chapters": [1,2,3,4,5]
}　

- レスポンス内容
{
  "result": true
}

## 考慮してほしいこと
     特になし
## 確認してほしいこと
     特になし

2024-08-26 11:22 UTC, yukihiroLaravel requested changes
いくつか指摘しましたので
お手数ですがご確認ください！

2024-08-26 11:22 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +use App\Http\Requests\Manager\ChapterPatchRequest;//追加
特に追加されたわけではないので
この //追加
のコメントは削除しておきましょう！

2024-08-26 11:22 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +//追加
この空行１行と
//追加
の行も不要

2024-08-26 11:22 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +   /**追加
追加
という文字は不要ですね！

2024-08-26 13:30 UTC, manabuandy commented
指摘内容修正いたしました。よろしくお願いします。

2024-08-26 22:16 UTC, yukihiroLaravel requested changes
１点以外OKです！
それだけご確認ください！

2024-08-26 22:16 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/ChapterController.php
>      }
ここに１行だけ空行を入れておきましょう！

2024-08-27 10:32 UTC, manabuandy commented
チャプター一括更新API(公開・非公開切り替え)のメソッドの区別とコードが見やすくなるように空行を挿入しました。

2024-08-27 11:10 UTC, Hikaru-Giannis approved these changes

2024-08-27 13:42 UTC, yukihiroLaravel approved these changes

2024-08-27 13:42 UTC, merged