JKA989親-講師側 チャプター作成画面 チャプターに紐づく全レッスンを削除するAPI作成 子JKA995　JKA989リクエスト実装・空配列作成
yukihiroLaravel/juko_laravel pull request #659
Opened 2024-09-02 07:32 UTC by manabuandy

## 概要
- 子JKA995　JKA989リクエスト実装・空配列作成

## 動作確認
Postmanにて確認

- http://localhost:8080/api/v1/instructor/course/{course_id}/chapter/{chapter_id}/lessons/all

- 講師側でログイン

- DELETEリクエスト

- ヘッダー
X-XSRF-TOKEN　{{XSRF-TOKEN}}
Referer　http://localhost:3000
Origin　http://localhost:3000

- ボディ
`[
]`

- スクリプト
pm.environment.set("variable_key", "variable_value");
pm.sendRequest({
    url: 'http://localhost:8080/sanctum/csrf-cookie',
    method: 'GET'
}, function (error, response, { cookies }) {
    let xsrfCookie = cookies.one('XSRF-TOKEN');
    if (xsrfCookie) {
        let xsrfToken = decodeURIComponent(xsrfCookie['value']);
        console.log(xsrfToken);
        pm.request.headers.upsert({
            key: 'X-XSRF-TOKEN',
            value: xsrfToken,
        });                
        pm.environment.set('XSRF-TOKEN', xsrfToken);
    }
})

レスポンス
[　]

-
考慮してほしいこと
プルリクエストの記載内容（issueの内容）

確認してほしいこと
レスポンス内容がエラーなく
[　]が返ってきましたがこれでよろしいのでしょうか。

2024-09-02 14:08 UTC, yukihiroLaravel requested changes

2024-09-02 14:08 UTC, yukihiroLaravel commented on routes/api.php
> +                            Route::delete('lessons/all', 'Api\Instructor\ChapterController@deleteAllLessons');
URLも変更になりますが、
もっと下の94行目の下くらいにルーティングの場所を移動させて

http://localhost:8080/api/v1/instructor/course/{course_id}/chapter/{chapter_id}/lesson/all

としたほうがいいかなと思いました！
lessons ではなく
lesson と単数系に変えています。

2024-09-02 14:08 UTC, yukihiroLaravel commented on routes/api.php
> +                            Route::delete('lessons/all', 'Api\Instructor\ChapterController@deleteAllLessons');
また、chapterではなくlessonを消すので
ChapterControllerではなく
LessonControllerに変えたほうがいいと思いました。

2024-09-02 14:08 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +
chapterではなくlessonを消すので
記載場所は、ChapterControllerではなく
LessonControllerに変えたほうがいいと思いました。

2024-09-02 14:08 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +    public function deleteAllLessons()
関数名もこれより、
allDelete
などほうがシンプルでいい気がしました！

2024-09-03 10:29 UTC, manabuandy commented on routes/api.php
> +                            Route::delete('lessons/all', 'Api\Instructor\ChapterController@deleteAllLessons');
あっそうですね。チャプターに紐づく全レッスン削除ですからLessonControllerですね。ちょっとややこしくなりましたが理解できております。

2024-09-03 10:30 UTC, manabuandy commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +    public function deleteAllLessons()
関数名は特に決まりはないのですね。わかりました。アドバイスとおり修正いたします。

2024-09-03 11:38 UTC, manabuandy commented
リモートリポジトリにあるブランチが、ローカルブランチよりも新しいコミットを持っているため、git pushが拒否されたエラーが発生したため、リモート上のfeature/manabu/jka989/api_karahairetuをローカルブランチeature/manabu/jka989/api_karahairetuへpullして再度Postmanにて動作試験を実施良好、git add . commitしてpushし修正プルリクエストしております。

2024-09-07 23:43 UTC, manabuandy commented
内容を修正しました。
修正内容：apiのURL変更、メソッド変更、ChapterControllerへ空配列を削除し、LessonControllerへ記述しております。
よろしくお願いします。

2024-09-08 01:27 UTC, manabuandy commented
apiのalldeleteメソッドの記述間違いを修正。apiのメソッドを実行するコントローラ名称を修正。postman動作検証良好です。
よろしくお願いします。

2024-09-08 10:31 UTC, Hikaru-Giannis approved these changes

2024-09-08 11:58 UTC, yukihiroLaravel approved these changes

2024-09-08 11:58 UTC, merged