Instructor/CourseControllerにQueryServiceの作成→適用（共通化）(シンタロウ)
yukihiroLaravel/juko_laravel pull request #660
Opened 2024-09-03 16:51 UTC by ShintaroYasuda

## issue
- https://gut-familie.atlassian.net/browse/JKA-988

## 概要
- Instructor/CourseControllerにQueryServiceの作成→適用（共通化）

2024-09-04 10:20 UTC, Hikaru-Giannis approved these changes

2024-09-05 14:01 UTC, Hikaru-Giannis requested changes

2024-09-05 14:01 UTC, Hikaru-Giannis commented on app/Services/Course/QueryService.php
> +    }
これだと引数の主キーから取得する関数という解釈をされてしまうので、関数名を`getCoursesByInstructorId`に変更しましょうか！
コメントやphpdocも合わせて、変更をお願いします！

2024-09-05 19:49 UTC, ShintaroYasuda commented on app/Services/Course/QueryService.php
> +    }
ご指摘ありがとうございます。
変更いたしました。

2024-09-07 05:53 UTC, Hikaru-Giannis approved these changes

2024-09-07 15:55 UTC, merged