子-ロジックの作成<親-新権限マネージャー設立による..>(辻/G2)
yukihiroLaravel/juko_laravel pull request #661
Opened 2024-09-03 23:21 UTC by maxmindl

## 概要
<確認> ロジックの作成

## 動作確認
Postmanにて  
インストラクター側にログイン後  
http://localhost:8080/api/v1/instructor/course/2/chapter/2/lesson/2/status  
に送信。trueが返ってくることを確認。  
-HTTPメソッド：patch  
-"raw"(Body)にて、  
{  
"status": "public"  
}

## 考慮してほしい所
adminerにてお知らせの情報を見たいのですが、見ることができません。
(データのlesson,chapterなどの更新情報を見ることができない)

## 確認してほしい所
なし

2024-09-04 10:16 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        $lesson = Lesson::FindOrFail($request->lesson_id);
ドキュメント上は、findOrFailなので修正をお願いします！
将来的に動作が保証されてはいないので、なるべく正しいメソッド名を使うように心がけましょう！

2024-09-04 10:16 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        return response()->json($lesson);
ここでreturnすると以降のコードは実行されないです！

2024-09-04 10:16 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/LessonController.php
> +
lessonテーブルにinstructor_idはないと思います！

2024-09-06 12:13 UTC, maxmindl commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        return response()->json($lesson);
訂正しました！

2024-09-06 12:13 UTC, maxmindl commented on app/Http/Controllers/Api/Manager/LessonController.php
> +
消去しました。

2024-09-06 12:14 UTC, maxmindl commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        $lesson = Lesson::FindOrFail($request->lesson_id);
FindOrFailをfindOrFailへ訂正しました。

2024-09-07 06:04 UTC, Hikaru-Giannis requested changes

2024-09-07 06:04 UTC, kou-tech commented on routes/api.php
> +                                        Route::patch('status', 'Api\Manager\LessonController@updateStatus');
1つのAPIを実装するのに2つルーティングを設定しているのは、おかしい気がするので、修正をお願いします！

2024-09-07 06:04 UTC, kou-tech commented on app/Http/Requests/Manager/LessonPatchStatusRequest.php
> +            'status' => ['required', 'string',new LessonStatusRule()],
初回なので、これらのバリデーションルールが実際に機能する動作確認をされていない場合は動作確認をお願いします！

2024-09-07 06:04 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        }
プルリクエストの内容にレスポンスが`true`の動作確認の内容がありましたが、意図した挙動で`false`と`message`が返ってくることの動作確認もお願いします！

2024-09-07 06:04 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        /** @var Instructor $manager */
記述箇所が間違っているため、修正をお願いします。
記述している変数の1行上に記載する必要がありました！

2024-09-09 12:12 UTC, merged