Manager/CourseControllerにQueryServiceの適用（共通化）(シンタロウ)
yukihiroLaravel/juko_laravel pull request #665
Opened 2024-09-11 10:20 UTC by ShintaroYasuda

## issue
- https://gut-familie.atlassian.net/browse/JKA-1001

## 概要
- Manager/CourseControllerにQueryServiceの適用（共通化）

## 動作確認手順
- postmanを使ってマネージャー権限のあるインストラクター(instructor_id = 1)でログイン後、HTTPメソッド: get でhttp://localhost:8080/api/v1/manager/course/index
にアクセスし、コース一覧が表示されるのを確認（indexメソッド）
- postmanを使ってマネージャー権限のあるインストラクター(instructor_id = 1)でログイン後、HTTPメソッド: get で
http://localhost:8080/api/v1/manager/course/1
にアクセスし、コース（course_id=1）の内容が表示されるのを確認（showメソッド）

2024-09-14 00:53 UTC, yukihiroLaravel requested changes
少し指摘させていただきました！

2024-09-14 00:53 UTC, yukihiroLaravel commented on app/Services/Course/QueryService.php
> +    public function getCoursesByManagerInstructorId(int $instructorId): LengthAwarePaginator
ManagerIdもInstructorIdも同じものなので
getCoursesByInstructorIdでいいかなと思うのと、上にある関数と似ているので
getPaginatedCoursesByInstructorId
などページネーションを返すという意味に変更するのがベストかなと思いました！

@Hikaru-Giannis 
今関数内に
->paginate(5)
と直接記述していまっているのですが
（今までのこのプロジェクトの実装も含めて）
引数に5などを入れてページネーションの個数を指定できる形に
した方がいいと思われますでしょうか？
ご意見いただければと思います！

2024-09-14 01:18 UTC, Hikaru-Giannis approved these changes

2024-09-14 01:18 UTC, Hikaru-Giannis commented on app/Services/Course/QueryService.php
> +    public function getCoursesByManagerInstructorId(int $instructorId): LengthAwarePaginator
@yukihiroLaravel 
ページ数を引数指定する認識で問題ないです！

2024-09-18 03:29 UTC, ShintaroYasuda commented on app/Services/Course/QueryService.php
> +    public function getCoursesByManagerInstructorId(int $instructorId): LengthAwarePaginator
@yukihiroLaravel 
@Hikaru-Giannis 
関数名を変更し、引数指定するように修正いたしました。

2024-09-19 06:09 UTC, Hikaru-Giannis approved these changes

2024-09-21 02:10 UTC, Hikaru-Giannis approved these changes

2024-09-21 11:53 UTC, yukihiroLaravel approved these changes

2024-09-21 11:53 UTC, merged