親-新権限マネージャー設立による配下のinstructorに紐づくレッスン"ステータス"更新API作成 topicブランチからdevelopへのプルリク(G2/辻)
yukihiroLaravel/juko_laravel pull request #666
Opened 2024-09-11 13:02 UTC by maxmindl

## 概要
- 新権限マネージャー設立による配下のinstructorに紐づくレッスン"ステータス"更新API作成
   topicブランチからdevelopへのプルリク(JKA-985)
   
## 動作確認

Postmanにて
インストラクター側にログイン後
http://localhost:8080/api/v1/manager/course/1/chapter/1/lesson/1/status
などに送信。trueが返ってくることを確認。
<instructor_id 1>

instructor_id 2,3は"Forbidden, not allowed to use manager api"
instructor_id 4は、"invalid instructor_id"と返ってきました。

-HTTPメソッド: patch
-"raw"(Body)にて、
{
"status": "public"
}

## 考慮してほしいこと
topic/jka-985/manager_new_instructor_status_updateでブランチをプッシュしても、main developが保護状態となっていたため、compare: ブランチをtopic/jka-985/manager_new_instructor_status_update2 にしました。

## 確認してほしいこと
特になし

2024-09-12 12:26 UTC, kou-tech requested changes

2024-09-12 12:26 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/LessonController.php
> +use App\Http\Resources\Manager\LessonPatchResource;
これはインポートする必要ありますか？
最低限の実装を心がけましょう！

2024-09-12 12:37 UTC, maxmindl commented on app/Http/Controllers/Api/Manager/LessonController.php
> +use App\Http\Resources\Manager\LessonPatchResource;
余分なコードの確認を見逃していました..
たった今、修正を行ったので確認をお願いします。

2024-09-13 01:33 UTC, Hikaru-Giannis approved these changes

2024-09-13 01:33 UTC, merged