親-JKA989講師側 チャプター作成画面 チャプターに紐づく全レッスンを削除するAPI作成　子課題ロジック作成（たわらつみだ）
yukihiroLaravel/juko_laravel pull request #668
Opened 2024-09-12 10:44 UTC by manabuandy

## 概要
-  JJKA989ロジックの作成（たわらつみだ）

## 動作確認
Postmanにて確認

- http://localhost:8080/api/v1/instructor/course/:course_id/chapter/:chapter_id/lesson/all

### チャプターに紐づく全レッスンを削除の場合
- 講師側でログイン
email:test_instructor@example.com
password:Hash::make('password')

- DELETEリクエスト

- パラメータ
couse_id:1
chapter_id:2

- レスポンス
{
    "result": true,
}

### 指定された course_id がチャプターに関連付けられている course_id と一致するか確認の場合

- 講師側でログイン
email:test_instructor@example.com
password:Hash::make('password')

- DELETEリクエスト

- パラメータ
couse_id:1
chapter_id:4

- レスポンス
{
    "result": false,
    "message": "Invalid instructor_id."
}

### 現在の講師がチャプターの講座の作成者であるか確認の場合
- 講師側でログイン
email:test_instructor2@example.com
password:password'

- DELETEリクエスト

- パラメータ
couse_id:1
chapter_id:2

- レスポンス
{
    "result": false,
    "message": "Invalid instructor_id."
}

### 考慮してほしいこと
なし

### 確認したいこと
今回は、api.phpは変更しておりませんがFiles changedに変更履歴があります。問題ないのでしょうか。

2024-09-14 11:01 UTC, yukihiroLaravel requested changes
少し指摘しましたのでご確認ください！

2024-09-14 11:01 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                'message' => 'All lessons deleted successfully.',
成功したときは、'result' => true,　が帰ってくるだけでいいと思うので
'message' => 'All lessons deleted successfully.',
これは消しましょう！

2024-09-14 11:01 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +    public function allDelete(Request $request, int $course_id, int $chapter_id): JsonResponse
すみません、今更ですが
他の方の実装と揃えて
deleteAll
という関数名に変えましょう！

api.phpの方の関数名も同時に変更お願いします！

2024-09-14 11:18 UTC, manabuandy commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                'message' => 'All lessons deleted successfully.',
承知しました。'message' => 'All lessons deleted successfully.',の内容はフロント側で実行するためバックエンド側では不要という理解でよろしいでしょうか。

2024-09-14 11:21 UTC, manabuandy commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +    public function allDelete(Request $request, int $course_id, int $chapter_id): JsonResponse
承知しました。次回修正プルリクエストするときはapi.phpの内容もFiles Chengedに内容が表示されることになりますのでご了承ください。

2024-09-14 11:38 UTC, manabuandy commented
ご指摘内容を修正しております。よろしくお願いします。

2024-09-15 01:55 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            }
他の実装箇所と異なるかもしれませんが、認可チェック周辺の実装は`DB::beginTransaction();`実行前に行うようにお願いします！トランザクションが適切に終了されないと、データベース周辺で問題が起きたり、データの不整合の原因になるためでした！

2024-09-15 06:30 UTC, manabuandy commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            }
ご指摘ありがとうございます。つまり、許可チェックをパスした後にトランザクションを開始するということですね。で許可チェックが失敗した場合は、データベーストランザクションを開始することなくエラーを返すってことだろうなと予想します。ありがとうございます。

2024-09-16 06:06 UTC, Hikaru-Giannis approved these changes

2024-09-16 13:35 UTC, yukihiroLaravel approved these changes

2024-09-16 13:36 UTC, merged