マネージャー(講師側) チャプター作成画面 全チャプターを削除するAPI作成のロジック作成(松本)
yukihiroLaravel/juko_laravel pull request #669
Opened 2024-09-13 04:12 UTC by kazu-777

## 概要
- マネージャー(講師側) チャプター作成画面 全チャプターを削除するAPI作成のロジック作成

## 動作確認
- Postmanにて
http://localhost:8080/api/v1/manager/course/2/chapter/all
に送信。trueが返ってくることを確認。
メソッド: delete
リクエストボディ
{
    "chapters": [
        4,5
    ]
}
AdminerにてチャプターIDの4,5がdeleted_atになっていることを確認。

## 確認して欲しいこと
- 申し訳ございません。リクエストフォームまで作成してしまいました。
- チャプターを取得した後にチャプターが存在するかの確認の記述はいるのでしょうか？
よろしくお願いいたします。

2024-09-13 05:32 UTC, Hikaru-Giannis requested changes

2024-09-13 05:32 UTC, Hikaru-Giannis commented on app/Http/Requests/Manager/ChapterDeleteAllRequest.php
> +        ];
今回のAPIでは、`course_id`以外のリクエストパラメータは想定していません。
自身が記述したコードの意図と意味を説明できるようにしておきましょう。
また、成功ケースの動作確認はもちろんのこと、記述したバリデーションが正しく機能しているかの確認もできる範囲で行うようにお願いします！

2024-09-13 05:32 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +                }
この辺りは認可のチェック処理ですが、実際にエラーになることの動作確認はされましたでしょうか？

2024-09-16 09:10 UTC, kazu-777 commented on app/Http/Requests/Manager/ChapterDeleteAllRequest.php
> +        ];
承知いたしました。
記述したバリデーションが正しく機能しているか確認しました！

2024-09-16 09:25 UTC, kazu-777 commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +                }
動作確認できていなかったのでしました。
また、コースIDのほうは
$chapters = Chapter::where('course_id', $courseId)->get();で
course_idに関連するチャプターを取得しているため
不要かと思いましたので削除しました。

2024-09-17 10:01 UTC, Hikaru-Giannis requested changes

2024-09-17 10:01 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            DB::beginTransaction();
トランザクション開始は`try`の前に行いましょう！
`try`外に推奨されている理由としては、トランザクション開始で例外へ投げると、もしかすると正常に処理されない可能性があるためでした。

2024-09-17 10:01 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            ], 403);
ロールバック処理を追加して欲しいです！

2024-09-17 10:01 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            $chapters = Chapter::where('course_id', $courseId)->get();
Eager Loadingを考慮した実装に修正をお願いします！
あえて、単語の説明をしていないのは、一度調べてみて欲しいためでした！

2024-09-19 03:26 UTC, kazu-777 commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            DB::beginTransaction();
修正しました！

2024-09-19 03:26 UTC, kazu-777 commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            ], 403);
追加しました！

2024-09-19 03:27 UTC, kazu-777 commented on app/Http/Controllers/Api/Manager/ChapterController.php
> +            $chapters = Chapter::where('course_id', $courseId)->get();
修正しました！

2024-09-19 14:07 UTC, Hikaru-Giannis approved these changes

2024-09-20 11:41 UTC, merged