講師側 チャプター作成画面 チャプターに紐づく全レッスンを削除するAPI作成　子タスクフォームリクエストの作成（たわらつみだ）
yukihiroLaravel/juko_laravel pull request #671
Opened 2024-09-17 22:48 UTC by manabuandy

## 概要
-  JJKA989フォームリクエストの作成（たわらつみだ）

## 動作確認
Postmanにて確認

- http://localhost:8080/api/v1/instructor/course/:course_id/chapter/:chapter_id/lesson/all

### チャプターに紐づく全レッスンを削除の場合
- 講師側でログイン
email:test_instructor@example.com
password:Hash::make('password')

- DELETEリクエスト

- パラメータ
couse_id:1
chapter_id:2

- ボディ
{
    "course_id": 1,
    "chapter_id": 2
}

- レスポンス
{
    "result": true,
}

### 指定された course_id がチャプターに関連付けられている course_id と一致するか確認の場合

- 講師側でログイン
email:test_instructor@example.com
password:Hash::make('password')

- DELETEリクエスト

- パラメータ
couse_id:1
chapter_id:4

- ボディ
{
    "course_id": 1,
    "chapter_id": 4
}

- レスポンス
{
    "result": false,
    "message": "Invalid instructor_id."
}

### 現在の講師がチャプターの講座の作成者であるか確認の場合
- 講師側でログイン
email:test_instructor2@example.com
password:password'

- DELETEリクエスト

- パラメータ
couse_id:1
chapter_id:2

- ボディ
{
    "course_id": 1,
    "chapter_id": 2

- レスポンス
{
    "result": false,
    "message": "Invalid instructor_id."
}

### 考慮してほしいこと
なし

### 確認したいこと
①URL:
http://localhost:8080/api/v1/instructor/course/:course_id/chapter/:chapter_id/lesson/allを入力しパラメータを入力しております。動作検証良好
②URL
http://localhost/api/v1/instructor/course/1/chapter/2/lesson/all
とした場合、レスポンスでなにも返答がありません。
ここにこだわることなく
①のURLで行った方がよろしいのでようか。
ちなみにSwagger記載のURL（②の例）でもうまくいっていないため、①URLを利用しております。

2024-09-18 02:23 UTC, yukihiroLaravel requested changes
修正事項指摘させていただきました！
ご確認ください！
↓
https://www.loom.com/share/b38b44c5cb8e4b1c8c285a4e36dd5206

2024-09-19 12:42 UTC, manabuandy commented
ご指摘内容に基づき修正いたしました。ご確認お願いします

2024-09-19 14:25 UTC, yukihiroLaravel requested changes
指摘通りになっていない部分がありましたので
コメントしました。

修正後は、慎重に言われた通りできているか？を
必ず確認しましょう！

2024-09-19 14:25 UTC, yukihiroLaravel commented on app/Http/Requests/Instructor/LessonsAllDeleteRequest.php
> +            'chapter_id' => ['required', 'integer', 'exists:chapters,id'],
なぜdeleted_at, NULL が抜けているのでしょうか？

2024-09-19 14:25 UTC, yukihiroLaravel commented on app/Http/Requests/Instructor/LessonsAllDeleteRequest.php
> +    }
この関数は他にならって
authorize関数と
rules関数の間に
おくべきだと思います！

2024-09-22 05:28 UTC, Hikaru-Giannis approved these changes

2024-09-22 05:31 UTC, merged