#668 親-JKA989講師側 チャプター作成画面 チャプターに紐づく全レッスンを削除するAPI作成 topicブランチからdevelopへのプルリクの作成たわらつみだ）
yukihiroLaravel/juko_laravel pull request #674
Opened 2024-09-23 04:39 UTC by manabuandy

## 概要
-  JKA989 topicブランチからdevelopへのプルリクの作成（たわらつみだ）

## 動作確認
Postmanにて確認

- http://localhost:8080/api/v1/instructor/course/:course_id/chapter/:chapter_id/lesson/all

### チャプターに紐づく全レッスンを削除の場合
- 講師側でログイン
email:test_instructor@example.com
password:Hash::make('password')

- DELETEリクエスト

- パラメータ
couse_id:1
chapter_id:2

- レスポンス
{
    "result": true,
}

### 指定された course_id がチャプターに関連付けられている course_id と一致するか確認の場合

- 講師側でログイン
email:test_instructor@example.com
password:Hash::make('password')

- DELETEリクエスト

- パラメータ
couse_id:1
chapter_id:4

- レスポンス
{
    "result": false,
    "message": "Invalid instructor_id."
}

### 現在の講師がチャプターの講座の作成者であるか確認の場合
- 講師側でログイン
email:test_instructor2@example.com
password:password'

- DELETEリクエスト

- パラメータ
couse_id:1
chapter_id:2

- レスポンス
{
    "result": false,
    "message": "Invalid instructor_id."
}

### 考慮してほしいこと
なし

2024-09-23 14:55 UTC, kou-tech requested changes

2024-09-23 14:55 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            DB::beginTransaction();
トランザクションは、try前に行うことを推奨します！
というのもトランザクション開始次に問題がある場合に、データの不整合等の問題が少なからずあるためでした！

2024-09-23 14:55 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            $chapter->lessons()->delete();
1つ質問なのですが、レッスン削除後`lesson_attendances`テーブルのレコードがある場合にそのレコードはどのような状態になりますか？

2024-09-29 08:12 UTC, yukihiroLaravel requested changes
いくつかコメントしました！

2024-09-29 08:12 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +                    ], 403);
全体的にインデントがズレているので修正お願いします！

2024-09-29 08:12 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +            foreach ($chapter->lessons as $lesson) {
いい感じだと思いますが、
同じコントローラのbulkDeleteメソッドなどに倣って
foreachの代わりに
$lessons->each(function (
を使いましょう！

2024-10-02 14:46 UTC, yukihiroLaravel requested changes
１点指摘しました！

2024-10-02 14:46 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        // チャプターに紐づく全レッスンを削除
インデントがずれているので
開始位置を
$chapterの最初の文字に合わせるべき
かと思います！

2024-10-03 11:22 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        }
この実装は正しいですが、レッスンの数だけデータベースにアクセスする必要があります。
より効率的な方法として、レッスンIDのリストを抽出し、`whereIn`メソッドを使用することで、データベースアクセスを1回に減らすことができます。この方針での修正をお願いします。

2024-10-05 07:14 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/LessonController.php
> +        }
これだと結局ループ処理が走るので、whereInの利点を受けられないです。
ヒントとして、次のようなLaravelのコレクションメソッドを利用することで、レッスンのIDを抽出し、配列で取得できます。こちらを活用して、ループ処理をなくしましょう！

```php
// チャプターに紐づく全レッスンのIDを取得
$lessonIds = $chapter->lessons->pluck('id')->toArray();
```

2024-10-08 03:30 UTC, Hikaru-Giannis approved these changes

2024-10-08 04:10 UTC, yukihiroLaravel approved these changes
マージしました！

2024-10-08 04:10 UTC, merged