Student/AttendanceControllerにQueryServiceの適用（共通化）()
yukihiroLaravel/juko_laravel pull request #677
Opened 2024-09-26 11:44 UTC by ShintaroYasuda

2024-10-12 10:22 UTC, yukihiroLaravel requested changes
いくつか指摘しましたので、ご確認ください!!

2024-10-12 10:22 UTC, yukihiroLaravel commented on app/Services/Attendance/QueryService.php
> +    public function getAttendances(int $studentId, $request): Collection
これだと関数名が引数を含めて説明しきれていないと思いました。
僕なら今までの慎太郎さんがやったタスクも鑑みて
更に$requestではなく$request->search_wordを引数に渡すことで
下記のようにするかなと思います。

getAttendancesByStudentIdAndSearchWord

2024-10-12 10:22 UTC, yukihiroLaravel commented on app/Services/Attendance/QueryService.php
> +    public function getAttendanceInDetails(int $attendanceId): Attendance
これは今までの関数名を鑑みて
InDetailsという文字がなくて、attendanceIdでの検索なので
getAttendanceById
がいいかなと思いました。

2024-10-12 10:22 UTC, yukihiroLaravel commented on app/Services/Attendance/QueryService.php
> +    }
こちらやっていることが上記の
getAttendanceInDetails(getAttendanceById)の関数とほぼ合致しているので
上記の関数をそのまま使いまわせるかと思いました！

2024-10-12 10:22 UTC, yukihiroLaravel commented on app/Services/Attendance/QueryService.php
> +    }
あと、ここで取得しているのは明らかにChapterとは無関係で
Attendanceですね....!

2024-10-14 09:53 UTC, ShintaroYasuda commented on app/Services/Attendance/QueryService.php
> +    public function getAttendanceInDetails(int $attendanceId): Attendance
修正しました！

2024-10-14 09:54 UTC, ShintaroYasuda commented on app/Services/Attendance/QueryService.php
> +    public function getAttendances(int $studentId, $request): Collection
ありがとうございます。
修正しました！

2024-10-14 09:54 UTC, ShintaroYasuda commented on app/Services/Attendance/QueryService.php
> +    }
修正しました！

2024-10-15 02:34 UTC, yukihiroLaravel requested changes
おつかれさまでした！
これで一旦最後のレビューとはなりますが
少しコメントしました！
今後の参考にしてください！

2024-10-15 02:34 UTC, yukihiroLaravel commented on app/Services/Attendance/QueryService.php
> +    public function getAttendancesByStudentIdAndSearchWords(int $studentId, string $searchWord): Collection
なぜかWordsと複数形になっていますが

getAttendancesByStudentIdAndSearchWord

複数単語での検索は不可なので
単数系にしましょう！

2024-10-15 02:34 UTC, yukihiroLaravel commented on app/Services/Attendance/QueryService.php
> +    }
これはデータベースにアクセスして
データをとってきているというより、PHP上での変数内部の操作がメインかと思いますので
QueryServiceというデータベース操作に関わる関数として記述するのは正しくないかと思いますね！

2024-11-20 22:54 UTC, closed without merging