講師・マネージャー側それぞれのInstructorControllerにQueryServiceの適用（共通化）松本
yukihiroLaravel/juko_laravel pull request #679
Opened 2024-10-03 08:30 UTC by kazu-777

## 概要
- 講師・マネージャー側それぞれのInstructorControllerにQueryServiceの適用（共通化）
InstructorControllerのindexメソッドとshowメソッドにおいてQueryServiceのメソッドを作成してコントローラに適用。

## 動作確認
- 講師側のshowメソッド
Postmanにて
ID１にログイン後
http://localhost:8080/api/v1/instructor
に送信。
{
    "data": {
        "instructor_id": 1,
        "nick_name": "Yamada",
        "last_name": "山田",
        "first_name": "太郎",
        "email": "test_instructor@example.com",
        "profile_image": "instructor/default.png"
    }
}
ID1の情報が返ってくることを確認。

- マネージャー側のshowメソッド
Postmanにて
http://localhost:8080/api/v1/manager/instructor/1
に送信。
{
    "data": {
        "instructor_id": 1,
        "nick_name": "Yamada",
        "last_name": "山田",
        "first_name": "太郎",
        "email": "test_instructor@example.com",
        "profile_image": "instructor/default.png"
    }
}
の値が返ってくることを確認。
指定した講師IDが自分と配下の講師IDと一致しない場合はfalse。
また、整数ではない場合、Instructor_idがdeleted_atの場合にはバリデーションエラーになることを確認。

- マネージャー側のIndexメソッド
Postmanにて
http://localhost:8080/api/v1/manager/instructor/index?per_page=20&page=1&sort_by=email&order=desc
を送信。
{
    "data": {
        "instructors": [
            {
                "instructor_id": 3,
                "nick_name": "Suzuki",
                "email": "test_instructor3@example.com",
                "profile_image": null,
                "created_at": "2024-08-16 17:31:58"
            },
            {
                "instructor_id": 2,
                "nick_name": "Hanako",
                "email": "test_instructor2@example.com",
                "profile_image": null,
                "created_at": "2024-08-16 17:31:58"
            },
            {
                "instructor_id": 1,
                "nick_name": "Yamada",
                "email": "test_instructor@example.com",
                "profile_image": "instructor/default.png",
                "created_at": "2024-08-16 17:31:58"
            }
        ],
        "pagination": {
            "page": 1,
            "total": 3
        }
    }
}
が返ってくることを確認。
※per_pageが整数ではない場合や０や101の場合にはバリデーションエラーになることを確認。
※pageが整数ではない場合や0の場合はバリデーションエラーになることを確認。
※sort_byが文字列ではない場合やnick_name、email、created_atではない値の場合、バリデーションエラーになることを確
認。
※orderが文字列ではない場合やdescかascではない場合はバリデーションエラーになることを確認。

2024-10-03 11:26 UTC, Hikaru-Giannis commented on app/Services/Instructor/QueryService.php
> +    }
`subordinates`という用語を利用するのは間違いではないですが、一般的に親しみのある英語でなかったり、システム内で使われている用語ではないので、`withManagings`にしましょうか！

2024-10-03 11:27 UTC, Hikaru-Giannis commented on app/Services/Instructor/QueryService.php
> +    public function getInstructorsWithPagination(array $instructorIds, string $sortBy, string $order, int $perPage, int $page)
他の関数同様に関数の戻り値の型を指定するようにお願いします！

2024-10-04 08:57 UTC, kazu-777 commented on app/Services/Instructor/QueryService.php
> +    }
修正しました！

2024-10-04 08:57 UTC, kazu-777 commented on app/Services/Instructor/QueryService.php
> +    public function getInstructorsWithPagination(array $instructorIds, string $sortBy, string $order, int $perPage, int $page)
修正しました！よろしくお願いいたします。

2024-10-05 07:18 UTC, Hikaru-Giannis approved these changes

2024-10-05 23:30 UTC, yukihiroLaravel requested changes
１点指摘しました！

2024-10-05 23:30 UTC, yukihiroLaravel commented on app/Services/Instructor/QueryService.php
> +    public function getInstructorsWithPagination(array $instructorIds, string $sortBy, string $order, int $perPage, int $page): LengthAwarePaginator
getInstructorsWithPagination
この関数名ですが、ほかの方がされていた実装で
getPaginatedInstructors
というような関数名にされていたので
同様の関数名に変更した方がいいかなと思いました！

2024-10-06 05:36 UTC, kazu-777 commented on app/Services/Instructor/QueryService.php
> +    public function getInstructorsWithPagination(array $instructorIds, string $sortBy, string $order, int $perPage, int $page): LengthAwarePaginator
変更しました！

2024-10-06 10:13 UTC, Hikaru-Giannis approved these changes

2024-10-06 10:14 UTC, Hikaru-Giannis approved these changes

2024-10-06 11:17 UTC, yukihiroLaravel approved these changes

2024-10-06 11:17 UTC, merged