親-講師側/マネージャー側 チャプター選択削除時に受講中のチャプターは削除できないように変更　松本
yukihiroLaravel/juko_laravel pull request #683
Opened 2024-10-11 09:10 UTC by kazu-777

## 概要
- 親-講師側/マネージャー側 チャプター選択削除時に受講中のチャプターは削除できないように変更

## 確認したいこと
- Adminerで受講状況(lesson_attendancesのstatus)を変更してもPostmanで確認すると
反映されていないのですがどのように動作確認すればよろしいでしょうか。
また、そもそもコードもあっているかわからないのでそちらも見ていただきたいです。
よろしくお願いいたします。

2024-10-11 11:52 UTC, Hikaru-Giannis requested changes

2024-10-11 11:52 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                $attendedLessonIds = LessonAttendance::whereIn('lesson_id', $lessonIds)->where('status', LessonAttendance::STATUS_IN_ATTENDANCE)->pluck('lesson_id');
一旦はレッスンの乗降状態は、厳密に`受講中`でなくともレコードがある場合において、削除しないようにしたいので、次のようなコードで問題ありません！

```php
        $attendedLessons = LessonAttendance::whereIn('lesson_id', $lessonIds)->pluck('lesson_id');
```

2024-10-12 09:43 UTC, kazu-777 commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                $attendedLessonIds = LessonAttendance::whereIn('lesson_id', $lessonIds)->where('status', LessonAttendance::STATUS_IN_ATTENDANCE)->pluck('lesson_id');
変更しました！

2024-10-12 23:56 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                }
このコードでも機能しますが、各チャプターごとにデータベースにアクセスする実装になっています。
レッスンの情報は事前に取得できているため、そのIDのみを抽出し、1回のデータベースアクセスで解決できる方法があります。その方法で修正してもよろしいでしょうか？

2024-10-13 09:48 UTC, kazu-777 commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                }
大丈夫です。よろしくお願いいたします。

2024-10-15 00:25 UTC, Hikaru-Giannis requested changes

2024-10-15 00:25 UTC, Hikaru-Giannis commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                }
ループの中に記述する必要がない気がします。
次のコードでループ外に記述できないでしょうか？

```php
            $lessonIds = $chapters->pluck('lessons')->flatten()->pluck('id');
            if (LessonAttendance::whereIn('lesson_id', $lessonIds)->exists()) {
                throw new ValidationErrorException('Lesson attendance exists.');
            }

```

2024-10-15 08:05 UTC, kazu-777 commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +                }
ループ外に記述しました！よろしくお願いいたします。

2024-11-20 22:54 UTC, closed without merging