JKA1016 マネージャー側 講師一覧画面 所有講座数の追加ログインマネジャーID除外（たわらつみだ）
yukihiroLaravel/juko_laravel pull request #684
Opened 2024-10-11 14:20 UTC by manabuandy

## 概要
-  JKA1016 マネージャー側 講師一覧画面 所有講座数の追加ログインマネジャーID除外（たわらつみだ）

## 動作確認
- Postmanにて確認
- URL: http://localhost:8080///api/v1/manager/instructor/index
- 講師側でログイン
email:test_instructor1@example.com
password:password'
- GETリクエスト

- レスポンス
{
    "data": {
        "instructors": [
            {
                "instructor_id": 3,
                "nick_name": "Suzuki",
                "email": "test_instructor3@example.com",
                "profile_image": null,
                "created_at": "2024-08-18 20:25:02",
                "course_count": 2
            },
            {
                "instructor_id": 2,
                "nick_name": "Hanako",
                "email": "test_instructor2@example.com",
                "profile_image": null,
                "created_at": "2024-08-18 20:25:01",
                "course_count": 2
            }
        ],
        "pagination": {
            "page": 1,
            "total": 2
        }
    }

### 考慮してほしいこと
なし

### 確認したいこと
全体実装のルールはほぼ無視して記載しております。問題ありませんでしょうか。

2024-10-11 18:23 UTC, yukihiroLaravel requested changes

2024-10-11 18:23 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/Instructor/InstructorController.php
> +         /** @var Instructor $manager */
ここの先頭になぜかついているスペースは削除してください！

2024-10-11 18:23 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/Instructor/InstructorController.php
> +        // マネージャー自身のIDを除外
除外するコードはとくに書いていないので
下記のもとのコメントに戻しましょう
// 講師情報を取得

2024-10-12 04:11 UTC, Hikaru-Giannis approved these changes

2024-10-12 04:14 UTC, yukihiroLaravel approved these changes

2024-10-12 04:14 UTC, merged