JKA-1002(親タスクJKA-990) ロジック作成(西山しょうこ)
yukihiroLaravel/juko_laravel pull request #697
Opened 2024-11-12 12:23 UTC by Kujiran40

## issue

- Closes JKA-1002(親タスクJKA-990) ロジック作成(西山しょうこ)

## 概要

- マネージャー側　チャプターに紐づくレッスン全削除API作成の子課題「ロジックの作成」

## 動作確認手順

Postmanで、以下のテストを実施
- ログイン中の講師（マネージャー権限）が作成したチャプターに紐づくレッスンの全削除
 （チャプター８レッスン９は、私がAdminerで作成したものです）
　URL：　api/v1/manager/course/5/chapter/8/lesson/all
　"result": true

- 出席のあるレッスンがあれば削除を許可しない
　URL：　api/v1/manager/course/1/chapter/2/lesson/all
　 "result": false,
    "message": "This lessons contains attendance."

- 講師の管理下にあるインストラクターが作成したチャプターに紐づくレッスンの全削除
 （チャプターID４の中のレッスン７は、確か私がAdminerで作成したものです）
　URL：　api/v1/manager/course/2/chapter/4/lesson/all
　"result": true

## 確認して欲しいこと
-　Postmanでのテストが、過不足なくできているかご確認よろしくお願いいたします。 
- 　コードは大半コピペですが、一部自分で書いたところもあるのでご確認よろしくお願いいたします。

2024-11-12 13:32 UTC, yukihiroLaravel requested changes
少し修正願います！

2024-11-12 13:32 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        $chapter = Chapter::with('course')->findOrFail($chapter_id);
548行目以下に移動

2024-11-12 13:32 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/LessonController.php
> +                ]);
インデント修正

2024-11-12 13:46 UTC, Kujiran40 commented on app/Http/Controllers/Api/Manager/LessonController.php
> +                ]);
修正しました！

2024-11-12 13:46 UTC, Kujiran40 commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        $chapter = Chapter::with('course')->findOrFail($chapter_id);
移動しました！

2024-11-13 11:12 UTC, kou-tech requested changes

2024-11-13 11:12 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/LessonController.php
> +        if (!in_array($chapter->course->instructor_id, $instructorIds)) {
in_arrayは第３引数がとても大事なので、調べて指定するようにお願いします！

2024-11-13 11:12 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/LessonController.php
> +            ], 403);
認可失敗時のエラー方針を決めまして、次のように対応して欲しいです！
同じメソッド内の403を返しているところを同様の修正で対応をお願いします！

```php
throw new AuthorizationException('例）エラーメッセージ');
```

2024-11-14 14:44 UTC, kou-tech approved these changes

2024-11-14 14:45 UTC, merged