空の配列を返すルーターとコントローラー作成
yukihiroLaravel/juko_laravel pull request #704
Opened 2024-11-16 02:08 UTC by mizuki012

Postman にて、
①　インストラクターでログイン
②　【DELETE】localhost:8080/api/v1/instructor/course/1/chapter/all
でsendを押し、結果として　[ ] が返ってきました。

2024-11-16 09:04 UTC, yukihiroLaravel requested changes
これだと何のタスクか見た人がわかりづらいので
チーム開発のときのように、プルリクに何のタスクか書いて、
下記のURLも載せましょう！

・講師側 チャプター作成画面 全チャプターを削除するAPI作成
https://gut-familie.atlassian.net/jira/software/projects/JKA/boards/1/backlog?selectedIssue=JKA-991

あともう１点指摘しましたのでご確認ください！

2024-11-16 09:04 UTC, yukihiroLaravel commented on routes/api.php
> +                    Route::delete('/', 'Api\Instructor\CourseController@delete');
この１行は無関係なので移動したらダメですね💦

2024-11-17 11:36 UTC, yukihiroLaravel approved these changes

2024-11-18 10:05 UTC, kou-tech approved these changes

2024-11-18 11:10 UTC, yukihiroLaravel approved these changes

2024-11-18 11:10 UTC, merged