マネージャー側_受講状況取得APIの作成(大川)
yukihiroLaravel/juko_laravel pull request #706
Opened 2024-11-16 11:28 UTC by ookawa999jp

## issue
- JKA-1041 マネージャー側_受講状況取得APIの作成

## 動画を見てInstructor側を参考にして実装した

swaggerのレスポンスの仕様が、InstructorとManagerで同じだった
他のタスクもInstructorとManagerで、ほぼ同じロジックも過去に見た。

違いは、
「自分と配下の講師の講座でない場合はエラーを返す」
これがあるかどうかの違いのケースが他にもあったが、

今回の分のその違いだけかな。思いました。
その方向性でしました。

なお、
Instructor側のshow()にあった
$chapters = Chapter::with('lessons.lessonAttendances')->where('course_id', $courseId)->get();
の
「with('lessons.lessonAttendances')->」部分は不要だったので

当Manager側のshowの実装時には、削りました

## テスト

https://www.dropbox.com/scl/fi/mg0im4v7w8jfcg71xxnyj/.xlsx?rlkey=dzby7481u6o4q0l0926yu050q&dl=0

で、

左側のInstructorのshow()
と、
右側のManagerのshow()
でレスポンスを比較し、一致を確認してます

swaggerのレスポンスの記載は、同じでした。

php artisan migrate:fresh --seedしたイメージのデータ状態で
course_id=4で動かしたら
```
        $course = Course::findOrFail($courseId);
        if (!in_array($course->instructor_id, $instructorIds, true)) {
            // 自分と配下の講師の講座でない場合はエラーを返す
            return response()->json([
                'result'  => false,
                'message' => "Forbidden, not allowed to access this course.",
            ], 403);
        }
の中に入って、レスポンス
{
    "result": false,
    "message": "Forbidden, not allowed to access this course."
}
が返ってくるのを確認した
```

## 追記
composer analyzeの対応をした

2024-11-16 22:42 UTC, kou-tech requested changes

2024-11-16 22:42 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            ], 403);
他の実装を参考にして、実装いただきありがとうございます！
ただ、すみません。以前のように`AuthorizationException`を使って、例外を投げていただいてよろしいでしょうか？
メッセージはそのままで問題ありません。
また、ログの出力は不要なのと、そのためによる`try/catch`もなしで問題ないです！

2024-11-16 22:42 UTC, kou-tech commented on routes/api.php
> +                                Route::get('', 'Api\Manager\AttendanceController@show');
こちらの方法でも動作上は問題ないかもしれませんが、他のコードとの統一性を保つため、また、Laravelのドキュメントに記載されている推奨方法に従うため、次のように修正をお願いしたいです！

```php
Route::get('/', 'Api\Manager\AttendanceController@show');
```

2024-11-17 00:56 UTC, ookawa999jp commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            ], 403);
```
        if (!in_array($course->instructor_id, $instructorIds, true)) {
            // 自分と配下の講師の講座でない場合はエラーを返す
            throw new AuthorizationException(
                "Forbidden, not allowed to access this course."
            );
        }
```

対応しました。

2024-11-17 00:56 UTC, ookawa999jp commented on routes/api.php
> +                                Route::get('', 'Api\Manager\AttendanceController@show');
対応しました。

2024-11-17 01:15 UTC, ookawa999jp commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            ], 403);
対応後、下記のように出ました
```
{
    "message": "Forbidden, not allowed to access this course.",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException",
    "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php",
    "line": 638,
    "trace": [
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php",
            "line": 582,
            "function": "prepareException",
            "class": "Illuminate\\Foundation\\Exceptions\\Handler",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/app/Exceptions/Handler.php",
            "line": 53,
            "function": "render",
            "class": "Illuminate\\Foundation\\Exceptions\\Handler",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 51,
            "function": "render",
            "class": "App\\Exceptions\\Handler",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 146,
            "function": "handleException",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/app/Http/Middleware/EnsureIsManager.php",
            "line": 28,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "App\\Http\\Middleware\\EnsureIsManager",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/app/Http/Middleware/EnsureIsInstructor.php",
            "line": 26,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "App\\Http\\Middleware\\EnsureIsInstructor",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 51,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
            "line": 161,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
            "line": 92,
            "function": "handleRequest",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php",
            "line": 64,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Auth\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php",
            "line": 25,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 144,
            "function": "Laravel\\Sanctum\\Http\\Middleware\\{closure}",
            "class": "Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/sanctum/src/Http/Middleware/AuthenticateSession.php",
            "line": 44,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Laravel\\Sanctum\\Http\\Middleware\\AuthenticateSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php",
            "line": 88,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 121,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 64,
            "function": "handleStatefulRequest",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/html/laravelapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 183,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "t [...]

2024-11-17 01:17 UTC, ookawa999jp commented on routes/api.php
> +                                Route::get('', 'Api\Manager\AttendanceController@show');
対応後、下記のように、対応前と同様、レスポンス返ってます
```
{
    "data": {
        "chapters": [
            {
                "chapter_id": 1,
                "title": "PHPとは？",
                "completed_count": 2
            },
            {
                "chapter_id": 2,
                "title": "PHPの基礎を学ぼう",
                "completed_count": 2
            },
            {
                "chapter_id": 3,
                "title": "PHPの応用にチャレンジしよう",
                "completed_count": 0
            }
        ],
        "students_count": 2
    }
}
```

2024-11-17 01:20 UTC, ookawa999jp commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +            ], 403);
laravel.logは自動ではでないようです。
＞ログの出力は不要
とのことで、スルーしてます。

2024-11-18 09:54 UTC, merged