マネージャー側 受講生ログイン率取得APIの作成(大川)
yukihiroLaravel/juko_laravel pull request #711
Opened 2024-11-19 15:00 UTC by ookawa999jp

## issue
- JKA-1042 マネージャー側 受講生ログイン率取得APIの作成

自分と配下の講師の講座でない場合はエラーを返す
のチェック以外は、Instructor側と同じ実装にした。
エラー系は、Instructor側、Manager側ともに、例外処理に変更した

## テスト_courseの認可

courseの認可は、

https://www.dropbox.com/scl/fi/bzspdixqcb0lh4n1jjopg/cource-JKA-1042_-_.xlsx?rlkey=0dviv4kysfdxcnpul1dnyrx6j&dl=0
の
courceのJKA-1042_テスト_エラー系.xlsx
で、
左側、Instructor
右側、Manager
AuthorizationExceptionで、403
laravel.logはでない（想定どうり)

## テスト_periodのelse制御

periodは、バリデーションチェックしてるため、else句に来るのはバグである。
そのため、例外処理とした、普通のExceptionを投げると
laravel.logにもスタックトレース出力され、postmanで500でかえってくる
( 例外に食わせたメッセージもレスポンスの先頭部に出力されています )

そのテストは、

https://www.dropbox.com/scl/fi/1go6sc2mqt5ey216k1bjb/period-JKA-1042_-_.xlsx?rlkey=m0ca09mknkkb62up3k3l3y12b&dl=0
の
periodのJKA-1042_テスト_エラー系.xlsx
で、
左側、Instructor
右側、Manager
500でかえってくる
laravel.logにスタックトレース出力。

★バリデーションチェックがOKになった後、ロジックが動いてる時に、値を変えないと
該当の分岐にいかないため、実行時にデバッガーで、periodの値を変更して、確認してます。

periodで、3種類以外の他の、
★普通のバリデーションチェックが効いてるのは、目視で確認してます。★
メソッドの先頭位置まで制御が来ません。

## 正常系は、Instructor側と同じものをもってきただけなので、１パターンだけ比較し確認した

https://www.dropbox.com/scl/fi/1zlkhgz3p433m9huxlhez/JKA-1042_-_.xlsx?rlkey=s2bt08npduch4ko7gqsdrfq00&dl=0
の
JKA-1042_テスト_正常系.xlsx
で
左側、Instructor
右側、Manager
で、200がかえる
レスポンス両者同じ

2024-11-20 22:51 UTC, kou-tech requested changes

2024-11-20 22:51 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/AttendanceController.php
157〜167行目は、PHPのバージョンが8.3になったため、match式でリファクタリングができるのではないかと考えています。そちらで修正していただけますでしょうか？
https://www.php.net/manual/ja/control-structures.match.php

複数のif-elseif文を1つのmatch式にまとめられ、コードがよりコンパクトになり、if-elseif文と比べて、わずかながら実行速度が向上するなどの利点があると考えています。

2024-11-20 22:51 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/AttendanceController.php
217〜228行目は、PHPのバージョンが8.3になったため、match式でリファクタリングができるのではないかと考えています。そちらで修正していただけますでしょうか？
https://www.php.net/manual/ja/control-structures.match.php

複数のif-elseif文を1つのmatch式にまとめられ、コードがよりコンパクトになり、if-elseif文と比べて、わずかながら実行速度が向上するなどの利点があると考えています。

2024-11-20 22:51 UTC, kou-tech commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +    }
`Attendance`モデルに静的メソッドを定義して、この関数を共通化していただきたいです！

共通化をあまり行わない方針ではあるのですが、この関数は外部要因に依存しない純粋な関数であるため、共通化が適切だと判断しました。

また、新たにユーティリティファイルを作成してこの関数を定義するよりも、関連性のあるAttendanceモデルに定義する方が、コードの管理がしやすくなると考えました。これにより、不必要なファイルの増加を避け、コードの整理整頓を維持できます。そのため、一旦は`Attendance`モデルに定義していただきたいです！

2024-11-21 12:01 UTC, ookawa999jp commented on app/Http/Controllers/Api/Manager/AttendanceController.php
対応しました。
事後報告が２点あります。
1点目)
default => throw new Exception('Invalid period. [' . $request->period . ']'),
なくても、match式が専用の例外を出して、postmanに500返ってきて、laravel.logにも出ることは
承知の上だが、
default記述しないと、composer analyzeで未処理分があるということで怒られましたので
default => throw new Exception('Invalid period. [' . $request->period . ']'),
を書いてます

2点目)
->subWeek()
などはインスタンスそのものを書き換えてます。
$endDateという名前の変数でインスタンスそのものを書き換えて
同じインスタンスを$periodAgoという変数で指し示すような実装になってました。
***
$nowDateの変数で現在の日時を取得後
それのインスタンスをcopyしたものについて、->subWeek()で更新したインスタンスを
$periodAgoを指し示すが
$nowDateがさしているインスタンスについては、現在の日時を保持しているということになってる
実装であるほうが
直感に反しないため。そうしました。

2024-11-21 12:01 UTC, ookawa999jp commented on app/Http/Controllers/Api/Manager/AttendanceController.php
> +    }
対応しました。

2024-11-22 06:23 UTC, kou-tech approved these changes

2024-11-22 06:26 UTC, merged