JKA-1029 親タスク-マネージャー側 講師詳細画面 講座一覧APIに更新日を追加(中川)
yukihiroLaravel/juko_laravel pull request #715
Opened 2024-11-21 14:18 UTC by 396sss

## issue
･Closes JKA-1029 featureブランチからdevelopブランチへのプルリク（なかがわ）

## 概要
・親タスク-マネージャー側 講師詳細画面 講座一覧APIに更新日を追加　『featureブランチからdevelopブランチへのプルリク』

##動作確認手順
-Postmanで、以下のテストを実施
講師詳細画面にログイン
http://localhost:8080/api/v1/manager/instructor/:instructor_id/course/index

更新日時 "updated_at": "2024-11-15T12:22:28.000000Z"の記載があることを確認
{
    "data": {
        "courses": [
            {
                "course_id": 2,
                "title": "Laravel入門講座",
                "status": "public",
                "updated_at": "2024-11-15T12:22:28.000000Z"
            },
            {
                "course_id": 6,
                "title": "Vue入門講座",
                "status": "public",
                "updated_at": "2024-11-15T12:22:28.000000Z"
            }
        ],
        "pagination": {
            "page": 1,
            "total": 2
        }
    }
}

2024-11-22 13:51 UTC, yukihiroLaravel approved these changes
問題ないかと思います！

2024-11-23 10:21 UTC, kou-tech requested changes

2024-11-23 10:21 UTC, kou-tech commented on app/Http/Resources/Manager/InstructorCourseIndexResource.php
> +                "updated_at" => $course->updated_at,
日時のフォーマットを`Y/m/d H:i:s`形式に修正をお願いしたいです！

```txt
"updated_at": "2024-11-15T12:22:28.000000Z"
```

参考として`app/Http/Resources/Student/StudentShowResource.php`などをご確認ください！

2024-11-26 13:39 UTC, 396sss commented on app/Http/Resources/Manager/InstructorCourseIndexResource.php
> +                "updated_at" => $course->updated_at,
日時のフォーマットをY/m/d H:i:s形式に変更しました。
ご確認お願いいたします。

2024-11-27 09:33 UTC, kou-tech approved these changes

2024-11-27 09:33 UTC, merged