JKA-1051(親タスクJKA-1044) ロジックの作成(西山しょうこ)
yukihiroLaravel/juko_laravel pull request #716
Opened 2024-11-22 01:17 UTC by Kujiran40

## issue

- Closes JKA-1051(親タスクJKA-1044)ロジックの作成(西山しょうこ)

## 概要

- 講師側　お知らせ削除（１つだけ）のAPI作成　子課題「ロジックの作成」

## 動作確認手順

PostmanとAdminerで、以下のテストを実施

- ログイン中の通常講師（id:2）が作成したお知らせ（id:2） を削除するテスト
【Postman】
　　URL：　http://localhost:8080/api/v1/instructor/notification/2
　　"result": true
【Adminer】
　　お知らせ２　が削除された。
　　中間テーブル（生徒id:2 とお知らせid:2 の関係を示すデータ）も、削除された。

- 別の講師（id:4）でログインした状態で、講師 id:2 が作ったお知らせ（id:2）を削除するテスト
【Postman】
　　URL：　http://localhost:8080/api/v1/instructor/notification/2
　　"result": 403 Forbidden
　　"message": 　"Invalid instructor_id.",

- 今回のテストで削除された　お知らせ（id:2）と、中間テーブルのデータ（生徒 id:2 とお知らせid:2 の繋がり）は、Adminerで復元済みです。

## ご確認をお願いしたいこと
Postmanでのテストがまだ慣れていないこともあり不安です。
上記のテストが、今回のタスク内容にきちんと沿っているか（的を得ているか）、ご確認とご指摘をいただきたいです。

2024-11-22 11:21 UTC, yukihiroLaravel requested changes
テストはご記載の通りで
ログイン講師がつくっていないお知らせと
ログイン講師がつくったお知らせを
比較するテストで問題ないと思います！

ほぼ問題ないですが、
超細かい点ですが追加で指摘しました！

2024-11-22 11:21 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            DB::commit();
他にならってここに空行を念の為入れておきましょう！

2024-11-22 11:21 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            Log::error($e);
他にならってここに空行を念の為入れておきましょう！

2024-11-22 11:28 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            ], 500);
エラー設計方針を見直し、ここは`throw $e`でお願いしたいです！
可能であれば、参考元のコードの方も修正をお願いします！

2024-11-23 12:54 UTC, Kujiran40 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            ], 500);
承知しました！
参考元の、「マネージャー側」NotificationControllerのdeleteメソッドも、変更しました。

2024-11-23 12:54 UTC, Kujiran40 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            DB::commit();
承知しました！

2024-11-23 12:59 UTC, Kujiran40 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            Log::error($e);
ありがとうございます！
return response…　の代わりに、throw $e となりました（今回は他にならって空欄無しにしました）

2024-11-24 15:41 UTC, kou-tech approved these changes

2024-11-24 21:57 UTC, yukihiroLaravel approved these changes
マージしました！

2024-11-24 21:57 UTC, merged