JKA-1057 Manager/NotificationControllerとInstructor/NotificationControllerの未対応部分にthrow new AuthorizationExceptionとthrow $eの適用（西山しょうこ）
yukihiroLaravel/juko_laravel pull request #722
Opened 2024-11-27 08:56 UTC by Kujiran40

## issue

- Closes JKA-1057 Manager/NotificationControllerとInstructor/NotificationControllerの未対応部分にthrow new AuthorizationExceptionとthrow $eの適用（西山しょうこ）

## 概要

- マネージャ側&講師側　NotificationControllerの未対応部分の403/500エラーの記述方法を変更

## 動作確認手順（１つ失敗）
Postmanにて以下の方法でそれぞれテスト

**<ins>マネージャ側　NotificationController</ins>　マネージャー（ id:1 ）でログイン**

＜403をthrow new AuthorizationException（）に変更し、アクセス権限のテストを実施。それぞれ指定のエラーメッセージが出ればOK。＞　
- **showメソッド**　配下でない講師４が作成したお知らせ３でテスト　
　URL：【GET】api/v1/manager/notification/3　
　結果：Forbiddenが出たのでOK！

- **storeメソッド** 　配下ではない講師４が作成したcourse_id:4をbodyに入れてテスト
　URL：【POST】api/v1/manager/course/notification
　body ：
```
　"course_id": 4,
　"instructor_id": 1,
　"title": "あああああ",
　"type": "always",
　"start_date": "2024-11-27 15:30:45",
　"end_date": "2025-11-27 15:30:45",
　"content": "あああああああああああああああああああああ"
```
　**結果：本来出てくるべきエラーとは違う下記のようなエラーが出てきてしまった。course_id は数値にしているつもりです。statusは必須となっていますが、validationルールには書いていないように思いますので何を記載すべきかわからないです。失敗。**
```
　{
  　  "message": "The course id must be an integer. (and 1 more error)",
    　"errors": {
       　 "course_id": [
          　  "The course id must be an integer."
        　],
        　"status": [
           　 "The status field is required."
        　]
    　}
　}
```

- **updateメソッド** 　配下でない講師４が作成したお知らせ３でテスト　
　URL：【PATCH】api/v1/manager/notification/3　
　body：
```
　{
   　 "title": "あああああ",
    　"type": "always",
    　"start_date": "2024-11-27 15:30:45",
    　"end_date": "2025-11-27 15:30:45",
    　"content": "あああああああああああああああああああああ"
　}
```
　結果：　Forbidden　が出たのでOK！

- **bulkDeleteメソッド**　関係ない講師が作成したお知らせ３をフロント側で選択したと仮定しテスト
　URL：【DELETE】api/v1/manager/notification
　body：　
```
　{
   　 "notifications": [3]
　}
```
　結果：Forbiddenが出たのでOK！

＜500エラー箇所をthrow $eに変更。意図的に例外を発生させてcatchブロックに飛ばすテスト＞　
- **bulkDeleteメソッド**
　catchブロックのthrow $eをテストするため、VScodeのtryの下に一時的にエラーを追加。（テスト後削除）
```
   　         throw new \Exception('テスト');
```
　ログインした講師が作成したお知らせ１をフロント側で選択したと仮定しテスト
　URL：【DELETE】api/v1/manager/notification
　body：　
```
　{
  　  "notifications": [1]
　}
```
　結果：500 Internal Server Error 、"message": "テスト”。意図的に発生させた例外「テスト」というメッセージが含まれているので、例外が正しくスローされてキャッチされた。OK！

**<ins>講師側　Notification Controller</ins>　講師（ id:2 ）でログイン**

＜403をthrow new AuthorizationException（）に変更し、アクセス権限のテストを実施。それぞれ指定されているエラーメッセージが出ればOK。＞　　

- **showメソッド** 　別の講師が作成したお知らせ３でテスト
　URL：【GET】api/v1/instructor/notification/3
　結果："Forbidden, not allowed to access this notification.” が出たのでOK！

- **bulkDeleteメソッド**　別の講師が作成したお知らせ３をフロント側で選択したと仮定しテスト
　URL：【DELETE】api/v1/instructor/notification
　body：　
```
　{
  　  "notifications": [3]
　}
```
　結果：Forbiddenが出たのでOK！

＜500エラー箇所をthrow $eに変更。意図的に例外を発生させてcatchブロックに飛ばすテスト＞　
- **bulkDeleteメソッド**
　catchブロックのthrow $eをテストするため、tryの下に一時的にエラーを追加。（テスト後削除）
```
   　         throw new \Exception('テスト');
```
　ログインしている講師が作成したお知らせ２をフロント側で選択したと仮定しテスト。
　URL：【DELETE】api/v1/instructor/notification
　body：
```
　{
  　  "notifications": [2]
　}
```
　結果：500 Internal Server Error 、"message": "テスト”。意図的に発生させた例外「テスト」というメッセージが含まれているので、例外が正しくスローされてキャッチされた。OK！

## ご確認をお願いしたいこと
- ほとんど自分で調べながら正しいテスト結果を返すことができましたが、１つだけ出るべきではないエラーが出てしまいました。これに関しては自分で解決することができませんでした。他の各テストと合わせて、失敗したテストに関しご指導よろしくお願いいたします。

2024-11-28 10:52 UTC, yukihiroLaravel requested changes
ご指摘させていただきました！

2024-11-28 10:52 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            throw new AuthorizationException('Forbidden.');
すみません、現状はあまり統一できていないのですが、
エラー内容は下記の書き方にしていることがこのプロジェクトだと多いと思いましたので
このように書き換えていただけますでしょうか？
`throw new AuthorizationException('Invalid instructor_id.');`

他の下記のようになっている箇所も、上記のように書き換えていただけると幸いです。
`throw new AuthorizationException('Forbidden, not allowed to access this notification.');`

よろしくお願いします！

2024-11-28 10:52 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            throw new AuthorizationException('Forbidden, not allowed to access this notification.');
すみません、現状はあまり統一できていないのですが、
エラー内容は下記の書き方にしていることがこのプロジェクトだと多いと思いましたので
このように書き換えていただけますでしょうか？
`throw new AuthorizationException('Invalid instructor_id.');`

他の下記のようになっている箇所も、上記のように書き換えていただけると幸いです。
`throw new AuthorizationException('Forbidden, not allowed to access this notification.');`

よろしくお願いします！

2024-11-28 10:52 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +            throw new AuthorizationException('Forbidden.');
すみません、現状はあまり統一できていないのですが、
エラー内容は下記の書き方にしていることがこのプロジェクトだと多いと思いましたので
このように書き換えていただけますでしょうか？
`throw new AuthorizationException('Invalid instructor_id.');`

他の下記のようになっている箇所も、上記のように書き換えていただけると幸いです。
`throw new AuthorizationException('Forbidden, not allowed to access this notification.');`

よろしくお願いします！

2024-11-28 10:52 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +            throw new AuthorizationException('Forbidden.');
すみません、現状はあまり統一できていないのですが、
エラー内容は下記の書き方にしていることがこのプロジェクトだと多いと思いましたので
このように書き換えていただけますでしょうか？
`throw new AuthorizationException('Invalid instructor_id.');`

他の下記のようになっている箇所も、上記のように書き換えていただけると幸いです。
`throw new AuthorizationException('Forbidden, not allowed to access this notification.');`

よろしくお願いします！

2024-11-28 10:52 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +            throw new AuthorizationException('Forbidden.');
すみません、現状はあまり統一できていないのですが、
エラー内容は下記の書き方にしていることがこのプロジェクトだと多いと思いましたので
このように書き換えていただけますでしょうか？
`throw new AuthorizationException('Invalid instructor_id.');`

他の下記のようになっている箇所も、上記のように書き換えていただけると幸いです。
`throw new AuthorizationException('Forbidden, not allowed to access this notification.');`

よろしくお願いします！

2024-11-28 10:52 UTC, yukihiroLaravel commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +            throw new AuthorizationException('Forbidden.');
すみません、現状はあまり統一できていないのですが、
エラー内容は下記の書き方にしていることがこのプロジェクトだと多いと思いましたので
このように書き換えていただけますでしょうか？
`throw new AuthorizationException('Invalid instructor_id.');`

他の下記のようになっている箇所も、上記のように書き換えていただけると幸いです。
`throw new AuthorizationException('Forbidden, not allowed to access this notification.');`

よろしくお願いします！

2024-11-28 12:03 UTC, Kujiran40 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            throw new AuthorizationException('Forbidden, not allowed to access this notification.');
承知しました！

2024-11-28 12:04 UTC, Kujiran40 commented on app/Http/Controllers/Api/Instructor/NotificationController.php
> +            throw new AuthorizationException('Forbidden.');
承知しました！

2024-11-28 12:04 UTC, Kujiran40 commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +            throw new AuthorizationException('Forbidden.');
承知しました！

2024-11-28 12:04 UTC, Kujiran40 commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +            throw new AuthorizationException('Forbidden.');
承知しました！

2024-11-28 12:04 UTC, Kujiran40 commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +            throw new AuthorizationException('Forbidden.');
承知しました！

2024-11-28 12:05 UTC, Kujiran40 commented on app/Http/Controllers/Api/Manager/NotificationController.php
> +            throw new AuthorizationException('Forbidden.');
承知しました！

2024-11-29 11:50 UTC, kou-tech approved these changes

2024-11-29 12:03 UTC, merged