JKA-991　全チャプター削除処理2(しみず)
yukihiroLaravel/juko_laravel pull request #730
Opened 2024-12-15 11:51 UTC by shimizu-e

## jka-991 全チャプター削除処理

###  概要
kou さんに段階を分けていただいて
- 第一目標 : 全チャプターを削除する処理
- 第二目標 : 全チャプターを削除時にレッスンが削除されていないことを確認し、レッスンも削除する処理(lessons)
- 第三目標 : レッスンの受講状態がある場合は削除できない仕様のため認可エラー(403)を返す(lesson_attendances)
- 第四目標 : リクエストの講座IDの作成者が認証ユーザーと一致しない場合は認可エラー(403)を返す
- 第五目標 : トランザクション処理を追加し、エラー時はロールバックする処理を追加し、エラーメッセージを返す処理を追加する
こちらの第二目標をやっています。
しかし、レッスンが消えず困っています。
今の状態では　"message": "Property [chapters] does not exist on this collection instance.",　とでています。
よろしくお願いいたします。

#### 補足
プルリクをトピックにしたかったのですが、うまくいきませんでしたのでnext-developにしています。

2024-12-15 12:38 UTC, kou-tech requested changes

2024-12-15 12:38 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +        get();
`find()`から`get()`に変更した理由はありますか？
まずはその際の挙動の違いとかを理解してみると分かるかもしれないです！

2024-12-15 12:38 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +        get();
その後に次のコードでチャプターのidを格納した配列を作成できます！
Slackで提示した方法は`chapter_id`となっていましたが、こちらはテーブルの主キーである`id`と一致させる必要があり、提示したコードが誤っておりました。

```php
$chapterIds = $course->chapters->pluck('id')->toArray();
```

2024-12-15 12:38 UTC, kou-tech commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +        get();
チャプターが削除されない件については以前記述されていた次のコードが消えていますが、何か意図がありますか？

```php
        Chapter::where('course_id', $courseId)->delete();
```

2024-12-17 12:37 UTC, closed without merging

2024-12-20 13:45 UTC, shimizu-e commented on app/Http/Controllers/Api/Instructor/ChapterController.php
> +        get();
lesson::where('course_id', $courseId)->delete();
これに書き直すのかとおもっていました。修正します！